### ISSUE TITLE
feat: Environments

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash#1042]
We have last weeks been working hard on implementing proper support for environments in Unleash. A lot of the code is already merged to master, and we are finalizing the final release (beta version already being tested).

"Environment" is an improved way to organize activation strategy configurations for feature toggles into separate environments. In Unleash a feature lives across all your environments, after all, the goal is to get the new feature released as soon as possible, but it makes sense to configure the activation differently per environment. 

Unleash Enterprise users have been able to leverage strategy constraints to control the roll-out per environment. This will not be needed after the release as a "full group" of activation strategy will belong to an environment. 

Connected applications will use environment specific API keys, to make sure they only download feature toggle configurations for the environment they are running in.

Metrics has also been upgraded to record the environment, so that Unleash now can display the usage metrics per environment.

![image](https://user-images.githubusercontent.com/158948/137791680-2c5584cd-d842-4a32-8c6e-fda682519df6.png)

**Release plan:**
- Will be released as early accesses, behind a feature flag, in v4.2 to allow us to collect feedback and performance metrics. 
- The plan is to make environments generally available in v4.3 of Unleash. 

**Who gets access?**
- **Open-Source** and **Unleash Hosted Pro** will get access to two environments: "development" and "production", in addition to a "default" environment to ease migration. 
- **Enterprise** will get access to full flexibility and can customize environments fully. 

Initial draft for the environment documentation:
https://docs.getunleash.io/user_guide/environments

**Comment by PEZ** [comment]
This sounds very cool! However, I don't actually follow. 😄 I think I would benefit from a couple of example scenarios that show me how I would do something today compared to how I will be doing it when this feature is available.

**Comment by vencivenc** [comment]
@ivarconr Hello, I see this feature was merged in the 4.2.0 but the Docker images were not built, when do you plan to build the new images?

**Comment by ivarconr** [comment]
Our plan is to ship that very soon. We are currently piloting it and doing a few more fixes before we publish the docker image.

**Comment by ivarconr** [comment]
It has been out for a while, `EXP_ENVIRONMENTS=true` would be the flag to enable it.

**Comment by ivarconr** [comment]
v4.3 is now released and GA
