### ISSUE TITLE
Documentation on custom strategies needs to be clear on parameters vs context

### ISSUE THREAD

**Issue by chriswk** [Unleash/unleash#1047]
We should update documentation for custom strategies to better explain where parameters are coming from (What's defined when you create the strategy for the feature toggle) and context - (unleash's static context, plus whatever parameters are passed in the `isEnabled` call's second parameter.

Thanks to https://unleash-community.slack.com/archives/CGP2MCHPF/p1634605223059500

**Comment by ivarconr** [comment]
has this been improved already @thomasheartman ?

**Comment by thomasheartman** [comment]
Yes, this was covered in #1205, I think. I'm happy to open this up again if we get more input on it, but I think we can close it for now. Thanks for alerting me, Ivar! 🙏🏼
