### ISSUE TITLE
Use bcryptjs instead of bcrypt ?

### ISSUE THREAD

**Issue by ishnmu** [Unleash/unleash#1108]
Since bcryptjs is pure js implementation and doesn't require any additional modules its super lightweight. 

Having bcrypt introduces the need of node-gyp, python, node-pre-gyp. What say ?

**Comment by ivarconr** [comment]
It sounds like a good idea. The pure js implementation is probably slower, but that's fine as we are only using it to hash+salt passwords. 

Are there any other known drawbacks?

**Comment by ishnmu** [comment]
Hey @ivarconr thanks for your quick response. Agree bcrypt is ~3 times faster than its js implementation `bcryptjs` , beyond that no other disadvantages i see.
