### ISSUE TITLE
Support for default API token in docker

### ISSUE THREAD

**Issue by mjuraj** [Unleash/unleash#1153]
Hi,

**This is our setup:**
- we are running Unleash in production.
- when developing locally and testing on sandbox, we also run instances of unleash (locally with docker, sandbox with helm) to be as close to production as possible.
- we use the export and import API (`admin/state/{import, export}`) to always have all our features defined and default values set.

**The problem:** it is tiresome to create the API token again and again for every new sandbox (we're talking about tens of sandboxes a week). First we have to deploy a new sandbox (with unleash), then we have to manually create the token, and then we have to redeploy all services so it would have that token as an environment variable and could communicate with unleash.

**Proposed solution:** allow for an environment variable to be set which, if defined, creates a default API token.

Thank you for the awesome product!
Juraj

**Comment by ivarconr** [comment]
Yes this makes sense. 

It should support a list of tokens and follow the new token format `projectName:environment:some-random-chars`. Might need an option for client tokens and a separate option for admin tokens.

**Comment by corbinschwartz** [comment]
@ivarconr @mjuraj are there any plans to add support for an `INIT_CLIENT_API_TOKENS` env variable?

**Comment by ivarconr** [comment]
@corbinschwartz yes we should add that as well.
