### ISSUE TITLE
Provide parameter type in the feature client API

### ISSUE THREAD

**Issue by borisguery** [Unleash/unleash#1159]
Calling `/api/client/features` returns features as well as associated strategies with their parameters:

```json
{
  "features": [
    {
      "strategies": [
        {
          "name": "CustomStrategy",
          "parameters": {
            "isVIP": "true"
          }
        }
      ]
    }
  ]
}
```

In the UI when we select `bool` as parameter type, the UI provides a toggle which is converted to `"true"` or `"false"` string.

This is particularly annoying because it requires complex conditionals on client side to determine if the value is actually just a string containing `"true"` or a boolean value of `true`.
The same may applies to `number` while it is more easily manageable.

I would suggest to provides the parameter type to the API.
Having this done directly in the API will simplify Client implementation as they won't have to do custom interpretation of the value but determines the type from the parameter configuration.

```json
{
  "features": [
    {
      "strategies": [
        {
          "name": "CustomStrategy",
          "parameters": {
            "isVIP": {
              "type": "boolean",
              "value": true // or even "true" it does not matter since we know which type the value is
            },
            "organisationIdsList": {
              "type": "list", // the client knows that it will have to split the value, we may want to provide a typed list such as `numberList` or `stringList` but `list` may be sufficient for most case.
              "value": "123,456,789",
            }
          }
        }
      ]
    }
  ]
}
```

**Comment by ivarconr** [comment]
This is a good suggestion, and is probably how we would have designed it today. 

The API was designed 5 years ago, and we already have a lot of SDKs that would need to be upgraded if we change the format. Obviously we would need to provide the new and old format in parallel to now break backwards compatibility, which will increase the payload towards clients.

The assumption the API was designed under was that a custom activation strategy would know the parameters it takes and the type of them, so I am not sure if I fully agree that it is that hard to know the parameter type on the client side. 

This would be something we can consider for Unleash v5.
