### ISSUE TITLE
Unleash - Windows Docker image 

### ISSUE THREAD

**Issue by nihilsomani** [Unleash/unleash#1171]
Is the docker image for windows available? I could not find it in docker hub.

**Comment by ivarconr** [comment]
I'm not sure what you are asking? The current docker image should be possible to run on a windows machine using docker for Windows.

**Comment by nihilsomani** [comment]
C:\Program Files\Docker\Docker>docker run -p 4242:4242 -e DATABASE_HOST=postgres -e DATABASE_NAME=unleash -e DATABASE_USERNAME=unleash_user -e DATABASE_PASSWORD=some_password -e DATABASE_SSL=false --network unleash unleashorg/unleash-server
**WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (windows/amd64) and no specific platform was requested**
[2021-12-09T06:06:04.397] [ERROR] server-impl.js - Failed to migrate db OperationalError: getaddrinfo EAI_AGAIN postgres
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26) {
  cause: Error: getaddrinfo EAI_AGAIN postgres
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'postgres'
  },

**Comment by nihilsomani** [comment]
![image](https://user-images.githubusercontent.com/72813647/145350284-a2858b94-7582-4220-8521-41bef6637bae.png)

**Comment by nihilsomani** [comment]
image does not run on windows platform , Please see the error and also docker hub it states linux/amd64

**Comment by nihilsomani** [comment]
I' see this error on docker for windows.

**Comment by nihilsomani** [comment]
It worked after switching to Linux containers on docker for windows.
