### ISSUE TITLE
Dependency between toggles

### ISSUE THREAD

**Issue by Agraphie** [Unleash/unleash#1179]
Hi,

I was wondering if it is possible to create dependencies between toggles. After checking in Slack I was told it's currently not supported so I wanted to open a feature request here.

Scenario:
We have several fine-granular kill-switches (in our current & custom, non-unleash system). We also have toggles which can trigger these fine-granular toggles. Like a "panic" toggle which enables all kill-switches.

Feature suggestion:
It would be great to be able to create such dependencies in unleash. Or define sets and super-sets of toggles (although a complete hierarchy is probably very advanced).

I hope I outlined the idea. Let me know if I can support.

**Comment by simonkaspersen** [comment]
I am also looking for something like this. My scenario is that I have:

- toggle.feature
- toggle.feature.create
- toggle.feature.moderate

So when I ask for `toggle.feature.create` it will also look at `toggle.feature` which is the root-toggle for that feature.
Not sure if it was clearly explained

**Comment by thomasheartman** [comment]
Hey! 🙋🏼 Thanks for opening the feature request. 

You are right in that it's not something that Unleash has built-in support for at the moment, but we recognize that it would be useful in certain cases. 

However, while Unleash doesn't let you work this kind of hierarchy via the UI at the moment, it's absolutely possible to do it manually on the client by checking both (or all) toggles. 

You could either write the full check every time, or extract it into a function like this (in JS):

```js
const featureAspectEnabled(featureAspect) => 
  unleash.isEnabled('toggle.feature') && unleash.isEnabled(featureAspect)
```

Similarly, if you have more toggles, you could iterate over them like this:

```js
const allEnabled(toggles) => toggles.every(unleash.isEnabled)
```

(Of course: extract parameters as you wish and adapt the code your languages.)

Does that solve your needs for now or is there something that couldn't be addressed this way? Depending on the depths of your hierarchy, this could become unwieldy, though, and if you need to keep things in sync across clients, that could also pose a bit of an issue. There may very well be other things I'm missing too; I'd love to hear your thoughts on this!

**Comment by Agraphie** [comment]
Hi. Thanks for your reply.

You summed it up very well. We could do it that way and it would work. As you mentioned, it's a bit hard to  keep in sync across clients and also becomes a bit cumbersome in the code.  The use case would be to have e.g. "switch of all non-vital functionality" switch. So in the UI everyone could declare if a feature can be safely switched off if we are in a degraded state. In the code you'd just have to check 
`unleash.isEnabled('degradedStateMode')` and that's about it. Or imagine you'd have external alerts like Grafana and once an alert gets triggered, you'd want to enable a bunch of switches to degrade the system. You could add several different REST calls (alert sources in Grafana) and it would work, it's just not as convenient and whenever you'd add another "non-vital" switch you have to update all the code and all the resources.

I hope I could shed some more light on the convenience.

**Comment by thomasheartman** [comment]
Thanks, that's great! 😄 More insight into what use cases it might solve is always very handy in cases like these. While we can definitely see the use case for it, it would also come with a fair bit of extra complexity, so we'll need to discuss this internally before we can commit to anything one way or the other.

**Comment by Agraphie** [comment]
Would still be great if this feature gets implemented at some stage :)

**Comment by thomasheartman** [comment]
I agree! It's something we hear about from time to time, but we have other priorities at the moment. It seems probable that we'll implement something that offers the same functionality somewhere down the road, but I can't give you any notion of when that would be 🤷🏼 You're probably better off finding workarounds (such as the one above) for now, I think 💁🏼
