### ISSUE TITLE
Metrics from the clients

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash#124]
It would be awesome if the clients could send metrics data to server and have the admin-ui show some simple sliding window stats. 

We should start very basic. It could be that the clients counts number for request for a toggle in predefined time-buckets. This data could then be sent to the unleash-service regularly and the server could be responsible to aggregate the counts and provide a simple API for the aggregated data. This data could then be presented in a simple graph in the Admin UI making it more interactive!

any thoughts?

**Comment by ivarconr** [comment]
related to #153

**Comment by ivarconr** [comment]
we need to provide:

- [ ] API documentation @sveisvei 
- [ ] [unleash-client-java](https://github.com/finn-no/unleash-client-java) implementation
- [ ] [unleash-client-node](https://github.com/Unleash/unleash-client-node/tree/metrics) implementation (in progress by @sveisvei

**Comment by sveisvei** [comment]
I think the node client is done, need to test stability before releasing 1.0

**Comment by ivarconr** [comment]
Almost done with the java-client, just need to review PR and add a disable metrics option, so we can roll release and roll out the client before the unleash server is ready.

**Comment by ivarconr** [comment]
We probably also should land the API'urls before releasing the clients. I think moving them to `/api/*` makes sense. We just need to keep the `/features` route a few versions to be backward compatible with running clients.

**Comment by sveisvei** [comment]
Makes sense to add the new routes, but dont think the client needs changes? its `domain.com/` vs `domain.com/api/`

**Comment by ivarconr** [comment]
Good point, make sense that you supposed to specify the path to the API endpoints.

**Comment by sveisvei** [comment]
Updated the api docs.

**Comment by ivarconr** [comment]
https://github.com/Unleash/unleash/commit/b1e11794f84613becc3978f9f64d3119ea0f253a
