### ISSUE TITLE
unleash with cockroachdb as backend

### ISSUE THREAD

**Issue by dbist** [Unleash/unleash#1240]
I'm trying to run Unleash server with CockroachDB as backend. Forgive me if my issue sounds naive, I'm new to Unleash and node. The issue I'm having starts I believe at migration 7 https://github.com/Unleash/unleash/blob/ff7be7696c5b42997990c30f3cbecaed82a2fffd/src/migrations/20160618193924-add-strategies-to-features.js
All previous migrations appear to be working.

```sql
root@roach-0:26257/unleash> show tables;
  schema_name | table_name | type  | owner | estimated_row_count | locality
--------------+------------+-------+-------+---------------------+-----------
  public      | events     | table | root  |                   1 | NULL
  public      | features   | table | root  |                   0 | NULL
  public      | migrations | table | root  |                   7 | NULL
  public      | strategies | table | root  |                   1 | NULL
```

```sql
root@roach-0:26257/unleash> select * from events;
          id         |         created_at         |       type       | created_by |                               data
---------------------+----------------------------+------------------+------------+--------------------------------------------------------------------
  725583036242821121 | 2022-01-06 20:26:09.925033 | strategy-created | migration  | {"description": "Default on or off Strategy.", "name": "default"}
```

```sql
root@roach-0:26257/unleash> select * from migrations;
          id         |                         name                          |         run_on
---------------------+-------------------------------------------------------+--------------------------
  725583034835861505 | /20141020151056-initial-schema                        | 2022-01-06 20:26:09.513
  725583034993934337 | /20141110144153-add-description-to-features           | 2022-01-06 20:26:09.562
  725583035597094913 | /20141117200435-add-parameters-template-to-strategies | 2022-01-06 20:26:09.748
  725583036130295809 | /20141117202209-insert-default-strategy               | 2022-01-06 20:26:09.911
  725583036253962241 | /20141118071458-default-strategy-event                | 2022-01-06 20:26:09.949
  725583036317892609 | /20141215210141-005-archived-flag-to-features         | 2022-01-06 20:26:09.967
  725583037432135681 | /20150210152531-006-rename-eventtype                  | 2022-01-06 20:26:10.309
(7 rows)
```

```sql
root@roach-0:26257/unleash> select * from strategies;
          created_at         |  name   |       description        | parameters_template
-----------------------------+---------+--------------------------+----------------------
  2022-01-06 20:26:09.897414 | default | Default on/off strategy. | NULL
```

I believe the issue is that in this particular migration, the `exports.down` code gets called and not `exports.up`. 

https://github.com/Unleash/unleash/blob/ff7be7696c5b42997990c30f3cbecaed82a2fffd/src/migrations/20160618193924-add-strategies-to-features.js#L23

I'm not familiar with this framework and was wondering why in this particular migration the second block gets called and not first? Testing these statements individually works. 

```bash
[2022-01-06T20:37:02.280] [ERROR] server-impl.js - Failed to migrate db error: column "strategies" does not exist
    at Parser.parseErrorMessage (/unleash/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/unleash/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/unleash/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/unleash/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  length: 105,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'column_resolver.go',
  line: '196',
  routine: 'NewUndefinedColumnError'
}
[ERROR] error: column "strategies" does not exist
    at Parser.parseErrorMessage (/unleash/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/unleash/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/unleash/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/unleash/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

If you can point me in the right direction, I'd be happy to continue working on this. Thank you

**Comment by dbist** [comment]
additionally, here's a repro environment in case you'd like to take a look https://github.com/dbist/cockroach-docker/tree/main/cockroach-unleash

**Comment by ivarconr** [comment]
Hi @dbist,

thanks for reaching out! There is no reason "down" should be called. Unleash depends on a library called db-migrate, and only the up commands are executed by unleash at startup. Down is only used manually via the cli. 

I doubt it, but could it simply be the "sql comments" that trips it over? We have not used to many of these else-where. 

I had a quick peek in to the demo-setup you provided, but have some difficulties running the [up.sh](https://github.com/dbist/cockroach-docker/blob/main/cockroach-unleash/up.sh#L3). I have never seen `docker compose..` instead of `docker-compose` before, is that a new capability in docker, is a typo? In order to debug further

**Comment by ivarconr** [comment]
So I manage to get it all running. What it seems like from my testing is that we cannot assume a column of type json to be present immediately in cockroach,

```sql
ALTER TABLE features ADD COLUMN strategies" json;

UPDATE features
SET strategies = ('[{"name":"'||f.strategy_name||'","parameters":'||f.parameters||'}]')::json
FROM features as f
WHERE f.name = features.name;

ALTER TABLE features DROP COLUMN "strategy_name";
ALTER TABLE features DROP COLUMN "parameters";
```

it fails because the column "strategies" column does not yet exist on the features table, even though that SQL command was executed first.

**Comment by ivarconr** [comment]
Found this in the [cockroach docs](https://www.cockroachlabs.com/docs/stable/alter-column.html)

> **Note**:
> Most ALTER COLUMN TYPE changes are finalized asynchronously. Schema changes on the table with the altered column may be restricted, and writes to the altered column may be rejected until the schema change is finalized.

So it basically confirms that add column is async and we cannot assume the new column exists right away, as with regular postgres.

**Comment by ivarconr** [comment]
So I learned a bit more cockroach today. You cannot alter tables inside a transaction (1), which is basically what db-migrate do migrations. I am a bit unsure how to make these migrations actually work on cockroach then, and still guarantee that either it runs and migrate the date, or it fails and does not do anything. 

1. https://www.cockroachlabs.com/docs/v21.2/online-schema-changes#examples-of-statements-that-fail

**Comment by ivarconr** [comment]
A simple workaround could be perform a initial migration on postgres and transform that to cockroach, and disable database migration in unleash for now. 

At least that would allow you to validate if there are runtime-parts not working.

**Comment by dbist** [comment]
Thank you @ivarconr for a detailed response. I'm going to test the workaround and see if it's a viable solution. I also noticed the following ticket https://github.com/Unleash/unleash/issues/898 are the issues described in that ticket observed before my issue is surfaced or this is something else entirely? I'm working internally with my team to see where we are with the issues in #898.

**Comment by dbist** [comment]
just an update, I updated my repo with a PG container. Unleash starts without problems, I generated a pgdump file and attempted to restore to CockroachDB. I've encountered a couple of issues that engineering is looking at. One of each has an easy workaround. With sequences, we don't support `AS integer` syntax until next release so we have to comment that out in the pgdump.

```sql
CREATE SEQUENCE public.migrations_id_seq
    --AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
```

Then, I get stuck at 

```sql
ERROR: referenced table "public.migrations_id_seq" not found in tables being imported (public.tag_types,public.unleash_session,public.client_instances,public.projects)
```

stay tuned.

**Comment by dbist** [comment]
an update, I'm able to import the pgdump successfully with the above change. I'm attempting to start Unleash using this database and encountering the following error

```bash
[ERROR] TypeError: Cannot read property '1' of null
    at Client_PG._parseVersion (/unleash/node_modules/knex/lib/dialects/postgres/index.js:130:56)
    at Query.<anonymous> (/unleash/node_modules/knex/lib/dialects/postgres/index.js:124:22)
    at Query.handleReadyForQuery (/unleash/node_modules/pg/lib/query.js:138:12)
    at Client._handleReadyForQuery (/unleash/node_modules/pg/lib/client.js:290:19)
    at Connection.emit (events.js:400:28)
    at /unleash/node_modules/pg/lib/connection.js:114:12
    at Parser.parse (/unleash/node_modules/pg-protocol/dist/parser.js:40:17)
    at Socket.<anonymous> (/unleash/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by ivarconr** [comment]
Took a quick peek on my phone. Would it simply work to specify a database version, via the DATABASE_VERSION env variable, see https://docs.getunleash.io/deploy/configuring_unleash#further-customization).

**Comment by dbist** [comment]
I was thinking that but I was not aware of PG env variable to assign. Glad there is one from Unleash! It helped me advance but I'm getting the following error now

```bash
[2022-01-11T17:55:18.798] [ERROR] server-impl.js - Failed to migrate db error: relation "migrations" is offline: importing
    at Parser.parseErrorMessage (/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 107,
  severity: 'ERROR',
  code: 'XXUUU',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'descriptor.go',
  line: '419',
  routine: 'FilterDescriptorState'
}
[ERROR] error: relation "migrations" is offline: importing
    at Parser.parseErrorMessage (/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
Unleash started on http://localhost:4242
```
Also, we apparently claim full support for Knex, and the version you're using in `package.json` is supposed to be supported.

**Comment by dbist** [comment]
I think it's because there is no `migrations` table in the pgdump.

**Comment by dbist** [comment]
@ivarconr our engineering is saying to use our own dialect `client: cockroachdb` vs. `client: pg` 
https://github.com/cockroachlabs/example-app-node-knex/blob/main/app.js#L4
vs. https://github.com/Unleash/unleash/blob/master/src/lib/db/db-pool.ts#L10
what will it take swapping out the client? Can I recompile this somehow or do I need a custom image?

**Comment by dbist** [comment]
The good news is Unleash UI is up, even with pg client
![image](https://user-images.githubusercontent.com/461296/149000444-093d9c72-ac8b-47da-86b4-e6d98cacb7eb.png)

**Comment by ivarconr** [comment]
> what will it take swapping out the client? Can I recompile this somehow or do I need a custom image?

we have not added a config for setting the database client, but that should be an easy fix. You should be able to just clone the repo and start it locally against the cockroachdb, given that you have node.js installed. 

Steps:
1. clone the unleash project 
2.  change the client defined in [db-pool.ts](https://github.com/Unleash/unleash/blob/master/src/lib/db/db-pool.ts#L10)
3. update connect options in [server-dev.ts](https://github.com/Unleash/unleash/blob/master/src/server-dev.ts) to use details for the local cockroachdb server
4. start unleash locally: 
  ```
  yarn install
  yarn start:dev
  ```


> still some underlying issues, I wonder if switching clients will do the trick

I doubt the change of client will help with this issue. This is actually the same bug as mentioned #898, where knex-session uses some incompatible queries. There seems to be some activity on that project again so maybe worth pinging them on the issue for it at: https://github.com/gx0r/connect-session-knex/issues/84

If you are running unleash locally you can actually disable usage of the database for session, by setting the `session.db` option to `false`. This would at least allow you to validate the other parts of unleash together with cockroachdb.

**Comment by dbist** [comment]
@ivarconr seems like it is working, I'm not seeing the errors as before. I do still need to run the initial migration in PG, restore the pgdump into CockroachDB then follow your step 1-4 and off we go!

![image](https://user-images.githubusercontent.com/461296/149177252-c7d30bc7-43ed-432c-9da6-7a3ab5923b78.png)

I created a feature in the UI, session seems to persist, didn't need to disable `session.db`. The feature propagated to the database

**Comment by ivarconr** [comment]
This is awesome 🔥 

If I understand you correctly, the only thing we need to find a solution for  is the database migrations then? Did you do any other adjustments?

**Comment by dbist** [comment]
in pgdump, I had to comment out `--AS integer` before importing into CockroachDB and then restoring the database to CockroachDB. After that, I followed your exact steps and it started. I've played around with feature toggles and intentionally tried to break the application but aside from adding a user, everything else seems to succeed?

![image](https://user-images.githubusercontent.com/461296/149192730-b59d4d56-cfa5-4f22-a380-48499356a052.png)

For the migrations, do you think splitting up the steps into separate migration files would do the trick? I wonder if we execute each SQL statement in their own separate migration step we can overcome the asynchronous nature.

**Comment by dbist** [comment]
@ivarconr so I spoke with schema engineer and he said splitting DDL from DML from individual migrations will help. My early tests show good results.

Take for example https://github.com/Unleash/unleash/blob/master/src/migrations/20160618193924-add-strategies-to-features.js
I split it into 3 files

![image](https://user-images.githubusercontent.com/461296/149399780-c725a97f-5607-4ece-a27c-708d6857c8f5.png)

file 1

```
'use strict';

exports.up = function (db, callback) {
    db.runSql(
        `
--create new strategies-column
ALTER TABLE features ADD "strategies" json;
       `,
        callback,
    );
};

exports.down = function (db, callback) {
    db.runSql(
        `
--create old columns
ALTER TABLE features ADD "parameters" json;
ALTER TABLE features ADD "strategy_name" varchar(255);
    `,
        callback,
    );
};
```

file 2

```
'use strict';

exports.up = function (db, callback) {
    db.runSql(
        `
--populate the strategies column
UPDATE features
SET strategies = ('[{"name":"'||f.strategy_name||'","parameters":'||f.parameters||'}]')::json
FROM features as f
WHERE f.name = features.name;
       `,
        callback,
    );
};

exports.down = function (db, callback) {
    db.runSql(
        `
--populate old columns
UPDATE features
SET strategy_name = f.strategies->0->>'name',
   parameters = f.strategies->0->'parameters'
FROM features as f
WHERE f.name = features.name;
    `,
        callback,
    );
};
```

file 3

```
'use strict';

exports.up = function (db, callback) {
    db.runSql(
        `
--delete old strategy-columns
ALTER TABLE features DROP COLUMN "strategy_name";
ALTER TABLE features DROP COLUMN "parameters";
       `,
        callback,
    );
};

exports.down = function (db, callback) {
    db.runSql(
        `
--drop new column
ALTER TABLE features DROP COLUMN "strategies";
    `,
        callback,
    );
};
```

if before I failed on this step and migration errored out on strategies table, I'm now failing on 

```
[2022-01-13T14:51:10.122] [DEBUG] server-impl.js - DB migration: start
[2022-01-13T14:51:17.881] [ERROR] server-impl.js - Failed to migrate db error: column "parameters" does not exist
    at Parser.parseErrorMessage (/Users/artem/Documents/Customers/Greenlight/011222/unleash/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/Users/artem/Documents/Customers/Greenlight/011222/unleash/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/artem/Documents/Customers/Greenlight/011222/unleash/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/Users/artem/Documents/Customers/Greenlight/011222/unleash/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
From previous event:
    at Object.runSql (/Users/artem/Documents/Customers/Greenlight/011222/unleash/node_modules/db-migrate-pg/index.js:634:12)
    at /Users/artem/Documents/Customers/Greenlight/011222/unleash/dist/migrations/20161212101749-better-strategy-parameter-definitions.js:25:16
    at processImmediate (node:internal/timers:473:21) {
  length: 105,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'column_resolver.go',
  line: '196',
  routine: 'NewUndefinedColumnError'
}
error: column "parameters" does not exist
    at Parser.parseErrorMessage (/Users/artem/Documents/Customers/Greenlight/011222/unleash/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/Users/artem/Documents/Customers/Greenlight/011222/unleash/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/artem/Documents/Customers/Greenlight/011222/unleash/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/Users/artem/Documents/Customers/Greenlight/011222/unleash/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
From previous event:
    at Object.runSql (/Users/artem/Documents/Customers/Greenlight/011222/unleash/node_modules/db-migrate-pg/index.js:634:12)
    at /Users/artem/Documents/Customers/Greenlight/011222/unleash/dist/migrations/20161212101749-better-strategy-parameter-definitions.js:25:16
    at processImmediate (node:internal/timers:473:21) {
  length: 105,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'column_resolver.go',
  line: '196',
  routine: 'NewUndefinedColumnError'
}
```

and you can see that migrations table now has 13 rows instead of 8 from before

![image](https://user-images.githubusercontent.com/461296/149400039-46ab417f-54ae-420c-a8b3-39bb00ce570f.png)

I'm going to continue until I have a clean migration and hopefully it will just run. The longer term question is whether we can pull these changes into your codebase to officially support CockroachDB. We don't want to have a fork.

**Comment by dbist** [comment]
I will need help on this migration, I'm not a javascript expert but we need to separate the `UPDATE` and schema change tasks.

```
/* eslint camelcase: "off" */

'use strict';

const async = require('async');

exports.up = function (db, callback) {
    const populateNewData = (cb) => {
        db.all(
            'select name, parameters_template from strategies',
            (err, results) => {
                const updateSQL = results
                    .map(({ name, parameters_template }) => {
                        const parameters = [];
                        Object.keys(parameters_template || {}).forEach((p) => {
                            parameters.push({
                                name: p,
                                type: parameters_template[p],
                                description: '',
                                required: false,
                            });
                        });
                        return { name, parameters };
                    })
                    .map(
                        (strategy) => `
                UPDATE strategies 
                SET parameters='${JSON.stringify(strategy.parameters)}'
                WHERE name='${strategy.name}';`,
                    )
                    .join('\n');

                db.runSql(updateSQL, cb);
            },
        );
    };

    async.series(
        [
            db.addColumn.bind(db, 'strategies', 'parameters', { type: 'json' }),
            populateNewData.bind(db),
            db.removeColumn.bind(db, 'strategies', 'parameters_template'),
        ],
        callback,
    );
};

exports.down = function (db, callback) {
    const populateOldData = (cb) => {
        db.all('select name, parameters from strategies', (err, results) => {
            const updateSQL = results
                .map(({ name, parameters }) => {
                    const parameters_template = {};
                    parameters.forEach((p) => {
                        parameters_template[p.name] = p.type;
                    });

                    return { name, parameters_template };
                })
                .map(
                    (strategy) => `
                UPDATE strategies 
                SET parameters_template='${JSON.stringify(
                    strategy.parameters_template,
                )}'
                WHERE name='${strategy.name}';`,
                )
                .join('\n');

            db.runSql(updateSQL, cb);
        });
    };

    async.series(
        [
            db.addColumn.bind(db, 'strategies', 'parameters_template', {
                type: 'json',
            }),
            populateOldData.bind(db),
            db.removeColumn.bind(db, 'strategies', 'parameters'),
        ],
        callback,
    );
};
```

**Comment by dbist** [comment]
next working migration

https://github.com/Unleash/unleash/blob/master/src/migrations/20170211085502-built-in-strategies.js

file 1

```
'use strict';

const async = require('async');

exports.up = function (db, cb) {
    async.series(
        [
            db.addColumn.bind(db, 'strategies', 'built_in', {
                type: 'int',
                defaultValue: 0,
            }),
        ],
        cb,
    );
};

exports.down = function (db, cb) {
    return db.removeColumn('strategies', 'built_in', cb);
};
```

file 2

```
'use strict';

const async = require('async');

exports.up = function (db, cb) {
    async.series(
        [
            db.runSql.bind(
                db,
                "UPDATE strategies SET built_in=1 where name='default'",
            ),
        ],
        cb,
    );
};

exports.down = function (db, cb) {
    return db.removeColumn('strategies', 'built_in', cb);
};
```

![image](https://user-images.githubusercontent.com/461296/149403421-d66d4d09-d0fc-428c-8110-9802075f6101.png)

I did delete the better strategy migration in order to advance as I'm not sure how to go around it yet.

**Comment by dbist** [comment]
we also have to fix 

```sql
ALTER TABLE client_instances ADD PRIMARY KEY (app_name, instance_id);
```

```sql
ERROR: cannot use nullable column "app_name" in primary key
SQLSTATE: 42P15
```

**Comment by dbist** [comment]
for [migration](https://github.com/Unleash/unleash/blob/master/src/migrations/20210624114602-change-type-of-feature-archived.js) need to set `SET enable_experimental_alter_column_type_general = true;`

**Comment by dbist** [comment]
for [migration](https://github.com/Unleash/unleash/blob/master/src/migrations/20210624114602-change-type-of-feature-archived.js) we need to set the following `SET CLUSTER SETTING sql.defaults.experimental_alter_column_type.enabled = true;` at the cluster level prior to any migration

**Comment by ivarconr** [comment]
It's really nice that you found a viable path forward. 

>  I spoke with schema engineer and he said splitting DDL from DML from individual migrations will help. My early tests show good results.

In general I agree, but splitting these migrations into to separate files comes with a few new concerns:

1. The name of the file is currently used to track whether a migration has already been executed, and I do fear that the introduction of new files can break exiting migrations. We might need to take additional steps to make sure this only applies to fresh installations. 
2. Splitting DDL and DML makes sense in its own, but it has often been the case that we changed the db structure and thus also needed to reformat existing data. Doing that in a single transaction has been practical, and it might require temp-tables between the migrations to make sure no data is lost. 

> The longer term question is whether we can pull these changes into your codebase to officially support CockroachDB. We don't want to have a fork.

Yes, indeed that would be preferable, as long as the overhead is bearable. I will assume some syntax fixes here and there, but that should be manageable. If Unleash would be to officially support CockroachDB we would also like to get automated tests set up. We already have a quite extensive set of e2e-tests which includes a postgres database. 

Also did you evaluate the already existing db-migrate binding for cockroachdb [link](https://github.com/db-migrate/cockroachdb )?

**Comment by dbist** [comment]
>Also did you evaluate the already existing db-migrate binding for cockroachdb link?
We have it under community supported [tooling](https://www.cockroachlabs.com/docs/v21.2/community-tooling.html#schema-migration-tools). I'm researching how much coverage we've done here.

**Comment by sighphyre** [comment]
I read the blogpost, great piece of work, I'm guessing this is solved so I'm going to close this
