### ISSUE TITLE
Externalization of postgres DB for Unleash...!

### ISSUE THREAD

**Issue by tariqmum** [Unleash/unleash#1284]
Hi Guys, 

Thanks, in advance to answer me question. I would like to install postgres outside of the Kubernetes env, while I am using Unleash docker image, will that be supported to connect my external postgres DB ? Will that be working by defining DATABASE_URL ?

Thanks

**Comment by thomasheartman** [comment]
Hey! 👋🏼 

Yes, using a database outside your Kubernetes cluster should work just fine, assuming there's nothing stopping network calls. Set the `DATABASE_URL` and the username and password as usual, and that should be enough. 

Let me know if it doesn't work or if you have any other questions. You can also use the [Unleash Slack](https://join.slack.com/t/unleash-community/shared_invite/enQtNjUxMjU2MDc0MTAxLTJjYmViYjkwYmE0ODVlNmY1YjcwZGRmZWU5MTU1YTQ1Nzg5ZWQ2YzBlY2U1MjlmZDg5ZDRmZTMzNmQ5YmEyOGE) for questions like this ☺️
