### ISSUE TITLE
Database adapter-pattern

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash#132]
Now we have totally locked unleash to postgres. It should be possible to plugin your own database adapter for whatever database you would like to use. 

Benefits: 
- This will make it easier for others to adopt unleash. 
- It will be easier to write great tests, as you can just provide a simple mock for the db. 
- It will be possible to run unleash in "in-memory" mode, just to test it out, without persistence.

**Comment by stigkj** [comment]
This also enables using something like [Consul](https://www.consul.io/) as the backend, which makes unleash very scalable and with no SPOF backend. The clients would need to also support reading configuration from a local consul agent, of course.

**Comment by ivarconr** [comment]
exactly :+1:

**Comment by ivarconr** [comment]
closing for now as I don't think to prioritize it. Some can re-open and contribute if they feel this is really required.
