### ISSUE TITLE
Error running with docker 

### ISSUE THREAD

**Issue by meeximum** [Unleash/unleash#1326]
Hi,

since version 4.6.1 it's not possible to run the image 
unleashorg/unleash-server:4.6.x (tried today 4.6.5)

I got the following error
_internal/modules/cjs/loader.js:905

  throw err;
  ^
Error: Cannot find module '/unleash/npm'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}_

here my yml file

**version: "3.4"
services:
  unleash:
    image: unleashorg/unleash-server:4.6.5
    networks:
      - traefik-public
      - net
    environment:
      DATABASE_HOST: "db"
      DATABASE_NAME: "unleash"
      DATABASE_USERNAME: "xxx"
      DATABASE_PASSWORD: "xxx"
      DATABASE_SSL: "false"
    depends_on:
      - db
    command: npm run start
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.unleash-http.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.unleash-http.entrypoints=http
        - traefik.http.routers.unleash-https.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.unleash-https.entrypoints=https
        - traefik.http.routers.unleash-https.tls=true
        - traefik.http.services.unleash.loadbalancer.server.port=4242
        - traefik.http.services.unleash.loadbalancer.server.scheme=http

  db:
    image: postgres:13
    networks:
      - net
    environment:
      POSTGRES_DB: "unleash"
      POSTGRES_USER: "xxx"
      POSTGRES_PASSWORD: "xxx"

networks:
  net:
    driver: overlay
    attachable: true

  traefik-public:
    external: true**

**Comment by ivarconr** [comment]
Hi, we did not expect you to run with npm. 

> command: npm run start

The official docker file uses node to start the app. We removed npm dependency in our docker image, because it was not used, and it drags along vulnerable (unused) dependencies. 

Could you use this command instead:

`command: node index.js`

**Comment by meeximum** [comment]
perfect! thx
