### ISSUE TITLE
Duplicate FKs in a table

### ISSUE THREAD

**Issue by govinda209** [Unleash/unleash#1360]
Role_permissions table has duplicate FKs. Would it be possible to remove one of them?
Foreign-key constraints:
    "fk_role_permission" FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
    "role_permission_role_id_fkey" FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE

**Comment by ivarconr** [comment]
This must have been an oversight. We should remove one of them.
