### ISSUE TITLE
[Feature request]: Slack integration per environment

### ISSUE THREAD

**Issue by Meemaw** [Unleash/unleash#1361]
Would be great if we could filter by environment in our slack integration. E.g. when features are toggled in `production` environment, we would post a #production slack channel.

**Comment by ivarconr** [comment]
Makes sense!

**Comment by laurafiuza** [comment]
Yes, would love to create a Slack channel that posts whenever someone changes a `production` environment toggle, because sometimes without the filter it can be too noisy. Any chance this can be built? :)

**Comment by thomasheartman** [comment]
For sure! We can't give any details just yet, but we'll probably tackle this within the next couple months 😄

**Comment by thomasheartman** [comment]
In progress, so not stale 😄 Backend was merged in #1800 and frontend in https://github.com/Unleash/unleash-frontend/pull/1133. @chriswk is this all done or is there anything left to do?

**Comment by ivarconr** [comment]
Was included in v4.14.x release
