### ISSUE TITLE
feat: Add search field on project view

### ISSUE THREAD

**Issue by mistic100** [Unleash/unleash#1372]
Can you add a features search on the page of a project ?

Screenshot of said page :
![Capture d’écran du 2022-02-16 11-21-30](https://user-images.githubusercontent.com/41597/154244634-624f2880-f972-4d97-b18b-ffd302ba3509.png)

Previously we used the homepage but since the status was removed (#1148) we now tend to use the project page.

Thank you.

**Comment by FredrikOseberg** [comment]
> Can you add a features search on the page of a project ?
> 
> Screenshot of said page : ![Capture d’écran du 2022-02-16 11-21-30](https://user-images.githubusercontent.com/41597/154244634-624f2880-f972-4d97-b18b-ffd302ba3509.png)
> 
> Previously we used the homepage but since the status was removed (#1148) we now tend to use the project page.
> 
> Thank you.

Thanks for the request. This has been planned for Q1 and will be implemented shortly.

**Comment by ivarconr** [comment]
released as part of v4.9

![image](https://user-images.githubusercontent.com/158948/162070528-a5a5cf33-55ca-4b63-bfeb-7ab31982b037.png)

**Comment by ivarconr** [comment]
Where do you see the releases missing (I see the release tab in github has some inconsistencies) but v4.9.1 should be available on both npm and docker.

**Comment by gabel** [comment]
That was the confusing part, I did not see any tags/releases on github (https://github.com/Unleash/unleash/releases) but in dockerhub (https://hub.docker.com/r/unleashorg/unleash-server/tags) the versions are available. Thanks for clarifying.
