### ISSUE TITLE
Webhook missing tagging events

### ISSUE THREAD

**Issue by abhinav1708** [Unleash/unleash#1374]
We are implementing some logic based on tagging event of feature.
We are using webhook to listen to events but currently webhook doesn't support tagging event

**Comment by abhinav1708** [comment]
I have opened a pull request which fixes this issue
#1355

**Comment by sighphyre** [comment]
Thanks so much for your contribution! The PR has been merged so I'm going to close this

**Comment by chriswk** [comment]
fixed in 66c66c7
