### ISSUE TITLE
How to use the JavaScript proxy

### ISSUE THREAD

**Issue by babajonni** [Unleash/unleash#1378]
I'm struggling with CORS when using the JavaScript proxy. In the documentation is says to create the client as:

```
const unleash = new UnleashClient({
  url: 'https://eu.unleash-hosted.com/hosted/proxy',
  clientKey: 'your-proxy-key',
  appName: 'my-webapp',
});
```

Is the url supposed to be the same API url that is displayed for my company in our admin page: https://app.unleash-hosted.com/xxxx/api/?

Can the CORS issue be due to that? I'm running the JS client in an app hosted at localhost.

**Comment by ivarconr** [comment]
Hi there, 

the proxy is hosted separately. please reach out to contact@getunleash.io

**Comment by babajonni** [comment]
> Hi there,
> 
> the proxy is hosted separately. please reach out to [contact@getunleash.io](mailto:contact@getunleash.io)

Email sent.

**Comment by babajonni** [comment]
> Hi there,
> 
> the proxy is hosted separately. please reach out to [contact@getunleash.io](mailto:contact@getunleash.io)

Email sent.
