### ISSUE TITLE
The documentation for the node client-sdk doesn't mention events

### ISSUE THREAD

**Issue by SimonSimCity** [Unleash/unleash#1386]
The documentation of the client-sdk for node (https://docs.getunleash.io/sdks/node_sdk) does not mention any of the available events (https://github.com/Unleash/unleash-client-node#events). Maybe its best to just link to the readme of the repository instead of having two docs you need to keep in sync.

**Comment by ivarconr** [comment]
Thanks for pointing this out. None of the SDK tutorials in the docs currently explains all the capabilities of the SDKs. We plan to move more of the individual SDK docs in the the combined documentation. Stay tuned!

**Comment by thomasheartman** [comment]
@SimonSimCity Yes, you're right! Thanks for raising this 😄 What Ivar says is correct: we've got plans to start integrating the documentation from the SDK repos into docs.getunleash.io, so we'll only need to keep one set of docs up to date. It's been researched and we've found a way forward, so it's on the way ✌🏼

**Comment by ivarconr** [comment]
any updates on this @thomasheartman ?

**Comment by thomasheartman** [comment]
Not yet, I'm afraid. With the OpenAPI work and other things going on, we haven't gotten around to actually implementing this, though.
