### ISSUE TITLE
Cannot access OpenAPI demo instance

### ISSUE THREAD

**Issue by connorads** [Unleash/unleash#1387]
http://unleash.herokuapp.com
http://unleash.herokuapp.com/oas/
![image](https://user-images.githubusercontent.com/10026538/155313339-604eee4c-3a6c-4823-bfd3-a0187962b65e.png)

Plenty of references to unleash.herokuapp.com in code/docs that are currently broken
https://github.com/Unleash/unleash/search?q=unleash.herokuapp.com

**Comment by ivarconr** [comment]
Hi @connorads 

it was down due to a full database on the Heroku setup. I just cleared the database so it should be resolved again.
