### ISSUE TITLE
Addon's that make HTTPS requests to external services should accept proxy configuration

### ISSUE THREAD

**Issue by goodtune** [Unleash/unleash#1390]
When configuring the Slack handler, I noticed that messages were not making it to our instance.

Looking at the code of the addon and researcing proxies in node, it appears that environment variables `https_proxy` and `HTTPS_PROXY` are not supported.

To make on-premise installations work in corporate environments this can be a blocker.

**Comment by ivarconr** [comment]
Seems like we would then need to setup a ProxyAgent together with fetch (or whatever http library we end up using).
https://stackoverflow.com/a/65418122

**Comment by ivarconr** [comment]
If we switch to make-fetch-happen it seems to have built-in support 
https://www.npmjs.com/package/make-fetch-happen#opts-proxy
