### ISSUE TITLE
https://docs.getunleash.io/sdks/unleash-proxy#toggle-data says 2 different things for the value of enabled when a toggle has no variants

### ISSUE THREAD

**Issue by jf** [Unleash/unleash#1414]
https://github.com/Unleash/unleash/blob/main/website/docs/sdks/unleash-proxy.md:

![Screenshot 2022-03-04 at 13 56 23](https://user-images.githubusercontent.com/7270/156711425-809c3fe4-f11b-48d7-8c9a-329d47c03442.png)

**Comment by jf** [comment]
closed by https://github.com/Unleash/unleash/commit/e6d939508d5d9b2f72c59d6fd94cdafcc44e42a1. Thanks, @thomasheartman !

**Comment by thomasheartman** [comment]
Any time! 😄
