### ISSUE TITLE
Use docker for tests involving the db

### ISSUE THREAD

**Issue by SimenB** [Unleash/unleash#146]
It's annoying having to setup psql locally. A `Dockerfile` capable of building the db for testing should be included, and be used by default in the test scripts

**Comment by tfheen** [comment]
pg_virtualenv might also be used, which is a lot less overhead than a full container.

**Comment by SimenB** [comment]
Will that still require me to have postgres installed? Not much work doing `brew install postrgesql` (or `brew cask install postgres` which I ended up doing), but having to set up the environment is a pain point.
I suppose I'd still have to install `pg_virtualenv`, but if it's scripted (at least the sql necessary), that'd be a big improvement

**Comment by tfheen** [comment]
It requires you to have postgres installed, yes, and it gives you a new shell with the various environment variables set up.  A typical run looks like:

```
$ pg_virtualenv 
install: cannot change owner and permissions of «/tmp/pg_virtualenv.t2j5mg/postgresql/9.5»: Operasjonen er ikke tillatt
Creating new cluster 9.5/regress ...
  config /tmp/pg_virtualenv.t2j5mg/postgresql/9.5/regress
  data   /tmp/pg_virtualenv.t2j5mg/data/9.5/regress
  locale nb_NO.UTF-8
  socket /tmp
  port   5433
Warning: The parent /var/run/postgresql of the selected
stats_temp_directory is not writable for the cluster owner. Not adding this
setting in postgresql.conf.
$ env | grep ^PG
PGPORT=5433
PGUSER=tfheen
PGDATABASE=postgres
PGPASSWORD=baX7beiC3di0mozauPh0
PGHOST=localhost
PGSYSCONFDIR=/tmp/pg_virtualenv.t2j5mg/postgresql-common
PG_CLUSTER_CONF_ROOT=/tmp/pg_virtualenv.t2j5mg/postgresql
PG_CONFIG=/usr/lib/postgresql/9.5/bin/pg_config
$ createdb foo
$ psql -l
                               List of databases
   Name    | Owner  | Encoding |   Collate   |    Ctype    | Access privileges 
-----------+--------+----------+-------------+-------------+-------------------
 foo       | tfheen | UTF8     | nb_NO.UTF-8 | nb_NO.UTF-8 | 
 postgres  | tfheen | UTF8     | nb_NO.UTF-8 | nb_NO.UTF-8 | 
 template0 | tfheen | UTF8     | nb_NO.UTF-8 | nb_NO.UTF-8 | =c/tfheen        +
           |        |          |             |             | tfheen=CTc/tfheen
 template1 | tfheen | UTF8     | nb_NO.UTF-8 | nb_NO.UTF-8 | =c/tfheen        +
           |        |          |             |             | tfheen=CTc/tfheen
(4 rows)

$ exit
Dropping cluster 9.5/regress ...
$ 
```

**Comment by ivarconr** [comment]
We already have both pg_virtualenv (see [package.json](https://github.com/finn-no/unleash/blob/master/packages/unleash-api/package.json) support and a [docker script](https://github.com/finn-no/unleash/blob/master/packages/unleash-api/scripts/docker-postgres.sh) available. We have just used it for e2e testing.

I am happy to accept a PR with a `start:docker` or `start:pg_virtualenv` starting with a migrated database.

**Comment by ivarconr** [comment]
pg_virtualenv is debian based.
