### ISSUE TITLE
Support for WebSockets

### ISSUE THREAD

**Issue by Johnabell** [Unleash/unleash#1461]
Currently Unleash, Unleash Proxy and Unleash Proxy Clients all make use of long polling to update the toggles statuses.

It would be nice to have the option to make use of WebSockets to update the toggle statuses.

**Comment by chriswk** [comment]
Hi @Johnabell . We're not currently looking at this, but it's been brought up before. Our current public roadmap is available here:
https://github.com/orgs/Unleash/projects/5 . We'll take it into consideration when we're planning for Q3

**Comment by chriswk** [comment]
If anyone does want to have a go, we will not reject PRs out of hand.
