### ISSUE TITLE
Question: Is Unleash server pluggable?

### ISSUE THREAD

**Issue by resah** [Unleash/unleash#1467]
Hi,

I was wondering if it is possible to write Unleash plugins/extensions/addons, for example to add a REST-API endpoint?

If so, how would I configure the server to use the extension?

Regards
Theresa

**Comment by sighphyre** [comment]
Hi Theresa,

It depends on what you're needing to do but if you want to extend Unleash with some extra endpoints this is absolutely possible.

When you create your Unleash options, you'll need to pass in a a preRouterHook with your new custom endpoints, like so:

```
let options = {
    'preRouterHook': (app, config) => {
        app.use(
            `${config.server.baseUriPath}/api/customEndpoint`,
            (req, res) => {
                //Some cool new custom code
            }
        )
     }
};

unleash.start(options);
```

**Comment by resah** [comment]
Hi @sighphyre ,

thanks for your answer, I will try that.

Regards
Theresa
