### ISSUE TITLE
Crash on login with Google auth

### ISSUE THREAD

**Issue by floskel** [Unleash/unleash#1537]
### Describe the bug

Im seeing a crash on the API when trying to login with a Google account that has **not** yet been created/invited in the system. 

This is on a self hosted environment using version 4.8.2

The login method is configure to **not** auto-create users. 

### Steps to reproduce the bug

1. Use selfhosted Unleash API v4.8.2
2. Setup google auth as here: 
```
passport.use(
              new GoogleOAuth2Strategy(
                  {
                      clientID: process.env.GOOGLE_CLIENT_ID,
                      clientSecret: process.env.GOOGLE_CLIENT_SECRET,
                      callbackURL: process.env.GOOGLE_CALLBACK_URL,
                  },
                  async (accessToken, refreshToken, profile, done) => {
                      const email  = profile.emails[0].value;
                      const user = await userService.loginUserWithoutPassword(email, false);
                      done(
                          null,
                          user
                      );
                  },
              ),
          );
```
 3. Login with Google account that is not yet created in the system
 4. API server crashes with stacktrace: 

```
[ERROR] NotFoundError: No user found
    at rowToUser (/unleash/node_modules/unleash-server/dist/lib/db/user-store.js:36:15)
    at UserStore.getByQuery (/unleash/node_modules/unleash-server/dist/lib/db/user-store.js:111:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async UserService.loginUserSSO (/unleash/node_modules/unleash-server/dist/lib/services/user-service.js:190:20)
    at async Strategy._verify (/unleash/index.js:22:30)
```
5. Service is restarted

### Expected behavior

Expected behaviour would be: 
1. The server handles this gracefully
2. An error message is shown to the user with something like: "You dont have access to the system. Contact your admin"

### Logs, error output, etc.

```bash
See above
```

### Additional context

The primary reason we dont want to autocreate users is that they are defaulted to ADMIN role. If the default role is configurable to EDITOR, then that could also solve the issue

### Unleash version

Selfhosted 4.8.2

### Subscription type

Open source

### Hosting type

Self-hosted

**Comment by ivarconr** [comment]
Hi,

you need to try/catch the line where you are login in users, something like this:

```js
try {
  const user = await userService.loginUserWithoutPassword(email, false);
  const user = await userService.loginUserWithoutPassword(email, false);
  done(null, user);
} catch(error) {
  done(error)
}
```

**Comment by floskel** [comment]
Thanks a lot. I will try it out. I really appreciate the fast responses and helpful attitude here 😎
