### ISSUE TITLE
Support databaseSchema in Version 4.X

### ISSUE THREAD

**Issue by Pfuenzle** [Unleash/unleash#1565]
### Describe the feature request

Hi,
in older versions (3.X), it was possible to specify a database schema via the start option "databaseSchema".
It seems this has been removed in the newer versions 4.X.
The only reference to it I could find was on a old documentation site from version 3.

Is there a reason this has been removed? It would be very practical to have this option enabled again.

### Background

The database we are using is using schemas for every service thats connecting, so when I tried to update our unleash instance to version 4, I stumbled upon this error and am not sure how to solve it without the additional parameter

### Solution suggestions

Implement "databaseSchema" in version 4 and forward

I dont think this has any drawbacks, as noone is forced to use it.

Thanks :)

**Comment by ivarconr** [comment]
Hi you still can, but it was moved to the db options. 

See https://github.com/Unleash/unleash/blob/main/src/lib/create-config.ts#L100 for reference. 

It seems to have been missed in our doc section though. It would be fantastic if you have time to open a PR improving our docs. 
https://docs.getunleash.io/deploy/configuring_unleash#database-configuration

**Comment by Pfuenzle** [comment]
Hi, thanks for the fast answer :)
It is working correctly now. thanks a lot.
Sure, I will add it to the docs today.

**Comment by chriswk** [comment]
Docs updated to point out the new way to define schema.
Fixed in #1567
