### ISSUE TITLE
datadog tag type and value are reversed

### ISSUE THREAD

**Issue by connorteague** [Unleash/unleash#1568]
When attempting to get event logs from unleash server in Datadog the tag shows up as `tag.value:tag.type` this seems to be backwards compared to the intent. 

Suggested fix:
Unleash/unleash/src/lib/addons/datadog.ts: lines 31-32
```
        const tags =
            eventTags && eventTags.map((tag) => `${tag.type}:${tag.value}`);
```

**Comment by chriswk** [comment]
Hi Connor. Great catch. I've approved the PR #1569, will be merged sometime today :)
