### ISSUE TITLE
Strict schema restrictions introduced in 4.11.0

### ISSUE THREAD

**Issue by Meemaw** [Unleash/unleash#1611]
### Describe the bug

It seems that some strict schema restrictions were introduced in version 4.11.0. Those don't play well with list strategies, where one would like to enable a feature for a lot of users whitelisted by ids:

<img width="433" alt="Screen Shot 2022-05-19 at 10 52 37 AM" src="https://user-images.githubusercontent.com/8524109/169328039-c78536b8-6ba1-49df-b907-45ff171de36f.png">

**Comment by FredrikOseberg** [comment]
You're right. Thanks for reporting, this will be fixed promptly.

**Comment by FredrikOseberg** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [OpenAPI Schemas block list strategies parameters](https://trello.com/c/bvbNoIOK/1175-openapi-schemas-block-list-strategies-parameters)

**Comment by FredrikOseberg** [comment]
This should be resolved in 4.11.1
