### ISSUE TITLE
Fake Proxy for CI/CD Testing; enabling control over feature flags inside e2e tests

### ISSUE THREAD

**Issue by TimHaboldt** [Unleash/unleash#1619]
### Describe the feature request

We recently implemented Unleash in our codebase and now struggle to find an existing way to handle feature flags in our Selenium-Tests reliably. We want a solution to properly test all code paths related to a feature toggle inside a CI/CD Pipeline. Just testing one path or another isn't a solution. This in return needs us to be able to properly hard-set a feature flag from inside a test environment without actually influencing the code directly. We don't wanna create a custom userId and set it inside the unleash-client or smth similar. 

### Solution suggestions

The best solution we thought about would be to implement a fake unleash proxy which the unleash-proxy-client connects to. All feature flags inside the proxy should be changeable via an API endpoint. The unleash proxy can be started before the test and manipulated inside the test.

**Comment by nunogois** [comment]
Hi @TimHaboldt - Thanks for opening this issue! We've seen this and will get back with more information soon.

**Comment by nunogois** [comment]
Hi @TimHaboldt - After discussing this internally we believe you might be able to leverage the `UnleashClient` bootstrap feature to manage this: https://github.com/Unleash/unleash-proxy-client-js#bootstrap
We're currently not planning on building towards the specific feature you mentioned, at least in the near future, but hopefully this will be a suitable workaround for your current needs.
Let me know if this helps, and if there's anything else I can help you with!
