### ISSUE TITLE
Split into multiple repos

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash#163]
As we now have a `Unelash` org it feels better to split in multiple reps, instead of doing internal multi-packages via lerna. 

I suggest the following repos:
- `unleash-api` as a separate repo
- `unleash-frontend` as a separate repo
- `unleash` (this repo) kept, but only responsibility to release the `unleash-server`artifact (possibly also rename this repo to `unleash-server`.
- `unleash-demo-app` 
- `unleash-server-docker`

**Comment by sveisvei** [comment]
Seams reasonable, we dont have any need for multi-repo/lerna in practice.

**Comment by ivarconr** [comment]
Yes, it seems to me the overhead is bigger than the gain

**Comment by ivarconr** [comment]
After some though I think we should simplify a bit, I really dont see the need for a sparate api and server repo at this point. 

- `unleash` (this repo.)
- `unleash-frontend` as a separate repo
- `unleash-demo-app` as a separate repo. 
- `unleash-server-docker` as a separate repo

**Comment by sveisvei** [comment]
Done deal
