### ISSUE TITLE
Unleash 4.12 filter stops after a short time

### ISSUE THREAD

**Issue by checketts** [Unleash/unleash#1637]
### Describe the bug

(Congrats on the release, I'm looking forward to this!)

Running Unleash 4.12 and filtering by features works, but only for a short time. After about 10 seconds it feels like the list refreshes, but without taking into account the filter, so all toggler re-appear.

Also the *Project feature toggles (<count>)* doesn't show the filtered count. Please have that count match the filter

### Steps to reproduce the bug

1. Click on 'Projects' link
2. Select the Default project
3. Filter the list
4. Wait for a bit and the filtering stops, and instead shows all features

### Expected behavior

The filter to remain in place until it is cleared

### Unleash version

4.12

### Subscription type

Open source

### Hosting type

Self-hosted

**Comment by checketts** [comment]
Also the filter parameter is removed from the URL

**Comment by checketts** [comment]
This hasn't been straight forward to reproduce. My prod instance resets the filter after 10 seconds or so (and seems to align with a call to the `/api/admin/feature-types` endpoint). 

However my dev instance doesn't do it automatically. Instead when I toggle a feature then it resets the filters to something wrong that I had filtered on before.

For example I had filtered on `abc.` before but now am looking at `xyz.`, then toggle a feature and suddenly it is showing `abc.` toggles again.

**Comment by ivarconr** [comment]
thanks, I can confirm the filter is reset after a feature toggle is being switched. We will look in to this!

**Comment by checketts** [comment]
Eager to verify the fix. I'm guessing it will happen after #1641 is merged in?

**Comment by Tymek** [comment]
@checketts v4.12.3 is out, demo will be updated soon.

**Comment by checketts** [comment]
Just verified the fix. Thanks! It really looks great. This was the last outstanding UX pain point my users had been hitting on during their iteration planning meetings.

Also noticed that the toggle count doesn't change with the filter: 

<img width="757" alt="image" src="https://user-images.githubusercontent.com/416063/171212157-7b9b1c91-cbc8-4553-8a40-ed9e9a110f04.png">

Is that intentional? Or do you think we could update the count when filtering?
