### ISSUE TITLE
Toggle not found is logged as ERROR

### ISSUE THREAD

**Issue by theneva** [Unleash/unleash#164]
This creates a fairly large amount of noise in our logs. log4js-node doesn't have a simple API for fine-tuning log level based on http status code beyond "3xx => WARN, 4xx and 5xx => ERROR", but please fix it if/when replacing log4js with something else.

**Comment by ivarconr** [comment]
great stuff.. I vote for finding a better / more flexible logging framework.

**Comment by SimenB** [comment]
Yeah, log4js doesn't support json output (as far as I can google), which makes it a really bad fit for fiaas (or containers in general).
