### ISSUE TITLE
Restrict / Enable feature-toggle per connected appName

### ISSUE THREAD

**Issue by sveisvei** [Unleash/unleash#165]
We can based on headers(UNLEASH-APPNAME) from clients do a filter on which toggles isEnabled.

Main problem is how to do this in the UI...

**Comment by sveisvei** [comment]
Will be solved via https://github.com/Unleash/unleash/projects/3 and AND strategies.

**Comment by hhiptmair** [comment]
Hi! I'm having issues implementing this idea, could you please elaborate how this is possible with Unleash 3?
Is it possible to access the appName directly in a strategy without implementing a custom one for this information?

**Comment by ivarconr** [comment]
In Unleash-hosted this can be done with strategy constraints out of the box.

https://www.unleash-hosted.com/docs/strategy-constraints

**Comment by hhiptmair** [comment]
Do you also know a way of doing this with the self-hosted version?

**Comment by ivarconr** [comment]
With open-source you can to do custom strategy as appName is part of the unleash context.

**Comment by ivarconr** [comment]
> Do you also know a way of doing this with the self-hosted version?

FYI; Unleash-enterprise can also be self-hosted.

**Comment by hhiptmair** [comment]
Thanks for the super-fast response :) Interesting to hear about Unleash-enterprise as well, will check that as it's a requirement for us to host the application ourselves.

Regarding the original topic: I assumed that I can access the properties of the Unleash Context without having to implement a custom strategy as this information is already transmitted. This is not the case, right?
