### ISSUE TITLE
Have defaults for enviroment

### ISSUE THREAD

**Issue by sveisvei** [Unleash/unleash#177]
We should not require to export:
```
export DATABASE_URL=postgres://unleash_user:passord@localhost:5432/unleash
export TEST_DATABASE_URL=postgres://unleash_user:passord@localhost:5432/unleash_test
```

Rather we should have these values as default in dev.

**Comment by ivarconr** [comment]
Indeed: we need to have a better config/options abstractions

**Comment by ivarconr** [comment]
I belive this is fixed now. Tests have reasonable defaults and running locally with `npm run start:dev` also gives reasonable defaults according to docs.
