### ISSUE TITLE
Allow for migration style rollbacks of feature toggles

### ISSUE THREAD

**Issue by sheastyer** [Unleash/unleash#1793]
### Describe the feature request

Currently, you are unable to delete a feature toggle, you can only archive it. When it is archived, you are unable to create a new feature toggle using the same name. 

This **totally** makes sense from a design standpoint - it would certainly be a mess if you unknowingly created a new Feature Toggle using the same name and reactivated old feature paths. 

From a real world use-case scenario, we are trying to manage our Unleash config via source-controlled migration level scripts, leveraging the API. During a forward migration, we call the API and create a new feature toggle. If later on in the migration a step was to fail, it would be nice to 'rollback' the creation of that feature toggle. We could archive the flag, but when we are ready to migrate forward again, we would get a naming collision. 

One possibility would be to rename the new feature toggle to some random string of characters and then archive it, but to my knowledge you cannot rename a feature toggle. 

Any ideas on how we can get around that? Or ideas on a possible 'unsafe-delete' feature for use-cases where you know there are no uses of that toggle you wish to delete? 

### Background

We have multiple self-hosted Unleash apps for each environment we maintain, and would like to keep the config on each exactly the same, eliminating accidental misconfigs via human interaction on the dashboard. 

We achieved this through database style migration, where we specify our config and roll it out to each environment as a migration step. All config is tracked in source code and automatically deployed using CI.

**Comment by FredrikOseberg** [comment]
Hi there! We haven't exposed this through the UI, but there is a DELETE request that can be sent on a feature toggle that is already archived in order to delete it fully from the database. You can hit the `/api/admin/archive/{featureName}` endpoint to fully delete a feature toggle (that has been archived) from the database.

Closing this with the comment. Feel free to reopen if it didn't solve your use-case.
