### ISSUE TITLE
🟢 feat: SDK support for Global Segments

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash#1878]
### Describe the feature request

We have introduced a segmentation feature in Unleash (pro and enterprise). In order to make it more efficient also the SDK should add support for the new format.

### Background

SDK support:

- [x] Python SDK
- [x] Go SDK
- [x] Node.js SDK
- [x] Java SDK
- [x] Proxy SDKs (makes it available to all Proxy Clients)
- [x] Ruby SDK
- [x] PHP SDK ([PR](https://github.com/Unleash/unleash-client-php/pull/104))
- [x] .NET SDK
- [ ] Rust SDK

**Comment by sighphyre** [comment]
Nothing concrete at the moment, Rust is behind a number of features compared to the other SDKs. We'd like to close off custom stickiness and advanced constraints (both have active PRs open) before we tackle global segments
