### ISSUE TITLE
Application overview needs UI improvements

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash#188]
![image](https://cloud.githubusercontent.com/assets/158948/21431788/04c427f0-c869-11e6-9341-e902f9642307.png)

**Comment by sveisvei** [comment]
I can fix.

**Comment by ivarconr** [comment]
Cool :)

**Comment by sveisvei** [comment]
adjusted grid and shortened names. not perfect,but better. https://github.com/Unleash/unleash-frontend/commit/14a374e5535bfd715ba6058984048f23fd4cb1a5
