### ISSUE TITLE
Troubles with CORS preflight request

### ISSUE THREAD

**Issue by ammuradyan** [Unleash/unleash#1883]
### Describe the bug

Hello, we have Unleash self hosted version.

Browser does preflight request without Authorization header set. I'm getting 401 Unauthorized on OPTIONS /api/client/features/{featureName} request. If i request GET /api/client/features/{featureName} with Authorization header and token, everything is working properly. 

Am i missing something?

Thanks

### Subscription type

Open source

### Hosting type

Self-hosted

**Comment by olav** [comment]
Hello!

The client API is geared towards backend applications and does not support CORS.

To call Unleash directly from a browser or mobile app, check out `unleash-proxy`:

https://docs.getunleash.io/sdks/unleash-proxy

**Comment by ammuradyan** [comment]
Will try, thanks!
