### ISSUE TITLE
Going back from a toggle should keep scroll position

### ISSUE THREAD

**Issue by SimenB** [Unleash/unleash#190]
From e.g. `#/features/view/ad.disable.event.ad.confirmed` and pressing back in the browser loses the scroll-position I had on `#/features`

**Comment by sveisvei** [comment]
@SimenB this should be posted in unleash-frontend imo

**Comment by SimenB** [comment]
Bah, forgot about the split

**Comment by SimenB** [comment]
Unleash/unleash-frontend#27
