### ISSUE TITLE
Custom headers for webhook addon

### ISSUE THREAD

**Issue by FrancoisPoinsot** [Unleash/unleash#1915]
### Describe the feature request

With the webhook addons, we can customize the body of the request.
It would be useful to be able to do the same with headers.

Particularily if we need to specify an Authorization header to be able to reach an API.

**Comment by sjaanus** [comment]
@FrancoisPoinsot Thank you for input. This is a great idea and if you are up for contributing, we would be happy to accept a PR. If not, I think you need to wait a little bit, until we have time and capacity to implement it.
