### ISSUE TITLE
Encoding issues in stored username

### ISSUE THREAD

**Issue by sveisvei** [Unleash/unleash#197]
<img width="505" alt="skjermbilde 2017-01-04 kl 16 06 06" src="https://cloud.githubusercontent.com/assets/121438/21646760/c13d388a-d297-11e6-90f7-b3c4c316f6a7.png">

**Comment by ivarconr** [comment]
probably a cookie thingy!

**Comment by ivarconr** [comment]
a frontend issue, see https://github.com/Unleash/unleash-frontend/issues/39
