### ISSUE TITLE
Default strategy should actually be default

### ISSUE THREAD

**Issue by theneva** [Unleash/unleash#204]
When I create a new toggle, I have to manually select the `default` strategy from the list. It's not even at the top of the list! That's kind of annoying ~

**Comment by vsandvold** [comment]
I know it's not much, but would it help if default was first? Empty states can be quite useful - when done well they can teach you something about how the interface works, like how to add strategies in this case.

It would be nice to do something like this:
http://blog.invisionapp.com/why-empty-states-deserve-more-design-time/
https://material.io/guidelines/patterns/empty-states.html

For now, here's a very quick and ugly example of a list with default on top:
![fireshot capture 225 - new feature toggl_ - https___unleash-new-ui herokuapp com_ _features_create](https://cloud.githubusercontent.com/assets/6734787/22390311/9b18b0d4-e4ea-11e6-834d-15d704e92c75.png)

**Comment by sveisvei** [comment]
I think we should remove default-strategy from the store and clients - and if there are no strategies - default should be the result in the clients.

The UI should show a text describing what happens without a strategy - default on/of.

**Comment by ivarconr** [comment]
I have no strong opinions on this other than it should be more intuitive than it is today and your suggestion sounds better than our current approach. What do you think @vsandvold ?

**Comment by vsandvold** [comment]
I agree, default could be a sensible empty state, at least for how the UI
looks right now. It would be quite easy to add a short text to the edit
tab, and remove the default strategy from the list. The requirements may
change though, when we move towards a UI with strategy groupings etc.

Den ons. 28. jun. 2017, 21.27 skrev Ivar Conradi Østhus <
notifications@github.com>:

**Comment by ivarconr** [comment]
Decision: no strategy configured in the UI (https://github.com/Unleash/unleash-frontend) should just mean that you want the default strategy enabled, and the UI should just add that automatically. Default strategy should still be available in the list as it can in some cases make sense to combine it with other strategies for convenience.
