### ISSUE TITLE
Random stickiness for Variants feature

### ISSUE THREAD

**Issue by esafev** [Unleash/unleash#2054]
### Describe the bug

Hey! First of all, I say thank you for this product.

I want to use the Variants feature for a/b-testing and also want to disable stickiness for some experiments, but I only have the `default` stickiness parameter in the dropdown.

Can you tell me if this is a bug or a feature for Enterprise customers? If it is a bug, maybe it was fixed?

Thanks.

### Steps to reproduce the bug

1. Create a toggle

2. Designate two or more variants

3. Click on the dropdown with stickiness parameters

4. The dropdown has only `default` parameter

### Expected behavior

The Variants feature has the `default`, `userId`, `userSession` and `random` stickiness parameters.

### Screenshots

<img width="722" alt="image" src="https://user-images.githubusercontent.com/1667907/189482666-e6a9fdb8-ad5f-4d4f-a003-593042734d62.png">

### Unleash version

4.2.0-2

### Subscription type

Open source

### Hosting type

Self-hosted

**Comment by FredrikOseberg** [comment]
Hey there @esafev! 

This is actually a feature that is part of our paid offering. Currently the default stickiness will check for the presence of userId, sessionId or random of none of those are provided (proxy-client-js will add sessionId automatically though). We currently don't support turning stickiness off for variants. This sounds like an interesting feature though, you could flesh this idea out a bit and submit it as a feature request if you'd like. 

By the way, the current version of unleash is at 4.15.1, there's lots of good stuff there if you want to upgrade :)

Going to close this for now unless something was unclear. Feel free to reopen if you disagree.

**Comment by esafev** [comment]
Thank you. I will try to implement this feature and create a PR with this.

**Comment by FredrikOseberg** [comment]
> Thank you. I will try to implement this feature and create a PR with this.

Before you get too far on the PR, could you create an issue detailing the need and the proposed solution? We generally like to involve more team members for input on requests like this before committing to a solution :)
