### ISSUE TITLE
Improve logging for failing addon event handling

### ISSUE THREAD

**Issue by chriswk** [Unleash/unleash#2057]
### Describe the feature request

To help with debugging failing webhooks, I would like Unleash to start logging the actual error being caught in the fetch call

### Background

Trying to help a customer with failing webhooks that were simply logging
```
[INFO] addon/webhook - Handled event "feature-environment-disabled". Status code: undefined
```
today, made me realise that we're not giving ourselves or self-hosted users very much to go on when addons fail.

### Solution suggestions

We should probably in addon.ts fetchRetry's catch log the error with a separate logger so that it can be muted for our hosted solution and only turned on if we need to help debug it.

Something like

```
 async fetchRetry(
        url: string,
        options = {},
        retries: number = 1,
    ): Promise<Response> {
        let res;
        try {
            res = await fetch(url, {
                retry: {
                    retries,
                },
                ...options,
            });
            return res;
        } catch (e) {
    //THIS LINE: this.addonFetchLogger.error(e);
            res = { statusCode: e.code, ok: false };
        }
        return res;
    }
```

**Comment by gastonfournier** [comment]
What about https://github.com/Unleash/unleash/pull/2739 ?
