### ISSUE TITLE
Overall history logs for a project at one place 

### ISSUE THREAD

**Issue by XLAR-8** [Unleash/unleash#2060]
### Describe the feature request

I would like unleash to have  complete project level logs at one place. its very pain full to keep track of different feature datewise logs.

**Comment by FredrikOseberg** [comment]
Hi there! Thanks for this suggestion, we'll look into that. I agree that it would be a useful addition.

**Comment by ivarconr** [comment]
We already have an API to retrieve changes for a project. 
http://some-host.com/api/admin/events?project=default

Should be doable!

**Comment by aneeshrelan** [comment]
Is this something I can take a stab at? I am thinking:

1. Add an "Event Log" tab to the Projects view (the one where Overview, Health, Access, Environments, Archive) are present
2. Use a similar view like feature toggle events, to show up the results using the above mentioned API

Feel free to correct/add

**Comment by aneeshrelan** [comment]
Adding on the previous comment, I have a doubt on if we should extend the existing `useEventSearch` hook or create a new one altogether for this use case

**Comment by FredrikOseberg** [comment]
> Adding on the previous comment, I have a doubt on if we should extend the existing `useEventSearch` hook or create a new one altogether for this use case

Hi @aneeshrelan

Would be awesome to have this contributed. I think you have a good direction. It makes sense to me to make a new abstraction for clarity sake: 'useProjectEvents' or something similar.
