### ISSUE TITLE
recently inactive toggles appear active in metrics

### ISSUE THREAD

**Issue by rbtcollins** [Unleash/unleash#2103]
### Describe the bug

Note that this is 24+  hours after the toggle was removed from our app - so no usage for some time. While the chart is annotated with times, it isn't anchored to a point in time, so I can't tell if thats 4pm today, or yesterday - which wouldn't matter if the chart showed 'the last 48 hours' - but it appears to show 'the last 48 slices from the database' rather than 'the last 48 hours', which are very different things. 
![image](https://user-images.githubusercontent.com/499678/192736304-25d898b8-e6c1-4c72-9ab4-74b30396b2e9.png)

**Comment by nunogois** [comment]
Hi @rbtcollins - Thanks for opening the issue! Let me reach out to the team and we'll get back to you :)

**Comment by ivarconr** [comment]
The problem is that the API should produce the hour buckets for all hours, even if they do not exists in the db. The UI could also be better are showing the actual dates, as it becomes miss-leading the way it is currently displayed.

**Comment by ivarconr** [comment]
A fix is available behind an experimental flag in v4.17, allowing us to validate it in Unleash Cloud. 

It will be GA from unleash v4.18
