### ISSUE TITLE
Back link url from slack to unleash server is incorrect

### ISSUE THREAD

**Issue by uthark** [Unleash/unleash#2122]
### Describe the bug

Slack notification has wrong URL to the feature flag.

Correct link: https://XXX/projects/default/features/test
Generated link: https://XXX/projects/default/test

Note missing `/features` in url.

### Steps to reproduce the bug

1. Enable slack integration
2. Trigger flag update.
3. Get message in slack
4. Click on button "Open in unleash"

### Expected behavior

Feature flag page is opened.

### Unleash version

4.15.4

### Hosting type

Self-hosted

**Comment by nunogois** [comment]
Hi @uthark - Thanks for opening this issue! We'll investigate this and get back to you 👍

**Comment by Tymek** [comment]
Probably something wrong in `src/lib/addons/feature-event-formatter-md.ts`. Seems like something that can quickly be fixed. @uthark would you like to submit a PR?

**Comment by aneeshrelan** [comment]
I've raised a fix for this, hope that's fine! 😅
