### ISSUE TITLE
Total members is invalid on Project page in admin web

### ISSUE THREAD

**Issue by mosathip** [Unleash/unleash#2123]
### Describe the bug

Total members on Projects page are invalid
After the first installation of Unleash server its shows 0 members. It should be 1 member (default admin user)

### Steps to reproduce the bug

1. Go to Projects page (/projects)
2. See the total members of a project

### Expected behavior

Should show total members of project

### Logs, error output, etc.

```bash
0
```

### Screenshots

![Screen Shot 2565-10-02 at 21 30 46](https://user-images.githubusercontent.com/45855161/193459504-a3fa425b-5eee-4d08-b78c-584cfb66482f.png)

### Additional context

I thought it was the wrong key to map with the result of getting projects
according to code from src/lib/db/project-store.ts line 274 selects the project name and then adds field memberCount (line 104) into the result by using project id

![image](https://user-images.githubusercontent.com/45855161/193464341-1bdfc32d-1a07-425e-873b-0614c68e37d2.png)
![image](https://user-images.githubusercontent.com/45855161/193464468-f2d33fe1-c4af-486f-a1cd-7042dc1ffc32.png)

### Unleash version

4.15.4

### Subscription type

Open source

### Hosting type

Self-hosted

**Comment by nunogois** [comment]
Hi @mosathip - Thanks for opening this issue, we'll have a look and get back to you 👍

**Comment by aneeshrelan** [comment]
I went ahead and raised a fix for this. Seemed like a straightforward fix, hope that's fine
