### ISSUE TITLE
Diff in history list should take up available space

### ISSUE THREAD

**Issue by theneva** [Unleash/unleash#213]
This looks kind of weird, and cuts off half of the `"` in the case of this toggle:

![image](https://cloud.githubusercontent.com/assets/1404650/23554295/c135a678-0024-11e7-9804-c0c6caf030cc.png)

You can scroll to the right, but that seems unnecessary when there is available space.

**Comment by ivarconr** [comment]
Thanks ( btw PR welcomed!)

**Comment by vsandvold** [comment]
I'll take it :-)
