### ISSUE TITLE
Require revisionnumber for changes

### ISSUE THREAD

**Issue by SimenB** [Unleash/unleash#218]
To stop a change from overwriting a change which happened at the same time/since the user loaded the toggle info. You can see it from the history, if you notice, but changes might get lost.

**Comment by ivarconr** [comment]
Yes we could deffently do more to avoid collisions

**Comment by sveisvei** [comment]
Indeed - multiuser on same toggle is not solved in current setup. +1 for this.

**Comment by sveisvei** [comment]
@ivarconr Recon that would work.
