### ISSUE TITLE
Length of feature toggle

### ISSUE THREAD

**Issue by jandeschuttere** [Unleash/unleash#2185]
### Describe the bug

The length of the feature toggle is limited to 100, a constraint that I could not immediately spot in the documentation. Not sure if this can be updated, or if you could explain?

The length in the database is 255 according to https://github.com/Unleash/unleash/blob/e30ff2b822b13ef7bda11f35f8a2b12a20839759/src/migrations/20141020151056-initial-schema.js and the validation is done based on https://github.com/Unleash/unleash/blob/13ef025fab3c330f3e0197e732bb380a838c9125/src/lib/routes/util.ts#L22 which seems to be used for a couple of elements.

I do understand that having large toggle names might be easy for cluttering, url limitations and adds to bandwidth, however in our team we have a use case that could benefit from having them be larger and I'm not sure if the current constraints really are a concern. Is there a chance you could have this updated to what is supported in the db?

### Expected behavior

Have support on length to what is supported by the database

### Unleash version

4.12.6

### Subscription type

Open source

**Comment by ivarconr** [comment]
Hi @jandeschuttere 

thanks for raising this. 

There are a few concerns about the name length:
- we need to make sure it fit in the database (so we cannot have it bigger than the db support, also need to account for potential extra encoding of special chars, etc)
- we need to make sure the UI is able to display it. The current UI has assumptions about the name length. 
- we currently use the name in the url for API calls. There could be limits we need to account for. 

All the above could be addressed of course. 

Could you explain a bit on your use case on why you would need more than 100 chars? Wold be nice with some real world examples on how and why this would be useful.

**Comment by jandeschuttere** [comment]
Our use case is that we have multiple services moving into using unleash as a feature toggle provider.  One of those services acts as a workflow engine. That workflow engine is desired to have some granular control on the flows it acts upon. The way we structure/identify the flags is based on the service and flow it controls together with one or more parts that define logical elements within the flow itself. 

We would prefer not to move into abbreviations as those could make it harder to identify and manage those flags.

**Comment by thomasheartman** [comment]
@jandeschuttere You raise a good point, though! I don't think this _is_ documented anywhere (I'm not sure I was even entirely aware of it myself), but it definitely belongs in the feature toggle docs. I'll update that, at least. 🙋🏼

**Comment by ivarconr** [comment]
Thanks for clarifying @jandeschuttere.

We have no strong preference that the feature max length has to be exactly 100 chars. But changing this will require some validations on our end:

- will it impact the overall database performance for large setups (feature toggle names are used as foreign keys also) 
- will it impact the API, limits to path lengths etc. 
- will the UI still work, what happens if the feature toggle name does not fit in the UI container?

**Comment by jandeschuttere** [comment]
Thank you for considering the change. To my knowledge the main concern most likely will be the UI, but I let you do validation and look forward to the outcome!

**Comment by gastonfournier** [comment]
Hi @jandeschuttere! Thanks for the suggestion, after evaluating this with the team, we've decided that there's no one-size-fits-all length for the feature toggles' names. It's an arbitrary value, we had our reasons for it to be 100 and changing it is not worth the effort.

I hope you understand and continue contributing to Open Source!

Regarding _in our team we have a use case that could benefit from having them be larger_, I wonder if we can provide alternatives, but it'd be helpful to have more context about the use case. 

Please, feel free to comment or open a new issue about that particular use case.
