### ISSUE TITLE
REST API for Client and Proxy Client Key Lifecycle Management

### ISSUE THREAD

**Issue by deepbrook** [Unleash/unleash#2189]
### Describe the feature request

As an administrator, I want to be able to programmatically create client and proxy client api tokens via API, so that I may manage their lifecycle with an IaC tool of my choice.

### Background

We're managing unleash for a very big group of teams, and our on/offboarding process is being streamlined. This means we're looking to minimize manual labor. Unfortunately, we found that we cannot easily automate client key automation for new teams.

While #1956 enables teams to create keys for their clients themselves, this feature request addresses the need of admins to be able to centrally manage certain keys and ideally permissions.

### Solution suggestions

A simple CRUD api with admin permission requirements would do.

**Comment by thomasheartman** [comment]
Hey, @deepbrook 👋🏼 Thanks for the feature request and the detail you provide 😄 🙌🏼 

I would like to be clear on what you're asking for here, so please bear with me.

> programmatically create client and proxy client api tokens via API

For client tokens, does the `api/admin/api-tokens` endpoint not provide you with what you need? You can see the OpenAPI spec for your specific instance by [enabling OpenAPI and the swagger UI](https://docs.getunleash.io/how-to/how-to-enable-openapi) for your instance. 

The docs also contain a copy of the most up-to-date OpenAPI documentation (including for [creating API tokens](https://docs.getunleash.io/reference/api/unleash/create-api-token)). (Yes, they're a little bare-bones at the moment, but we're working on fleshing them out as we speak!)

For "proxy client api tokens", do you mean the tokens the proxy uses to connect to Unleash, or the keys the client SDKs use to connect to the proxy? If it's the former, then they're regular client tokens and can be created the same way as mentioned in the preceding paragraph. If they're proxy client keys, then they're just arbitrary strings, so it's entirely up to you how you create them.

However, with proxy client keys, there is a limitation: if you are a pro/enterprise user and Unleash hosts the proxy for you, then you won't be able to create them yourself. Could you clarify whether you host the proxy yourself or not?

>  need [...] to be able to centrally manage certain keys and ideally **permissions**.

What kind of permissions are you talking about here? For the keys or something else?

**Comment by deepbrook** [comment]
Hey Thomas!
Thanks for getting back to me!

> For client tokens, does the api/admin/api-tokens endpoint not provide you with what you need? You can see the OpenAPI spec for your specific instance by [enabling OpenAPI and the swagger UI](https://docs.getunleash.io/how-to/how-to-enable-openapi) for your instance.
>
>The docs also contain a copy of the most up-to-date OpenAPI documentation (including for [creating API tokens](https://docs.getunleash.io/reference/api/unleash/create-api-token)). (Yes, they're a little bare-bones at the moment, but we're working on fleshing them out as we speak!)

Huh - that entire endpoint eluded me. `api/admin/api-tokens` looks like exactly what I need. thanks!

>For "proxy client api tokens", do you mean the tokens the proxy uses to connect to Unleash, or the keys the client SDKs use to connect to the proxy? If it's the former, then they're regular client tokens and can be created the same way as mentioned in the preceding paragraph. If they're proxy client keys, then they're just arbitrary strings, so it's entirely up to you how you create them.

Indeed I meant the token for client SDKs. Is there any way to manage these via an API on the proxy? 
We're currently rolling them out on k8s using the respective ENV setting. A REST endpoint would be more elegant.

>What kind of permissions are you talking about here? For the keys or something else?

Essentially the scope of the keys - which is (i suspect) exactly what the `type` field sets for the client token? `client`, `admin`, `frontend` ?

**Comment by thomasheartman** [comment]
>  Huh - that entire endpoint eluded me. api/admin/api-tokens looks like exactly what I need. thanks!

Great! And yeah, sorry; it hasn't been very well documented previously. We're on it! But if you're ever in that situation again: everything you can do via the UI can be done vi the API (that is how the UI does it). Going forward, all endpoints will also be available in the OpenAPI docs. As mentioned, there's still a few issues there we're sorting out, but it's moving along.

> Indeed I meant the token for client SDKs. Is there any way to manage these via an API on the proxy?
> We're currently rolling them out on k8s using the respective ENV setting. A REST endpoint would be more elegant.

As far as I'm aware, no there isn't. I think that would require a fair bit more work (the proxy would need proper auth to prevent outside actors from setting keys etc), but it might be possible. If it's something you think would be a worthwhile addition, please don't hesitate to open a feature request to explain the need you have. I can't promise we'll get around to it, but it'll at least give us a data point. And if you're willing, you could also potentially contribute some code for it 💁🏼

> Essentially the scope of the keys - which is (i suspect) exactly what the type field sets for the client token? client, admin, frontend ? I'm not clear on project vs projects though - how do those work?

Yes, those three are scopes, indeed:
- admin tokens get access to everything
- client tokens only get access to the /api/client endpoints
- front-end tokens only get access to the /api/frontend

`project` vs `projects` is probably a holdover from a previous version. You should use `projects` instead. List all the projects you want to give access to in the `projects` array. If you want to give access to **all** (current and future) projects, use `"projects": ["*"]``.

Another thing that might be useful in cases like this is the API command panel that Unleash has for most of its forms: on the right-hand side of the form, there is a dynamically updating API command to perform exactly the same action as submitting the form would perform. You can check this command to see what command the Unleash UI would send.

In the case of creating API tokens, it uses the `projects` property consistently as shown in the following image:

![API token creation form with an equivalent cURL command on the right side](https://user-images.githubusercontent.com/17786332/196375840-e3ed80a8-d18a-4a8a-9071-9329b030b859.png)

**Comment by thomasheartman** [comment]
@deepbrook Following the PR in the terraform provider, it looks like this issue has been resolved for you, so I'll go ahead and close this issue for now. Feel free to reopen it if you think there's more to be done here. Thanks again for opening the issue! 😄
