### ISSUE TITLE
Allow Unleash server to run with Node > 6

### ISSUE THREAD

**Issue by jrbarron** [Unleash/unleash#219]
Currently, the version of Node is restricted  to 6 in the package.json file:

```json
  "engines": {
    "node": "6"
  },
```

This causes problems when running with Node > 6 especially when using yarn which is stricter when  evaluating the `engines` property.

**Comment by SimenB** [comment]
Changed this, but I'm leaving Ivar to do a release, unsure about all these changes

https://github.com/Unleash/unleash/compare/5e83dd4a42a658d1a54f2b87c791bd1155cf6da6...HEAD

**Comment by SimenB** [comment]
@jrbarron A new release is out, but for posterity; you can use `--ignore-engines` when running yarn to circumvent the issue

**Comment by ivarconr** [comment]
released as 2.1.6

**Comment by jrbarron** [comment]
@SimenB I found that out after I created this :) Unfortunately it's a bit tricky to change that in our Docker file.

@ivarconr Wow, that was quick! I just tested this, but the unleash-frontend is still pinned to "6" so it still won't install :( Should I create a separate issue for that?

**Comment by ivarconr** [comment]
ai, too quick obviously. Will fix that one too.

**Comment by ivarconr** [comment]
fix unleash-frontend too!

**Comment by SimenB** [comment]
@ivarconr did you release it?

**Comment by SimenB** [comment]
@ivarconr did you release it?

**Comment by ivarconr** [comment]
yes, released as 2.1.7.

**Comment by SimenB** [comment]
No, the frontend. https://github.com/Unleash/unleash-frontend/releases

**Comment by ivarconr** [comment]
I just forgot to push tags, fixed now.

**Comment by SimenB** [comment]
Gotcha, cool!
