### ISSUE TITLE
Importing a feature with a feature environment set displays the feature environment even with the environment disabled in project settings

### ISSUE THREAD

**Issue by knightsg** [Unleash/unleash#2193]
### Describe the bug

We have a deployment process that imports toggles into multiple Unleash server (free version) environments and we use either of the built-in 'development' or 'production' Unleash project environments across all of our app environments. As such, the featureEnvironment is included (though set to disabled) for both development and production environments when it's imported from the source JSON file.

We also disable the non-used environment for any particular Unleash server through that server's default project environment settings. However, when we import a feature toggle, even though (for example) the 'development' project is disabled in the project settings, the toggle page will still display 'development' as one of the toggle's available environments. To remove it from the toggle page I have to go into the project's environment settings and re-enable, then disable the environment again to stop it showing on the toggle page.

### Steps to reproduce the bug

1. Create a source configuration file with a feature toggle and a specific environment set (eg. 'development')
2. Import the source configuration into an Unleash server where the 'development' environment is disabled in the project's environment settings.
3. Check the feature toggle overview page and you should see that the 'development' environment is still showing in the 'feature toggle status' section.

### Expected behavior

Importing a feature toggle into that project with a 'development' feature environment configuration should not cause that environment to show in the toggle overview/settings if the same environment is disabled in the project's environment settings.

### Unleash version

4.15.4

### Subscription type

Open source

### Hosting type

Self-hosted

**Comment by thomasheartman** [comment]
Hey, @knightsg! 👋🏼  That does indeed sound like a bug 🐛 ; thanks for the report 😄 I'll bring it up with the rest of the team and we'll investigate further next week. Have a good weekend in the meantime ☺️

**Comment by sjaanus** [comment]
Hey, @knightsg, it should be resolved by https://github.com/Unleash/unleash/pull/2209 if you want to test it out.

**Comment by knightsg** [comment]
Thank you! I'll give it a test and let you know how it goes.

**Comment by knightsg** [comment]
Ok, I've checked and the good news is the core issue I originally identified is fixed. Here's my test steps:

1. Start up a clean server (no imported config).
2. Disable the development environment in the default project.
3. Stopped the server (eg. did not remove the existing container).
4. Start the server again with IMPORT_FILE and IMPORT_DROP_BEFORE_IMPORT vars set. The configuration file I sourced had a single feature toggle config with the feature environment 'development' enabled.
5. Checked toggle settings and confirmed that the development environment was not showing in the 'Feature toggle status' panel for the feature toggle.

One caveat however, is that I did a follow-up test where I simply started with a clean server and set the same import flags from the beginning, which imported my test toggle immediately. However, when I checked the toggle settings the development environment was showing but was *not* enabled even though it's marked as enabled in the source config file.

Despite the above issue I can confirm the core issue I originally opened this ticket for is resolved.  I can open another tocket for the secondary issue after I perform some further investigation.

**Comment by thomasheartman** [comment]
Hey, @knightsg! 🙋🏼 It seems that this issue has been solved, so I'll go ahead and close it for now. If you've performed the further investigation you mentioned, we'd love for you to open another ticket for that one too (I _do_ remember you having another ticket open; was that that one?) 😄 

Feel free to reopen if you feel there's more work to be done here! Thanks again for opening the issue 😄
