### ISSUE TITLE
Implement support for reusable lists

### ISSUE THREAD

**Issue by jrbarron** [Unleash/unleash#220]
It would be really nice if reusable lists could be created and thereby shared across different feature strategies. Consider a case where you have a set of internal users that you very often enable a feature for before rolling it out to a greater audience. At the moment, this has to be done by manually adding all the userIds (or IP addresses for that matter) to the relevant strategy in each feature.

There are two ways this could be implemented.

1) When you select a reusable list, it copies it's contents into the list field of the strategy (but further changes to the list would have no effect)

2) When you select a reusable list, it stores a reference to the list such that adding or removing people to the list later would enable/disable the feature for them.

On the one hand I like the convenience of 2), but on the other hand it reduces visibility of which users should get a feature or not. With 1), you would need to re-add the list if it has changed, but this avoids side effects. Discuss :)

**Comment by ivarconr** [comment]
Yes, this would be a great feature and we have already discussed this briefly here at FINN also. 

Personally I am in favor of alt 1, mostly to keep the model-complexity down. One can also argue that feature toggles should be shorted lived, and thus future changes would be irrelevant.

From a usage perspective alt 2 would of course feel like a more well thought implementation. There might be an issue though that modifying the list is changing existing usage, and can lead to accidental exposure of toggles by mistake. 

I also believe one can start with **alt 1** make that work, and later evolve the implementation in to also solving **alt 2**.

**Comment by ivarconr** [comment]
A simpler solution could be to add the possibility to clone/reuse toggle configurations? This can be done without adding anything new to the backend. 

What do you think @jrbarron ?

**Comment by Willyham** [comment]
My first thought was that option 2 was the only way to go. Now I'm wondering whether it would be better to move the state out of unleash and into your own store. For example, you could set an `isAdmin` property on your users, then use an activation strategy which checks for that property. Then you can control who gets a feature just by toggling the property in your own store.

However, given that Unleash does provide the concept of using lists as built-ins (with the userIds), it does seem like it should support maintaining the state of the list. With option 1, if we have 100 toggles and a new employee joins the company, updating the list for all toggles isn't really feasible.

**Comment by ivarconr** [comment]
> Now I'm wondering whether it would be better to move the state out of unleash and into your own store. For example, you could set an isAdmin property on your users, then use an activation strategy which checks for that property. Then you can control who gets a feature just by toggling the property in your own store.

This is exactly how we have implemented our `BetaUserStrategy`. It would be kind of strange if Unleash should hold a list of all employees or users of your site. 

> With option 1, if we have 100 toggles and a new employee joins the company, updating the list for all toggles isn't really feasible.

Yes, but what we see in our company (150+ toggles, 70 apps) is that we use the `RemoteAddressStrategy` in order to release something everyone in our company (we could use a `EmployeeStrategy` too). 

Teams tend to use the `userWithIdStrategy` to enable the feature for the people actually working on that feature. This is mostly  a very limited list of users, and will often vary from feature to feature. They will add more strategies when they are ready to test on real users (emplyees, external users via gradualRollout etc.) 

I would also stress that you should delete toggles after they have served their purpose. Features toggles are technical depth, and we should delete them as soon as possible. Having them laying around too long make it harder to remove them; people quit, developers forget what they do. Every toggle ads a new if/else path in the code.  

That said

**Comment by ivarconr** [comment]
(closed by mistake)

**Comment by floskel** [comment]
It has been a while with activity on this one. 
The solution I was looking for is more of an `alias` or `group` functionality. 
Being able to do something like: 
- Create `alias` named "Product Owners" 
- Set list of `userId` as the value of "Product Owners"
- In the UserId activation strategy i want to be able to select the alias
- The list of userIds for "Product Owners" is then added to the `List of userIds`

<img width="578" alt="Screenshot 2022-03-23 at 12 48 40" src="https://user-images.githubusercontent.com/1681866/159692641-412bc9fe-4c49-4df6-96fe-5b3572949072.png">
v

**Comment by thomasheartman** [comment]
Hey, @floskel! 👋🏼  I think you already got a response to this in the Slack channel, but I'll reiterate it here for broader visibility:

We are in fact working on something that would solve this exact issue at the moment! The "lists" in this case will actually be a collection of constraints that can be reused across features. It should land in one of the next few releases 🚀 

For reference, here's the [roadmap card describing this feature](https://github.com/orgs/Unleash/projects/5#card-77029815).

**Comment by thomasheartman** [comment]
Unleash 4.13 will contain a feature called [segments](https://docs.getunleash.io/reference/segments) (available to pro and enterprise users) which should solve this issue. I'll close this issue for now (with stalebot's recent recommendation in mind), but feel free to reopen it if you think there is further work to be done ☺️
