### ISSUE TITLE
Client should be allowed to include SDK version in register call

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash#221]
Today it is hard to know which SDK-version a client application is using. The Client SDK should add some metadata in the registration call which tells which SDK is used (unleash-client-node, unleash-client-java, unleash-client-go, etc) and which version.

**Comment by sveisvei** [comment]
indeed `language` and `client-version` should be part of the meta-data.

**Comment by ivarconr** [comment]
I was thinking this could go as part of the initial [client instance registration call](https://github.com/Unleash/unleash/blob/master/docs/api/metrics-api.md#client-registration)
