### ISSUE TITLE
Expose application hooks and enable/simplify authentication

### ISSUE THREAD

**Issue by andereld** [Unleash/unleash#222]
Hi

I'm working on a project where we would like to use Unleash, but we need authentication. While it's possible to place the Unleash server behind a proxy and use HTTP Basic Auth, it would be nice to use, say, Basic Auth for the API endpoints and OAuth for the web interface. 

It is possible to do this on the server-side using `config.preHook` in `lib/app.js` and something like [Passport](http://passportjs.org/). However, `config.preHook` is not exposed through the Unleash server's main module (`lib/server-impl.js`). Unless I am mistaken, that means that we will have to essentially duplicate `server-impl.js` in our wrapper app in order to actually use the hook. This seems unnecessarily complicated and brittle. I would much prefer to use Unleash in a ‘black box’ fashion, along the lines of:

```js
const unleash = require('unleash-server');

function myPreHook(app) {
    app.use(superSecureAuthentication());
    …
}

unleash.start({
    databaseUrl: 'postgres://unleash_user:passord@localhost:5432/unleash'
    port: 4242,
    preHook: myPreHook
}).then(unleash => {
    console.log(`Unleash started on http://localhost:${unleash.app.get('port')}`);
});
```

Of course, for this particular use case, the Unleash client would also need to pass an HTTP `Authorization` header with the appropriate credentials to the server with every request. This could conceivably be solved by including a list of custom HTTP headers in `UnleashConfig` and adding those to every request made by the client – based on a quick search of the repository, it seems this would only affect `HttpToggleFetcher` and `UnleashMetricsSender` (in the Java case).

```java
// In your client application:
UnleashConfig config = UnleashConfig.builder()
        .appName("java-test")
        .instanceId("instance x")
        .unleashAPI("http://unleash.herokuapp.com/api/")
        .customHttpHeader("Authorization",
                Base64.getEncoder().encodeToString("user:password".getBytes())); // :(
        .build();

Unleash unleash = new DefaultUnleash(config);
```

So:

1. Is there a particular reason you have chosen not to expose the server application hooks through the main module?
2. If not, are you open to the suggested changes (to the server and client, or if not, to just one of them)?
3. If you use authentication with Unleash at FINN, how have you solved it?

Relates to: #33

**Comment by sveisvei** [comment]
1) No, this was not intended as far as I can tell. Did do a quick-fix here now: https://github.com/Unleash/unleash/pull/223, will this fix 1 for you?
2) Yes, very open to changes to get this to work with your setup
3) We do not embed auth in the unleash-server, we secure the service with other means atm.

**Comment by ivarconr** [comment]
First of all, thanks for showing an interest in to the project! 

I agree with @sveisvei there is no good reason why hooks was not exposed and we should definitely get #223 solved.

It is already on the roadmap to standardize a bit more around authentication, but time as proven to be a bit sparse lately. 

As you mention, I believe there is a distinction between **client authentication** and **user authentication**. The latter should probably be based on Passport or similar. When it comes to client authentication my initial though was that this should be token based, where we generate a token per client-id which should be added as a `Authorization` header by the clients. This would allow us to easily add/revoke access for clients, without having to a separate user/password storage. We still need to figure out a smart way to store these access tokens though. 

I will absolutely love others suggestions on how this could be solved and will encourage suggestions and  PRs on how to solve this.

**Comment by andereld** [comment]
@sveisvei:

1. Yes, that should fix it. Do you plan to release a new version anytime soon, or should I just depend on the latest commit for now (in my wrapper app's `package.json`)?
2. Great!
3. I see, thanks.

@ivarconr:

While a token-based solution sounds nice, I don't really need it in my case. We run our services in an Amazon VPC. As these are trusted (internal) services running in a private network, we don't have the need to revoke access and such, so we normally use Basic Auth for communication between them. We already have a store for credentials, and tools for fetching them during deployment. I expect that different companies/projects will have different existing solutions or preferences, so I think it's a good idea for Unleash to be flexible.

In my particular case, I was thinking that I'd use Passport in my wrapper app with two different strategies for different routes – Basic Auth for routes beginning with `/api` and one of the available OAuth strategies for everything else. This would be quite simple to set up in the preHook, and should work well for my needs. All that I need from the client, then, is to be able to pass in an `Authorization` header to be added to the API calls.

I'm thinking a simple way of allowing this is to keep a list (or a `Map`) of custom HTTP headers within `UnleashConfig` and add those to the `HttpURLConnection`s in `HttpToggleFetcher#fetchToggles` and `UnleashMetricsSender#post`, perhaps creating a helper method which adds them along with the app name and instance ID (which are already stored in `UnleashConfig`) to keep things DRY. This is based on the Java client, obviously something similar should be done for the other clients.

As this doesn't actually add authentication or make assumptions about authentication within Unleash, but only makes it easy to add authentication oneself, it shouldn't get in the way if you decide to make authentication part of Unleash in the future. What do you think?

Thank you both for your help and prompt reply!

**Comment by ivarconr** [comment]
> As this doesn't actually add authentication or make assumptions about authentication within Unleash, but only makes it easy to add authentication oneself, it shouldn't get in the way if you decide to make authentication part of Unleash in the future. What do you think?

I think that extending the clients with the ability to add headers via the config makes sense and see that this can be useful for other scenarios as well, such as distributed tracing etc. 

If you are willing to purpose the necessary changes for the Java-client I will be more than happy to assist and can probably also make sure we implement these capabilities in the other official clients as well (node and go).

**Comment by andereld** [comment]
@ivarconr Great! I will write a patch and submit a pull request in the unleash-client-java repo.

**Comment by sveisvei** [comment]
@andereld + unleash-server@2.2.0 published

**Comment by andereld** [comment]
@sveisvei Nice, thanks! I'll close this issue then, as the server issue has been resolved and the client change will appear as a pull request in another repository.

**Comment by andereld** [comment]
Hello again

I've submitted a pull request for the change to the Java client. However, I've made some discoveries which warrant further discussion about the Unleash server, so I figured I'd reopen this issue and comment here for context.

While it seems rather obvious, I didn't know/consider that the web interface runs entirely in the browser, performing AJAX requests to the API for its various actions. Obviously, if the API endpoints require authentication and `unleash-frontend` doesn't provide any credentials, as is currently the case, the web interface stops working. I've considered three solutions to this problem:

1. If the authentication method for the API and the web interface were the same – or, more likely, if there were two authentication methods for the API endpoints, one acting as a ‘fallback’ when the other fails – the current client could work given that all of the `fetch()` calls feature `credentials: 'include'` so as to pass along the cookie or authorization header containing the token added by the authentication middleware. Currently some of the calls do, but not all. This seems like a relatively small change to the frontend, but given that we want separate client and user authentication, the server side of things would probably be a little complicated/hacky in my opinion.
2. An alternative frontend could be created. If I understand the code correctly, it should be simple to pass in a `publicFolder` other than the default value to prevent the current frontend from being served, and mounting an alternative frontend in the wrapper app.

    If I were to make one, it would probably be a little more ‘Web 1.0’ than the current frontend in that communication with the API would happen server-side, so as to make the issue of authentication easier – having code running on the server would allow the app to access sensitive information (credentials) and make configuration easier when compared to a static, precompiled bundle of HTML, CSS and JS which is sent to the browser. I think it would make sense to perform authentication in a callback, similar to the prehooks in the Unleash server, to keep it flexible/changeable. (A rewrite would also be an opportunity to assume user authentication and include the authenticated username in the logs rather than the user typing it into a text field as is currently done.)
3. We (my team) could just wait for you guys to fix it. ;) Joking aside, you mentioned that authentication is on the roadmap, but that time has been sparse lately – it would be interesting to know if you have thoughts/plans for when it may become a priority for the Unleash team.

I am thinking of going for the second option and creating an alternative frontend as I'm not quite comfortable with the first solution. However, I don't believe I'll be able to do that during my day job for prioritisation reasons. Given that it would be a ‘hobby’ project for me, I don't want to commit / make promises at this point.

Because requiring authentication for the API endpoints renders the web interface broken at the moment, and because we have deadlines and need to start actually using Unleash for A/B testing, my team have decided to only add authentication to the web interface at this time, and not to the API, instead using Amazon's network features to secure it sufficiently for our purposes. It would be nice if we were able to add API authentication in the future though. This means that we won't need my suggested change to the Java client at this point, which you may want to consider with regard to the pull request. I still think it could be useful in the future, though, and – as @ivarconr points out – it could have applications other than authentication as well.

As a bit of a side note, I noticed that the legacy routes are not prefixed with `/api`, making it cumbersome to secure the API by route matching. It would be nice if there was something like `config.enableLegacyAPI` passed to `app.js` so that they could be disabled – the default configuration could enable them, of course, for backward compatibility.

Apologies for the lengthy post. I'd be interested to hear any comments you may have.

**Comment by sveisvei** [comment]
Ahoy @andereld!

I vote for 1). Indeed there needs to be some work done on a cleaner split the api-routes/ui-routes, but this should be within reach in my opinion. We need to create some kind of user-provider functionality for the ui as well.

We plan on doing som work on Unleash next friday, given we have the planning done by then - it should be possible to get this working.

**Comment by ivarconr** [comment]
Legacy routes should go away in next major.

I also vote for 1). We might have a better understanding of the required work needed after our unleash effort next Friday.

You are of course free to build your own Admin UI, but this will not give you future updates and new features for free.

**Comment by ivarconr** [comment]
> If I understand the code correctly, it should be simple to pass in a publicFolder other than the default value to prevent the current frontend from being served, and mounting an alternative frontend in the wrapper app.

yes this should be possible.

**Comment by andereld** [comment]
Alright, thanks!

I agree that sticking with the official frontend would be the best solution for several reasons, I'm just not sure how to separate API and UI authentication in a clean way – although providing two authentication methods for accessing the API, one for the web interface and one for (other) client apps, may not be as messy as I originally thought.

I'd be very interested to hear what you conclude on Friday.

**Comment by ivarconr** [comment]
closing this as we have multiple task covering authentication and it is on the roadmap for Unleash 3.x. Do not hesitate to re-open if you don't find the suggested tasks sufficient.
