### ISSUE TITLE
🔥 feat: Changes request

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash#2251]
(enterprise feature)

“Change request” is a feature Unleash is currently building to enable Unleash users to create suggested feature toggle configuration changes in an environment. This feature enables changes to be inspected by other Unleash users, before they are applied. 

This feature is expected to allow Unleash Enterprise customers to enforce the “**The four eyes principle**”.

An early mockup:
![image](https://user-images.githubusercontent.com/158948/197850477-360f2096-5c33-4a3c-8297-0fd8eb861b58.png)

We are collaborating with a few of our strategic customers to shape this feature.

**Comment by joelroohzen** [comment]
Could this potentially become an OS feature? Even a paid "add on" rather than enterprise-only.

**Comment by ivarconr** [comment]
This feature is now in beta with selected customers.

**Comment by ivarconr** [comment]
> Could this potentially become an OS feature? Even a paid "add on" rather than enterprise-only.

We have not fully decided on this yet, for now we are building this feature together with some of our strategic customers to learn what this can be. I would not be surprised if parts of it will be open-sourced eventually (we have open-sourced most things eventually).

**Comment by ivarconr** [comment]
First iteration released as part of v4.19
