### ISSUE TITLE
🔥 feat: Dependent feature toggles

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash#2255]
Allow one toggle to depend on another toggle when evaluating if the toggle is enabled. 
![image (15)](https://user-images.githubusercontent.com/158948/197853394-f68acb6f-3713-4df1-92cb-8a24af78c2d4.png)

Should be possible to depend on multiple toggles:
![image (16)](https://user-images.githubusercontent.com/158948/197853426-4dab4338-aded-43ae-b42b-093f06ccb4b4.png)

We will not support multiple toggles in a chain
![image (17)](https://user-images.githubusercontent.com/158948/197853438-c0732886-64b4-4eaf-84a2-70fc28f84825.png)

We will not support circular dependencies
![image (18)](https://user-images.githubusercontent.com/158948/197853471-afce1305-6420-4f3e-814a-d62ae4a177b8.png)

**Note**
This will also require updates to ALL SDKs, so we should align on the protocol quite early.

**Comment by sullrich84** [comment]
+1 Was going to suggest that too! Currently we map our toggle dependencies in the code.

**Comment by ArekCzarnik** [comment]
+1
It would be nice to have these features!

**Comment by kwasniew** [comment]
This issue is actively worked on starting this week.

**Comment by kwasniew** [comment]
This feature is implemented: https://docs.getunleash.io/reference/dependent-features
