### ISSUE TITLE
Client / Admin auth

### ISSUE THREAD

**Issue by sveisvei** [Unleash/unleash#228]
Admin / UI
- [ ] Move all admin routes under `/api/admin` https://github.com/Unleash/unleash/pull/227
    - [ ] Update frontend https://github.com/Unleash/unleash-frontend/pull/80
- [ ] User provider
  - [ ] Require and pick up user from req.user
- [ ] UI should handle 401
    - [ ] redirect with window.confirm
- [ ]  create validate auth examples
    - [ ] OKTA
    - [ ] Google 
    - [ ] cookie (default)
        - [ ] fix cookie impl.

Client
- [ ] Move all client routes under `/api/client`  https://github.com/Unleash/unleash/pull/227
    - [ ] Create legacy routes
- [ ] Client auth / custom header examples

**Comment by ivarconr** [comment]
I have split this in to multiple subtasks.
