### ISSUE TITLE
[Groups] Change protocol to support grouping of strategies

### ISSUE THREAD

**Issue by sveisvei** [Unleash/unleash#229]
We want to be able to support more complex strategies compositions, and therefor should add AND support. This can be though of as creating a segment for limiting target. 

We discussed so far on a grouping mechanism:

```json
[
{ 
    "id": "group-id",
    "name": "__internal-operator-group-strategy",
    "type" :" AND",
    "commands": [
         { "name": "strategy-1", "parameters": {} },
         { "name": "strategy-2", "parameters": {} }
    ]
},
{ 
    "id": "group-id",
    "name": "__internal-operator-group-strategy",
    "type" :" AND",
    "commands": [
         { "name": "strategy-1", "parameters": {} }
    ]
}
]

```

Within each group the strategies forms a segment where each strategy reduces the target group for the toggle. A concrete example could be that we want one group for `dev` and another for `prod`.

TOOD:
* improve example
* write test-implementation in the clients to figure out the exact details of the new format. 
* spec up how metrics should count a groups
* find a way to handle groups in the UI

**Comment by ivarconr** [comment]
I have been playing a bit with the format.

## Suggestion 1 (new field):
We can add a new "strategies" field in the strategies section. Thus we can imagine a support for endless levels of groups in the future. This will require us to slightly change the client implementations to handle the new format. 

```
{
	"version": 2,
	"features": [
		{
			"name": "Feature.A",
			"description": "lorem ipsum",
			"enabled": true,
			"strategies": [{
                "name": "__internal-operator-group-strategy",
                "parameters": {
					"operator": "AND"
				},
				"strategies": [{
						"name": "ActiveForUserWithId",
						"parameters": {
							"userIdList": "123,221,998"
						}
					},
					{
						"name": "GradualRolloutRandom",
						"parameters": {
							"percentage": "10"
						}
					}
				]
			}]
		}
	]
}
```

## Suggestion 2: Don't break the format
Another approach is to stick with the current format and just inline the required data (grouped strategies) as json. This feels like a hack, but allows us to introduces grouped strategies without breaking exisitng client implementations. 

```
{
	"version": 2,
	"features": [
		{
			"name": "Feature.A",
			"description": "lorem ipsum",
			"enabled": true,
			"strategies": [{
                "name": "__internal-operator-group-strategy",
                "parameters": {
					"operator": "AND",
                    "strategies": "[{"name":"ActiveForUserWithId","parameters":{"userIdList":"123,221,998"}},{"name":"GradualRolloutRandom","parameters":{"percentage":"10"}}]"
				}
			}]
		}
	]
}
```

**Comment by ivarconr** [comment]
## Suggestion 3

Another way to introduce this is to think about it a bit more mathematically in the protocol. By adding an operator to the strategy-definition. This can still be displayed as strategy groups in the UI. 

1. A **OR** B **AND** C ==> A **OR** (B **AND** C)
2. A **AND** B **AND** C ==> ((A **AND** B) **AND** C))
3. A **OR** B **OR** C ==> A **OR** B **OR** C
4. A **AND** B **OR** C ==> (A **AND** B) **OR** C

A concrete example:

```json
{
	"version": 2,
	"features": [{
		"name": "Another",
		"description": "A small test toggle",
		"enabled": true,
		"strategies": [{
				"name": "gradualRolloutRandom",
				"operator": "AND",
				"parameters": {
					"percentage": "13"
				}
			},
			{
				"name": "geo",
                "operator": "OR",
				"parameters": {
					"countries": "norway, colombia"
				}
			}
		]
	}]
}
```

The implementation in the clients would be as simple as:
- If operator=="OR" and strategy yields true => return true
- If operator=="AND" and strategy yields true => check next strategy also yields true. Repeat until false or operator=="OR" or last strategy. 
- If last strategy: Ignore operator. 

The biggest drawback of doing it this way is that existing client implementations will ignore the operator and always assume "OR".

**Comment by ivarconr** [comment]
I played a bit with **alternative 1** in the node client:
https://github.com/Unleash/unleash-client-node/compare/groups?expand=1

What I learned that we need to adress:
- Do we want/need to support nested groups? (My implementation does that now)
- Should `type`, `operator` and `strategies` be new fields on the strategy configuration?^

**Comment by sveisvei** [comment]
I have done my take on this, work-in-progress (working as far as I can tell): https://github.com/Unleash/unleash-client-node/pull/71

**Comment by ivarconr** [comment]
#442 will take care of this.
