### ISSUE TITLE
Add tag filter to new project features endpoint

### ISSUE THREAD

**Issue by chriswk** [Unleash/unleash#2306]
### Describe the feature request

I would like to be able filter features by their tags. Something similar to what we already have for /api/admin/features (which is deprecated).

### Background

Previously with our now deprecated /api/admin/features endpoint, we could filter by tags using ?tag[]=TAGTYPE:TAGVALUE (curious detail, this was the first feature I added when I joined in January 2021).

### Solution suggestions

Stealing the logic from our previous /api/admin/features for extracting the tags parameter from query params seems like a good way to go. Our feature service/stores already supports filtering by tags as evidenced by the fact that we can still filter by tags through the deprecated endpoint.

**Comment by jlane-tkww** [comment]
I see that stale bot marked this as closed, is it possible to still request this feature remain open?

**Comment by chriswk** [comment]
Yes. I'll see what I can get done on this.

**Comment by jlane-tkww** [comment]
> Yes. I'll see what I can get done on this.

Thank you!
