### ISSUE TITLE
[Auth] Client API authentication

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash#231]
Document how to use pre-shared keys together with preHooks and custom client headers to perform client authentication.

**Comment by ivarconr** [comment]
Because we have separated `/api/admin` routes from `/api/client` routes this is easy to achieve client-token auth with the use of a preRouterHook together with custom header set in the client configs. 

This could be implemented by using unleash-service programatically with a small wrapper as in the example below. Here we register a express middleware to intercept all requests to `/api/client` and it will send a 401 Unauthorized if the token does not match the pre-shared key. 

```js
const unleash = require('unleash-server');

const sharedSecret = '123?z_SabcF1'

unleash.start({
  databaseUrl: 'postgres://unleash_user:passord@localhost:5432/unleash',
  port: 4242,
  preRouterHook: (app) => {
      app.use('/api/client', function (req, res, next) {
        if(req.headers.authorization !== sharedSecret) {
            res.send(401);
        } else {
            next()
        }
        
      });
  }
}).then(unleash => {
    console.log(`Unleash started on http://localhost:${unleash.app.get('port')}`);
});
```

In the client code you would need to instruct the client to send the pre-shared key as the Authorization  header. In the java client this can be done via the configuration:

```java 
UnleashConfig config = UnleashConfig.builder()
                .appName("my-app")
                .instanceId("my-instance-1")
                .unleashAPI(unleashAPI)
                .customHttpHeader("Authorization", "123?z_SabcF1")
                .build();
Unleash unleash = new DefaultUnleash(config);

```

**Comment by ivarconr** [comment]
@sveisvei anything I have forgotten about?

**Comment by sveisvei** [comment]
Maybe one of our heroku-deploys should be "with" security.

**Comment by andereld** [comment]
@ivarconr Looks good to me! I just tried something similar, using `unleash-server` v3.0.0-alpha.1 and `unleash-client-java` v2.1.3-SNAPSHOT with different authentication mechanisms for the client and admin interface, and things seem to work nicely.

Two things are not quite in place, though:

1. The Java client still polls `/api/features`, not `/api/client/features`, so the authentication in your example wouldn't be triggered with the current version of the client library.
2. Once #244 has been implemented, the ‘disable legacy routes’ flag should be added so that you can't bypass authentication by using the old routes.

**Comment by ivarconr** [comment]
Great we are on the right track, and thanks for pushing to get this on our agenda. 

1. Yes, we must release a v3.x alpha of the clients also, using correct paths. 
2. Yes indeed, will probably be done soon! 

Current work-around is to protect the `/api/features` path with the same strategy used for `/api/client`.

**Comment by andereld** [comment]
Sorry about the late reply – that sounds good, thanks! Do you have a guesstimate for when Unleash v3 will be released?

**Comment by ivarconr** [comment]
Because of holiday I hope we can have a lot of it shipped during August (We generally don't provide strict ETAs).

Alpha releases will be shipped regularly, with slightly higher risk of incompatible api changes.

**Comment by ivarconr** [comment]
https://github.com/Unleash/unleash/pull/283
