### ISSUE TITLE
Failed to migrate db error: password authentication failed for user "unleash_user"

### ISSUE THREAD

**Issue by kundarsowjanya** [Unleash/unleash#2333]
### Describe the bug

Hi I'm trying to run unleash using option 3 (node)  in my local but I'm getting error like this could you please help me on this.
![image](https://user-images.githubusercontent.com/21242317/199948019-f0bd9b9d-3af9-4d09-9c75-917e3f34d5b9.png)

**Comment by thomasheartman** [comment]
Hey, @kundarsowjanya 👋🏼  Seems like your the password you're using is incorrect. Did you copy the exact code that's listed under [step 3](https://docs.getunleash.io/deploy/getting_started#option-three---from-nodejs)? If so, could you try setting the `password` property to `"passord"` instead (without the `w`) and see if that solves it? 

Oh, and it looks like you are, but I just want to double check: do you have a Postgres instance running?

**Comment by kundarsowjanya** [comment]
Hi,
I just followed these 3 steps

npm init
npm install unleash-server --save

Create a file called server.js, paste the following into it and save.

const unleash = require('unleash-server');

unleash
  .start({
    db: {
      ssl: false,
      host: 'localhost',
      port: 5432,
      database: 'unleash',
      user: 'unleash_user',
      password: 'password',
    },
    server: {
      port: 4242,
    },
  })
  .then((unleash) => {
    console.log(
      `Unleash started on http://localhost:${unleash.app.get('port')}`,
    );
  });

Run server.js:

node server.js

Do I need to do anything else?I'm not running postgress

**Comment by ivarconr** [comment]
@kundarsowjanya yes, you need a postgres instance to connect to.

**Comment by thomasheartman** [comment]
Just to add some more context to what Ivar's saying above here. Yes, you need a running database for Unleash to work. You can start a postgres database via docker using the following command, for instance:

```bash
docker run -e POSTGRES_PASSWORD=password \
  -e POSTGRES_USER=unleash_user -e POSTGRES_DB=unleash postgres
```

I think that should work. You _might_ need to also map the ports, but I'm not sure.
