### ISSUE TITLE
getFeature by name should filter results by projectId

### ISSUE THREAD

**Issue by jlane-tkww** [Unleash/unleash#2337]
### Describe the bug

/api/admin/projects/:projectId/features/:featureName
https://docs.getunleash.io/reference/api/unleash/get-feature 

When using the above endpoint, I had assumed that results would be filtered by the projectId provided in the path, but I’m not seeing my results change regardless of which (valid) projectId I put in the endpoint. I know that feature names are a unique identifier across all projects, but I would expect that it should validate the project id as well as the feature name and yield a 404 in the case that the feature name does not exist within that project id. 

### Subscription type

Enterprise

### Hosting type

Hosted by Unleash

**Comment by thomasheartman** [comment]
Hey, @jlane-tkww 👋  I saw the thread in Slack; thanks for taking the time to open the issue here! I'll move it into our list of things to do ☺
