### ISSUE TITLE
View for content of archived toggles

### ISSUE THREAD

**Issue by theneva** [Unleash/unleash#249]
I would like to be able to see how an archived toggle was configured without restoring it to "normal" toggle status. The archived toggle list items aren't clickable right now, but it would be great if they pointed to a (read-only) view of the configuration the toggle had when it was archived.

**Comment by ivarconr** [comment]
This is a pure view task, as the API already includes all the data needed: [docs/api/admin/feature-toggles-api.md](https://github.com/Unleash/unleash/blob/master/docs/api/admin/feature-toggles-api.md#archive)

will be tracked in https://github.com/Unleash/unleash-frontend/issues/92
