### ISSUE TITLE
Missing unit for metrics interval

### ISSUE THREAD

**Issue by tfheen** [Unleash/unleash#250]
On https://github.com/Unleash/unleash/blob/master/docs/api/client/register-api.md, the interval does not have a defined unit. From the example, it looks like it might be msec, but I'm not sure.

(It should probably be in seconds rather than msec, but that's a different issue.)

**Comment by SimenB** [comment]
It is ms. And I agree it should be in seconds.

**Comment by ivarconr** [comment]
This should be documented, and yes it should probably be seconds. 

Currently it's just displayed in the UI, and we should probably be able to calculate it from the actual metrics.
