### ISSUE TITLE
Customisable labels for gradualRolloutRandom

### ISSUE THREAD

**Issue by tfheen** [Unleash/unleash#252]
We're using unleash in a slightly unusual setup where it is used for shifting traffic between two environments (using gradualRolloutRandom). It would be useful if we could use custom labels so people could drag the slider between "A" and "B", rather than having it be "amount of traffic going to A". Ideally this would feed all the way down to the underlying metrics as well so I could report "a: 5" and "b: 10" rather than yes and no.

**Comment by ivarconr** [comment]
Indeed. Adding labels in the UI should be trivial. 

I don't see how we can connecting it with the metrics in a general way with the current format. Do you?

**Comment by tfheen** [comment]
In terms of the underlying json structure, just accepting the labels in addition to "yes" and "no" would be enough for me. Not sure if that answers the question?
