### ISSUE TITLE
gradualRolloutRandom is hard to use on a touch device

### ISSUE THREAD

**Issue by tfheen** [Unleash/unleash#254]
It's really hard to make the percentage on gradualRolloutRandom change on a touch device such as an ipad. Could the touch target be made larger?

**Comment by vsandvold** [comment]
Great suggestion! I'll see if I can fix this.

**Comment by ivarconr** [comment]
Closing here as it will be adressed in https://github.com/Unleash/unleash-frontend/pull/89

**Comment by ivarconr** [comment]
tracked in https://github.com/Unleash/unleash-frontend/issues/91
