### ISSUE TITLE
fix: Technical debt

### ISSUE THREAD

**Issue by Tymek** [Unleash/unleash#2595]
### Things that we would like to improve in the codebase.

- [x] #2715
- [ ] React Table update (v8) @Tymek 
- [ ] ConditionallyRender @Tymek 
- [x] Integration testing @kwasniew (https://github.com/Unleash/unleash/pull/2422)
- [x] Enable eslint for frontend (again) (https://github.com/Unleash/unleash/pull/2562)
- [x] https://github.com/Unleash/unleash/issues/2306 @chriswk
- [x] #2606

### Anything else?

Please send me things to add or comment below. Anything that you would like to prioritize updating/fixing/enhancing. Non-breaking changes here, breaking changes for v5 in https://github.com/Unleash/unleash/issues/1265

**Comment by ShaswatPrabhat** [comment]
Can any of the above be picked up by a beginner to the repo @Tymek ? I can give one of these a shot if needed but I see PRs against a lot of the items already :)

**Comment by Tymek** [comment]
Most of it is medium to advanced. https://github.com/Unleash/unleash/issues/2606 is a good first issue. This doesn't need to be done in full to be helpful. Every refactored file helps.

**Comment by gastonfournier** [comment]
is ConditionallyRender finished @Tymek?

**Comment by Tymek** [comment]
@gastonfournier No. I have a script to do it, I need couple of hours to parse a codebase, fix edge cases.
