### ISSUE TITLE
Remove `useStyles`, refactor into `StyledComponents` and `sx`

### ISSUE THREAD

**Issue by Tymek** [Unleash/unleash#2606]
`useStyles`/`makeStyles()` is deprecated (See: https://mui.com/system/styles/basics/).

We need to migrate to [`styled`](https://mui.com/system/styled/), or where it makes sense use [`sx`](https://mui.com/system/getting-started/usage/#the-sx-prop) while keeping in mind [performance tradeoffs](https://mui.com/system/getting-started/usage/#performance-tradeoffs).

## Examples 

New syntax: https://github.com/Unleash/unleash/blob/228ddabf73411ce8837824de1e15fe58659896a8/frontend/src/component/addons/AddonForm/AddonForm.styles.tsx

Old syntax: https://github.com/Unleash/unleash/blob/228ddabf73411ce8837824de1e15fe58659896a8/frontend/src/component/admin/apiToken/ApiTokenForm/ApiTokenForm.styles.ts

**Comment by asharonbaltazar** [comment]
Hey, @Tymek, can I take a shot at this? Seems like a good first issue to orient myself with the codebase.

**Comment by Tymek** [comment]
This can be worked on by multiple people. Pick couple of files, let us know in the comment, and go for it! :) Once small initial contribution is reviewed you can choose to do another batch, that's how I see it.

**Comment by ShaswatPrabhat** [comment]
Picking up: `frontend/src/component/admin/users/UserForm/UserForm.styles.ts`

Will share PR shortly
