### ISSUE TITLE
[Auth] Session support

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash#262]
Unleash needs to have a session awareness to handle signed in users across multiple instances (to avoid redirects to OAuth provider). There exists multiple options:

- Use an encyted cookie for session data
- Use postgress as session store (see [connect-pg-simple](https://www.npmjs.com/package/connect-pg-simple))

**Comment by ivarconr** [comment]
After playing a bit with this I feel it is sufficient to just use an encrypted cookie for session store. The data needs are rather limited and the cookie would be about 190 bytes with a small user object on it.

**Comment by kamranayub** [comment]
@ivarconr I am trying to implement a custom `preHook` and was wondering how I "plug in" to the unleash session cookie?

Basically, we have our own OAuth2 provider and I'm as far as generating the access token/getting user info in the auth callback.

I am setting my own custom cookie, then in the `/api/admin` middleware, reading the ID token from the cookie and setting `req.user` with the Unleash `User` object from the data in the token/cookie.

Is there a cleaner way to tell Unleash "use this user in your session"?

**Comment by ivarconr** [comment]
Thanks for asking, this is not super clear in the documentation. 

What you need to do is to make sure to set the user-object you need on the session. The session will be stored encrypted in the cookie for you by Unleash. Frameworks like passport does this automatically for you. 

```
...
const user = new User({ ... });
req.session.user = user;
req.user = user;
...
``` 

You should also remember to inject a custom secret to Unleash (see [getting started](https://github.com/Unleash/unleash/blob/master/docs/getting-started.md#2-or-programmatically))

**Comment by kamranayub** [comment]
Thanks! I managed to get it working using that suggestion! I hadn't seen
that pattern before but when I read about cookie-session it started to make
sense.

Thanks for all your work on this, I stood up a working unleash server in 20
mins and started using it locally. Now I'm just "productionizing" it 😎

I may contribute an example using openid-client which is what I'm using.
