### ISSUE TITLE
Unable to use multiple versions of the same strategy with lists

### ISSUE THREAD

**Issue by jfse** [Unleash/unleash#266]
![screenshot 2017-09-13 10 23 37](https://user-images.githubusercontent.com/3922958/30367200-e125a262-986d-11e7-9388-6d1c32bb503f.png)

When adding multiple versions of the same strategy you can only add list items to the first instance. In the screenshot above, adding the "test2" to right hand strategy will not work.

This issue is in effect both on the heroku demo app and on the docker version (I also ran the docker version with 3.0a1)

**Comment by ivarconr** [comment]
Thanks for reporting, this looks like a UI bug. 

I will look in to it asap!

**Comment by ivarconr** [comment]
fixed on master now: 
http://unleash.herokuapp.com/#/features/edit/cool-feature

**Comment by ivarconr** [comment]
And released as "unleash-server:3.0.0-alpha.3"
