### ISSUE TITLE
Validate feature and strategy names in a less homegrown way

### ISSUE THREAD

**Issue by theneva** [Unleash/unleash#271]
I spoke with @SimenB offline, and we agree that even though #269 introduced some tests for valid names, we don't really know if we _disallow_ unwanted names.

From what I understand, the main goal of the validation is to only allow URL friendly characters.

Perhaps we could replace [the custom regex](https://github.com/Unleash/unleash/blob/de496c337a9298f695883068c29ae8169b3397be/lib/routes/admin-api/feature.js#L18) for validating feature and strategy names with a test as simple as:

```js
encodeURIComponent(input) === input
```

This will disallow all names containing non-URL-friendly characters.

The key advantage to this is that the URL spec is both well-defined and relatively well-known, so there's no need to actually maintain or document it further.

This approach would allow everything allowed by the current regex, and additionally `!`, `~`, `*`, `'`, `(`, and `)`, as per [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent).

Is there any reason to prefer a custom regex over just checking for non-URL-friendly characters?

**Comment by SimenB** [comment]
`encodeURIComponent` is not available in Node (but we cab probably use the `url` module), other than that I (still :D) thinks this makes sense

**Comment by ivarconr** [comment]
> encodeURIComponent is not available in Node (but we cab probably use the url module), other than that I (still :D) thinks this makes sense

are you sure @SimenB ?

```shell
$ node -e "console.log(encodeURIComponent('123.123-asd'))"
$ 123.123-asd
```

**Comment by ivarconr** [comment]
> Is there any reason to prefer a custom regex over just checking for non-URL-friendly characters?

That's the intention. I also see that this currently is duplicated in the view in various places.
