### ISSUE TITLE
Docs on how to upgrade

### ISSUE THREAD

**Issue by leftieFriele** [Unleash/unleash#276]
Being a user which isn't a contributor to the project I would really appreciate some docs on what to expect when upgrading. I assume it works without issues, but it would be cool with just a note on "upgrading" in relation to the upcoming v3 release.

**Comment by ivarconr** [comment]
Agreed, and the plan was to work that out as part of the v3 release. 

The `unleash-server` should always support clients one lower major version. So the v3 server needs to provide a format for consumable for v2 clients. This will make it easy for users of unleash to migrate gradually.
