### ISSUE TITLE
"AND"ing strategy paramters

### ISSUE THREAD

**Issue by yukw777** [Unleash/unleash#282]
I noticed that when you set custom parameters for a strategy, they're all "OR"ed. Is there a way to "AND" them? If not, is it something we want, or did you make a conscious decision not to implement "AND"?

**Comment by sveisvei** [comment]
Hi!

We definitely want AND support.
We have looked into how we want AND to operate, have not landed on anything yet. (I did do some code for the node client a year ago https://github.com/Unleash/unleash-client-node/commits/and-impl)

**Comment by ivarconr** [comment]
Yes indeed, we actually have another issue for this, as we have moved in to talking about this as groups of strategies, see #229. 

We plan to focus on this after we have manage to released v3.0.0.

**Comment by yukw777** [comment]
Thanks for your answers everyone. I was going through the docs again and I stumbled upon custom activation strategies from the node client. Looking at the code, seems like this may work for "AND"ing parameters? Let me know if I'm understanding it correctly.

```
const { Strategy, initialize } = require('unleash-client');
class ActiveForUserWithEmailAndInUSAStrategy extends Strategy {
    constructor() {
        super('ActiveForUserWithEmail');
    }

    isEnabled(parameters, context) {
        return parameters.emails.indexOf(context.email) !== -1 && parameters.country === 'USA';
    }
}
```

Does this work? If so, is this supported by the go client also?

**Comment by ivarconr** [comment]
Yes you will be able to define a custom strategy that does the ANDing for you. Custom strategies is supported by all official client SDKs.

**Comment by ivarconr** [comment]
I misread the question first; ANDing strategy params is possible and up to the strategy implementation. 

ANDing strategies are part of the group strategy feature, described in #229
