### ISSUE TITLE
fix: Metrics Table Timestamps Missing Time

### ISSUE THREAD

**Issue by sebastian-bury** [Unleash/unleash#2873]
On the metrics page, the table showing events and when they were requested and exposed only shows the date. This is confusing since the same date shows up many times in the table. This should include the time along with the date. 

![image](https://user-images.githubusercontent.com/101799760/211748240-7656cac7-01eb-43c8-8dc6-678b37099177.png)

**Comment by urveshgodhani** [comment]
can you assign to me i want to work on this issue
