### ISSUE TITLE
Creation of feature that name-clashes with an archived one silently fails

### ISSUE THREAD

**Issue by matiasanaya** [Unleash/unleash#290]
To reproduce:
1) Create a feature named 'feature'.
2) Archive it.
3) Create another feature named 'feature'.

Expected:
Step 3 should fail.

Actual:
Step 3 seems successful and a feature view is displayed. In reality all that has happened is an edit on attributes for the archived feature.

**Comment by SimenB** [comment]
I believe that this duplicates #284, do you agree? What version of Unleash are you on?

**Comment by ivarconr** [comment]
Hi, thanks for reporting the issue!

There was an attempt to address this issue in `3.0.0-alpha.7`. Can you verify on the latest version of Unleash (http://unleash.herokuapp.com)

Which version of unleash is you running on?

**Comment by ivarconr** [comment]
I see now that the UI will display an error-message: 

**Recreate archived toggle**
![image](https://user-images.githubusercontent.com/158948/35139430-59607bbe-fcf3-11e7-99a0-b39a9bc281bc.png)

**Submit form with validation error**
The "create button" will still be clickable, even if validation errors exists. This results in a stupid error:
![image](https://user-images.githubusercontent.com/158948/35139462-7f5ec0f0-fcf3-11e7-9329-633281ab10b5.png)

We need to address a fix for this.

**Comment by matiasanaya** [comment]
@ivarconr thanks for the quick fix :)
