### ISSUE TITLE
Creation of a feature that name-clashes with an existing feature displays incorrect error

### ISSUE THREAD

**Issue by matiasanaya** [Unleash/unleash#291]
To reproduce:
1) Create a feature named 'feature'.
2) Create another feature named 'feature'

Expected:
At Step 2 a message that does not mention archived toggles appears.

Actual:
At Step 2 a message that does mention archived toggles appears. Specifically: "A feature with this name already exists. Try re-activating it from the archive"

**Comment by ivarconr** [comment]
Agree, the error message could be more precise. Currently the error message will not differ between active and archived toggles, which might be confusing. 

I will address a fix for this!

**Comment by ivarconr** [comment]
Fixed via #292

**Comment by matiasanaya** [comment]
@ivarconr thanks for the quick fix :)
