### ISSUE TITLE
OpenAPI Spec - defined example request body object

### ISSUE THREAD

**Issue by sebastian-bury** [Unleash/unleash#2975]
### Describe the feature request

Currently there is no defined example request bodies.

**Comment by sebastian-bury** [comment]
This is needed for all endpoints.

**Comment by gastonfournier** [comment]
Almost all if not all of our schemas now have examples: https://docs.getunleash.io/reference/api/unleash/add-feature-strategy 
Closing for now, but let's re-open if we have a specific endpoint where examples are missing
