### ISSUE TITLE
CloudQuery Source Plugin

### ISSUE THREAD

**Issue by yevgenypats** [Unleash/unleash#2996]
### Describe the feature request

I want to sync unleash data to a datalake/database

### Background

Hi Team, hopefully this is right place to ask, if not, I'd appreciate if you can direct me.

I'm the founder of [cloudquery.io](https://www.cloudquery.io/), a high performance open source ELT framework. 

Our users are interested in an Unleash plugin, but as we cannot maintain all the plugins ourselves, I was curious if this would be an interesting collaboration, where we would help implement an initial [source plugin](https://www.cloudquery.io/docs/plugins/sources/overview), and you will help maintain it.

This will give your users the ability to sync Unleash APIs to any of their datalakes/data-warehouses/databases easily using any of the growing list of CQ [destination plugins](https://www.cloudquery.io/docs/plugins/destinations/overview).

Best,
Yevgeny

**Comment by sighphyre** [comment]
Hey @yevgenypats, this sounds like a really interesting idea. I'll bring this to the team to chat about and get back to you

**Comment by sighphyre** [comment]
Hey @yevgenypats we've chatted about this internally, this probably isn't something that we have capacity for at the moment. At least until we have pressure from our own users for this integration. We'd be happy to help guide development of a plugin but at this time we wouldn't be able to commit to maintenance

**Comment by yevgenypats** [comment]
Hey @sighphyre  Sounds good! Really appreciate you getting back to me and let's wait for customer feedback if this ever comes up I'd love to help as well.

**Comment by sighphyre** [comment]
@yevgenypats Wonderful! I'm going to mark this as maybe later, if anything changes we'll update this ticket
