### ISSUE TITLE
Ability to provide payload configuration along with feature true/false

### ISSUE THREAD

**Issue by tombburnell** [Unleash/unleash#301]
Is there any current or planned mechanism to provide configuration along with the feature. 
So if you had a feature called :
showNewMenu it might also have some associated json with it such as { "colour": "blue", "animated":  true } etc. 

The people that manage our feature toggles in our business also need to be able to change the behaviour/style of the feature to try things out before they decide on the final version.

We noticed that Launchdarkly provide this.

**Comment by ivarconr** [comment]
Yes, I have dedicated v4 to support experiments and variants of feature toggles. I believe custom configuration could be valuable in that context. See #297 for some discussion on this topic.

**Comment by ivarconr** [comment]
You an send payload to the client via variants, see #379
