### ISSUE TITLE
Ability to mark the current state of the feature set, generate a diff that can be applied elsewhere and rollback

### ISSUE THREAD

**Issue by tombburnell** [Unleash/unleash#302]
Our workflow often involves making a number of config/feature changes to an integration cluster, testing them and them making those same changes to our production cluster. It would be very useful to be able to mark the current state (like a tag in git), create a diff of feature changes and then apply those to a separate production instance of unleash. If there are any issues, we can then rollback that set of changes.

**Comment by ivarconr** [comment]
Interesting suggestion. This needs a bit more research on possible approaches. 

Internally unleash already uses "events" for all mutating operations on toggles and strategies, all events are published via an internal event-emitter. It would be possible to capture those events, and provide an execute a list of events. 

How to do the rollback is not that straight forward. 

As a side note:
One of the reasons we want to introduce the support of strategy groups and the support of "AND-ing" strategies, see #229 , is that we plan to just use one instance of Unleash, serving both our environments. Then you could have one group for `integration` and another for `production`, just by ANDing with a EnvironmentStrategy.

**Comment by ivarconr** [comment]
will be adressed in #395
