### ISSUE TITLE
Expose a list of all toggles with 100% yes last changed > 30d

### ISSUE THREAD

**Issue by SimenB** [Unleash/unleash#306]
Sorta bad titlte, but I'd love to get a list of all toggles that are responding with 100% yes and are unchanged for the last 30 days. In that case, you can probably delete the toggle as it's not necesarry any more.

In the same vein, also exposing all toggles that has no metrics for the last 30 days would be great for the same use case.

Opening here instead of in unleash-frontend as I want to query this myself and set up alerts within FINN for it, and not just necessarily view it as a list in the frontend.

**Comment by ivarconr** [comment]
Sounds good. The only thing to notice is that unleash currently does not hold metrics that long, it aggregates and deletes after a few days. This can be adjusted of course , but was implemented like this because the current use cases (real time and last hour) did not require anything more.

**Comment by SimenB** [comment]
Could store it separately.

`last_metric: timestamp`
`last_yes: timestamp`
`last_no: timestamp`

(ignore my lousy notation)

**Comment by ivarconr** [comment]
Indeed!
