### ISSUE TITLE
Feature description UI

### ISSUE THREAD

**Issue by Tymek** [Unleash/unleash#3096]
### Describe the bug

Feature description being awkwardly cut

### Screenshots

<img width="333" alt="Captura de pantalla 2023-02-13 a las 11 55 45" src="https://user-images.githubusercontent.com/2625371/218479157-3bff7fa5-6fd4-45e6-a9cd-31c4a599cd7a.png">

### Subscription type

None

### Hosting type

None

**Comment by CoffeeGeek101** [comment]
Hey, @Tymek. I would love to work on this issue.

**Comment by Tymek** [comment]
Awesome. Go ahead :)

**Comment by CoffeeGeek101** [comment]
@Tymek hope you having a good day. I'm pretty new to docker, so it's kind of taking time for me to open a PR. I'm just letting you know that I'm working on it.

**Comment by Tymek** [comment]
Very good point. Docker shouldn't be required for small frontend changes. `Node` and `yarn` should be enough.

Try pulling current version and running a command

`cd frontend && yarn && yarn start:demo`

(from https://github.com/Unleash/unleash/pull/3143)

Contribution guide needs an update 😄  @thomasheartman I can do it next week.

**Comment by CoffeeGeek101** [comment]
@Tymek I'm done setting up unleash locally, but how can I bypass the email. In Doc's only username is given.
<img width="1440" alt="Screenshot 2023-02-17 at 8 02 44 PM" src="https://user-images.githubusercontent.com/110016849/219683955-a167a9bd-1cf2-4786-97a4-5aa73fd3d836.png">

**Comment by Tymek** [comment]
locally, yes, there is a default username and password. When using Demo backend, you can sign up with the same email as for demo (https://www.getunleash.io/interactive-demo), or create new account.

**Comment by CoffeeGeek101** [comment]
@Tymek hey I have created an account with the interactive-demo version, but I couldn't able to get into the dashboard locally.

It's giving me 401 unauthorized error
<img width="1431" alt="Screenshot 2023-02-18 at 7 59 12 AM" src="https://user-images.githubusercontent.com/110016849/219827154-e15806e5-d449-4f5e-a195-2ae5654d87a2.png">

note -  I have also created the account with the live interactive-demo, but still not working while trying to get into it locally.
<img width="1440" alt="Screenshot 2023-02-18 at 8 03 30 AM" src="https://user-images.githubusercontent.com/110016849/219827269-a9efa5b0-451f-4545-b429-3278a97df919.png">

**Comment by Tymek** [comment]
Sorry for the delay. I couldn't reproduce the issue 😞. Some `401`s are OK before login.

**Comment by CoffeeGeek101** [comment]
In Live demo, the auth endpoint keep on failing the request. I can't access the dashboard locally.
<img width="350" alt="Screenshot 2023-02-24 at 11 05 50 PM" src="https://user-images.githubusercontent.com/110016849/221249084-6eba8c5f-c8cd-4cda-bbf0-75b3e246dd3d.png">

**Comment by SolomonJude** [comment]
How can I participate in resolving this issue? or has it been worked on?

**Comment by deepakchethan** [comment]
Hi @SolomonJude, Are you still working on this? Or can I take this up?

**Comment by SolomonJude** [comment]
Would you love to connect on WhatsApp?
