### ISSUE TITLE
Gradual rollout for user id and session id have intersectionality that may be undesirable

### ISSUE THREAD

**Issue by jribe** [Unleash/unleash#313]
When doing a gradual rollout of multiple feature toggles, I care about monitoring each toggle in isolation and in intersection. As such, I would naively expect that rolling out `FeatureA` to 10% of users and `FeatureB` to 10% of users would result in 1% of users having both `FeatureA` and `FeatureB`.

As implemented in the client libraries, that configuration would cause 10% of all users to have both features enabled. That means that I wouldn't be testing either feature in isolation! In fact, when using gradual rollout, I can only ever test the feature with the largest percent in isolation since it will be enabled for each request that has a feature with a smaller percent enabled.

You could achieve the behavior that I naively expect by adding the toggle name to the hashed text so that each toggle would hit a different set of users.

I understand that I could easily implement this as a custom strategy, but it seems reasonable for that to be the default behavior of `GradualRolloutUserId` and `GradualRolloutSessionId`. What are your thoughts?

**Comment by ivarconr** [comment]
Hi @jribe,

If you define the `goupId` strategy option (available in both gradualRolloutSessionId and gradualRolloutUserId) differently for `FeatureA` and `FeatureB`, this will end up beeing part of the hashed value, and thus give a different distribution of users, and should in theory give about 1 percent overlap of users in A and B. 

Currently the default value of `groupId` is today the empty string "", but it might be better to default it to the toggle-name as you suggest. I am all for changing this, but it might be something that is implemented in the UI (unleash-frontend) as the default value, that the user might change when they want to correlate users across toggles.
