### ISSUE TITLE
Unleash for Jira not compatible with Jira 9.4.3

### ISSUE THREAD

**Issue by bipin-brahmanandan** [Unleash/unleash#3173]
Hi Team,

Please release the unleash-jira-server-plugin compatible with Jira 9.4.3 in the marketplace. It would be great if we could get an ETA by when this would be available.

**Comment by sighphyre** [comment]
@bipin-brahmanandan Thanks for raising this one! A quick check suggests there's quite a few breaking changes in the new Jira version, we'll do an evaluation next week first thing and come back when we have a timeline

**Comment by bipin-brahmanandan** [comment]
Internal

Thank you. Looking forward for your feedback.

From: Simon Hornby ***@***.***>
Sent: 22 February 2023 12:43
To: Unleash/unleash ***@***.***>
Cc: Brahmanandan, Bipin (Allianz Technology) ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [Unleash/unleash] Unleash for Jira not compatible with Jira 9.4.3 (Issue #3173)


@bipin-brahmanandan<https://github.com/bipin-brahmanandan> Thanks for raising this one! A quick check suggests there's quite a few breaking changes in the new Jira version, we'll do an evaluation next week first thing and come back when we have a timeline

**Comment by sighphyre** [comment]
Hi @bipin-brahmanandan, we've release version 1.3.0 of the Jira plugin which is compatible with Jira 9.4 and above, you can download this from the Atlassian Marketplace, please just give us a shout if you have any troubles here
