### ISSUE TITLE
Bind to Addresses

### ISSUE THREAD

**Issue by cst152** [Unleash/unleash#318]
Hi,

I'd like to be able to bind the Unleash server to a specific address. In my setup, I have Unleash running behind an NGINX server would like to avoid having the server directly accessible from the outside on port 4242. I'd appreciate having a command line option (e.g. `-l 127.0.0.1`) and an environment variable to specify the address.

Thanks for your work!

**Comment by ivarconr** [comment]
This should be straight forward to add. I will look in to it as soon as I have some extra time available!

**Comment by cst152** [comment]
Awesome! Thank you so much.
