### ISSUE TITLE
Increase possible layout max wide to improve UX for complex project views

### ISSUE THREAD

**Issue by gabel** [Unleash/unleash#3373]
### Describe the feature request

The layout current is limited to a fixed width of 1250px which limits the usability in complex views. It would be great to allow for larger resolutions a wider layout to improve visibility any layout UX for complex views like the project overview.

### Background

The project view that allows to instant toggle features and to see all environments at once does hide longer toggle names with ellipse which makes it hardly useable if the significant part of a toggle name is hidden behind ellipse.

![image](https://user-images.githubusercontent.com/242039/227151385-f883a35c-b45c-4db6-98c1-352c0b55f4bf.png)

### Solution suggestions

Allow scaling of the layout to higher width.

![image](https://user-images.githubusercontent.com/242039/227152015-9c9717d9-406f-4961-ad7e-555cae9ee09f.png)

**Comment by daveleek** [comment]
Thank you @gabel for the suggestion! I have raised this with the team responsible for UX/UI, but I can't promise it will get looked at right away
