### ISSUE TITLE
How to do scheduled feature toggle?

### ISSUE THREAD

**Issue by geekyme** [Unleash/unleash#338]
Are we able to do something like: at 10pm on 31st Jul, turn on this feature toggle?

Use case: maintenance window

**Comment by ivarconr** [comment]
Hi, this is exactly what you can use custom activation strategies for. You will have to defining your strategy via the Unleash UI and set the config parameters it takes, e.g. ‘activeFrom‘ and ‘activeTo‘.

You will also have to provide the implementation for the strategy to the client SDK you are using. E.g. the java SDK will require you to provide an implementation of the Strategy interface and pass all custom strategy implementations as part of the constructor.

**Comment by geekyme** [comment]
Where's the documentation for custom strategy? I only see https://github.com/Unleash/unleash/blob/master/docs/activation-strategies.md

**Comment by ivarconr** [comment]
Good question. This needs better documentation for sure, will try to add some when I return from summer vacation in beginning of August.

The easiest way forward would probably be to look at the implementation for an built-in activation strategy in the client SDK you are using.
