### ISSUE TITLE
PHP Client

### ISSUE THREAD

**Issue by brpaz** [Unleash/unleash#339]
Hello.
It would be nice to have also a PHP client for unleash. You already have clients for go, ruby, node, java and  .NET. Only PHP and maybe Python missing from the most used langs.

Thank you.

**Comment by ivarconr** [comment]
It would be awesome if someone have the capacity to work on this.

**Comment by MyDigitalLife** [comment]
If a repository would could be setup people could start contributing to getting this started.

**Comment by ivarconr** [comment]
Aight :+1:  I have created a repo for it now :fire: 

https://github.com/Unleash/unleash-client-php

**Comment by ivarconr** [comment]
further discussion should now be in https://github.com/Unleash/unleash-client-php
