### ISSUE TITLE
Running the server as a serverless function?

### ISSUE THREAD

**Issue by leftieFriele** [Unleash/unleash#344]
I was wondering if the maintainers has thought about wether there anything preventing the server to be run as a serverless function on a cloude provider?

The heavy lifting is done by the clients anyway, so cold starts and things shouldn't be a big deal. Are there things I am missing which would make it a disaster to run this in a function?

**Comment by ivarconr** [comment]
My knowledge of serverless is limited, but I think it should be totally fine to rune the unleash-server as a serverless function. The state is stored in a postgres instance, so you would of course have to provide that as a resource. 

The only thing that might be a problem is that unleash-server calculates the metrics projections (per hour and per min) and store these pre-calculated in memory. We have seen for large users of Unleash (~100 clients and ~200 feature toggles) that it could take a few seconds to calculate these projections on startup of a new instance. 

As this question trigger my curiosity I have put on my agenda to verify this use-case. I will probably have time some time to do that next week.

**Comment by hennings** [comment]
AWS Lambda has a default timeout of 5 min per invocation. 

If a few seconds is too much for a client hitting a cold start, some people argue for a scheduled invocation every 20 minutes to minimise the odds if hitting a cold instance.

**Comment by leftieFriele** [comment]
I see what you mean. However the way the clients I've used is set to work is that whenever something occurs (network issues or Unleash server downtime) the client returns the default. The host app must  handle the default being returned and you should not never use toggles which never can fall back to the default. The cold start for functions would just be like any other network related issue.

Of course it could mean that on a site with little traffic it could occur frequently, but on sites with reasonable traffic it shouldn't be a big problem?

**Comment by ivarconr** [comment]
> Of course it could mean that on a site with little traffic it could occur frequently, but on sites with reasonable traffic it shouldn't be a big problem?

The in-mem metrics-projects will only be a problem for the Admin UI and will not affect the unleash clients.

I have done some playing around with Azure functions and also been looking at the API for AWS Lambda. The way they work is that you should basically implement a function which will provide a a request and a context object (which can help out with logging etc).

**Example on a serverless function with Azure**:
```js
function (context, req) {
    context.res = {
       body: 'hello world'
    };
    context.done();
}
```

This does not fit Unleash very well which is built on express.js. Fortunately it exist libraries to enable integration with express.js; [azure-function-express](https://www.npmjs.com/package/azure-function-express). It exists similar libraries for AWS.  

This would work, expect form the fact that unleash has a init-phase where it migrate the db if necessary. As far as I can understand, serverless functions should be stateless and thus should not require any startup phase. 

Also `unleash-server` also servers the Admin UI, which basically is a browser-rendered SPA. 

If one should run `unleash-server` as a serverless function I think it would be a better fit if it was split the application in three parts: 
1. The DB migration (could be one time functions of some sort)
2. The Admin UI (serving static files)
3. The API

I do not however this is the right choice for unleash and would in most cases make it harder to set it up. 

However; If your need is to better serve the client of unleash, in the case of `unleash-server` being down I believe there is a better way to use serverless functions: Use it to implement a small proxy for the client API, which has a small cache for the the toggles in case `unleash-server` disappears. The cache could be implemented with redis or similar. You can use a time based function to keep the cache in sync.
