### ISSUE TITLE
"Edit application" page fails validation

### ISSUE THREAD

**Issue by dylannz** [Unleash/unleash#3580]
### Describe the bug

When trying to edit any of the 3 available attributes on the "Edit application" page (icon, application URL, description) within the web panel, I get the following error:

<img width="455" alt="Screen Shot 2023-04-21 at 11 30 02 AM" src="https://user-images.githubusercontent.com/6373352/233507490-c573d08f-2d12-4d89-95d0-b184675dbd20.png">

Digging a bit deeper, I can see that the server is returning an HTTP 400 status with the following error in the response body:

```
{"error":"Request validation failed","validation":[{"keyword":"required","dataPath":".body","schemaPath":"#/components/schemas/applicationSchema/required","params":{"missingProperty":"appName"},"message":"should have required property 'appName'"}]}
```

But as you can see on the form, appName is not a field that is visible on the page:

<img width="946" alt="Screen Shot 2023-04-21 at 11 31 08 AM" src="https://user-images.githubusercontent.com/6373352/233507602-3ab5397f-d35d-4327-81b1-2cfc0fb2c180.png">

So there is no way for the user to fix this. Maybe some of these fields are normally configured via the SDK configuration within the code and nobody usually touches this part of the app? Either way, seems like a bug!

### Steps to reproduce the bug

Configure ruby on rails application to use unleash SDK like so (where unleash is installed on https://example.com):

**config/initializers/unleash.rb**:
```
Unleash.configure do |config|
  config.app_name            = 'MyRailsApplication'
  config.url                 = 'https://example.com/api'
  config.custom_http_headers = {'Authorization': ENV['UNLEASH_SERVER_API_KEY']}
end

UNLEASH = Unleash::Client.new
```

Start up the application, then navigate to:
https://example.com/applications/MyRailsApplication

Click the "Edit application" tab

Try to change any of the 3 fields displayed (icon, application URL, description)

Then you will see the error

### Expected behavior

No error

### Unleash version

4.22.5

### Subscription type

Open source

### Hosting type

Self-hosted

### SDK information (language and version)

unleash-client-ruby:4.4.2

**Comment by andreas-unleash** [comment]
Hi, @dylannz ! Thanks for bringing this to our attention. I will forward it to the right team and get back to you.

**Comment by gastonfournier** [comment]
I've been able to reproduce this and I've raised a bug internally to look into it in our upcoming cycle
