### ISSUE TITLE
UnknownError: Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by EmadBinAbid** [Unleash/unleash#3640]
### Describe the bug

I am trying to add a new strategy to a feature (`[POST] /projects/:projectId/features/:featureName/environments/:environment/strategies`) with Unleash v5.0.0 but getting `UnknownError: Cannot read properties of undefined (reading 'name')` even after adding all the required fields in the request payload.

My request payload looks like this:

```
{
    "name": "default",
    "constraints": [
        {
            "contextName": "customerId",
            "operator": "IN",
            "values": [
                "6d3285a1-67a4-4267-805a-13befa8b9646",
                "5f3285a1-67a4-4267-805a-13befa8b969d"
            ]
        }
    ]
}
```

and the error I'm receiving looks like this:
```
{
    "id": "811fcc32-ae15-4ba3-8838-2c6319928e1c",
    "name": "UnknownError",
    "message": "Cannot read properties of undefined (reading 'name')",
    "details": [
        {
            "message": "Cannot read properties of undefined (reading 'name')",
            "description": "Cannot read properties of undefined (reading 'name')"
        }
    ]
}
```

I think this is because of some missed handling for `segments` optional request field. Can someone please take a look?

### Unleash version

5.0.0

### Subscription type

Open source

### Hosting type

Self-hosted

**Comment by EmadBinAbid** [comment]
@ivarconr

**Comment by andreas-unleash** [comment]
One question @EmadBinAbid : does the context field `customerId` exist in your context fields? You can check by going to Configure/Context Fields

**Comment by EmadBinAbid** [comment]
@andreas-unleash, nope, it doesn't - it only has default context fields, `environment`, `userId`, `appName`, `currentTime`, 
and `sessionId`; `customerId` is my custom context field. It used to work with v4.16.

**Comment by andreas-unleash** [comment]
Great! If you create the context field, the error should go away.  I will make a task to give a more informative error when this happens. Let me know if your issue persists

**Comment by andreas-unleash** [comment]
You can find out more about contextFields [here](https://docs.getunleash.io/reference/unleash-context).  You are basically asking unleash to use a custom context field it doesn't recognise (that is, it is not part of the context fields)

**Comment by andreas-unleash** [comment]
But thanks for bringing this to our attention.  We should give you a more relevant error: https://github.com/Unleash/unleash/pull/3647

**Comment by chriswk** [comment]
Hi. @EmadBinAbid. To clarify, this did not work in 4.16.4 either, it returned a 500, but with no body. The thing we added for 5.0 was to try to have all errors include a body, better explaining what was wrong. We hadn't caught this one, so that's why you received the UnknownError. 5.0.1 is released, and will now give a 404 with an error message saying why the context information was wrong (The context field could not be found)

**Comment by EmadBinAbid** [comment]
I see; thanks for clarifying @andreas-unleash @chriswk.

Let me briefly explain what I mean when I say it worked for me with v4.16 (just for curiosity and further pondering).

I am consuming Unleash's Admin API, and with v4.16, I used to create features like this:
```
{
    "name": "feature-one",
    "description": "This is feature one",
    "enabled": true,
    "strategies": [
        {
            "name": "default",
            "constraints": [
                {
                    "contextName": "customerId",
                    "operator": "IN",
                    "values": [
                        "6d3285a1-67a4-4267-805a-13befa8b9646",
                        "5f3285a1-67a4-4267-805a-13befa8b969d"
                    ]
                }
            ]
        }
    ]
}
```
The request to create a new feature in v4.16 accepted the `strategies` array within the same payload and added the strategies to the feature. Note that I didn't explicitly create a `customerId` context field - it used to handle it internally. 

Now, with v5.0.0, it no longer creates strategies. Rather I have to use a new endpoint to add a strategy to the feature. So, it has become a two-step process now.

#### Step 1: Create a feature
```
{
    "name": "feature-one",
    "description": "This is feature one",
    "enabled": true
}
```

#### Step 2: Add a strategy to the feature
```
{
    "name": "default",
    "constraints": [
        {
            "contextName": "customerId",
            "operator": "IN",
            "values": [
                "6d3285a1-67a4-4267-805a-13befa8b9646",
                "5f3285a1-67a4-4267-805a-13befa8b969d"
            ]
        }
    ]
}
```
However, step 2 doesn't pass through right now (it doesn't handle context fields internally). Rather I need to create the context field explicitly.

**Comment by EmadBinAbid** [comment]
@andreas-unleash, is there an endpoint that allows creating multiple context fields at once?

**Comment by andreas-unleash** [comment]
Hi @EmadBinAbid , you will have to create them through the UI or 1 by 1. https://docs.getunleash.io/reference/api/unleash/create-context-field
