### ISSUE TITLE
Application title unreadable with dark theme

### ISSUE THREAD

**Issue by HenrikBacher** [Unleash/unleash#3718]
### Describe the bug

When dark theme is enabled the application title on the /application page is still black and hence unreadable (class: _listLink_h6uff_25 & _truncate_h6uff_2)

### Steps to reproduce the bug

1. On self-hosted unleash 5.0.1 go to the /applcation page (configure -> applications)
2. Application shows as black

### Expected behavior

The title should be readable on the dark background

### Unleash version

5.0.1

### Subscription type

Enterprise

### Hosting type

Self-hosted

**Comment by pransh15** [comment]
Hi @HenrikBacher 👋 
Thanks for reporting this issue, I've shared it with the team and someone will get back to you soon on this.
