### ISSUE TITLE
API returns 403 - Forbidden when toggle does not exist

### ISSUE THREAD

**Issue by jdelucaa** [Unleash/unleash#3726]
Dear Unleash team, 

I noticed a peculiar behavior using Unleash server `v4.23.2` and `v5`. When doing a GET request to `<unleash-url>/api/admin/projects/:projectId/features/:featureName` if the toggle does not exist, the API returns 403 - Forbidden (I am using an admin API token), see:

Toggle exists (200 OK):
![image](https://github.com/Unleash/unleash/assets/13077810/853ffd9d-8400-4d6d-aac4-cf37e27253e7)

Toggle does not exist (403 - Forbidden)
![image](https://github.com/Unleash/unleash/assets/13077810/8caeedd1-b7dc-42f7-97ac-267c4b1faf1f)

The error message is a bit misleading too.

### Steps to reproduce the bug

- Perform a GET request to `<unleash-url>/api/admin/projects/:projectId/features/:featureName` by replacing :projectId with an existing project ID and :featureName with a feature toggle that does not exist in the db.
- See 403 - Forbidden error in return 

### Expected behavior

The API should return 404 - Not Found

### Logs, error output, etc.

```bash
{
    "id": "f73da250-2dec-4516-a31b-a3bec40df943",
    "name": "InvalidOperationError",
    "message": "The operation could not be completed. The feature exists, but the provided project id (\"default\") does not match the project that the feature belongs to (\"undefined\"). Try using \"undefined\" in the request URL instead of \"default\".",
    "details": [
        {
            "message": "The operation could not be completed. The feature exists, but the provided project id (\"default\") does not match the project that the feature belongs to (\"undefined\"). Try using \"undefined\" in the request URL instead of \"default\".",
            "description": "The operation could not be completed. The feature exists, but the provided project id (\"default\") does not match the project that the feature belongs to (\"undefined\"). Try using \"undefined\" in the request URL instead of \"default\"."
        }
    ]
}
```
```

### Screenshots
See above

### Additional context
N/A

### Unleash version
v5

### Subscription type
Open source

### Hosting type
Self-hosted

### SDK information (language and version)
N/A

**Comment by gastonfournier** [comment]
Sorry, for the delay in answering this issue! We had some things to look into before this one
