### ISSUE TITLE
postgres jdbc url if databse has schema

### ISSUE THREAD

**Issue by vkatoch2000** [Unleash/unleash#376]
what should be postgres jdbc url if database has not public schema ? 
Let say database = unleash  and schema =  custom_schema
 unleash -d postgres://unleash_user:password@localhost:5432/unleash -p 4242

**Comment by ivarconr** [comment]
You can possibly change the default schema for the postgres user, see [postgres schema doc](https://www.postgresql.org/docs/9.3/ddl-schemas.html)

The unleash-cli does not expose an option to set a custom schema, but you can use unleash [problematically](https://unleash.github.io/docs/getting_started#2-or-programmatically) and specify the `databaseSchema` as option. This is actually undocumented, but used in the e2e tests to allow tests to run in parallel using different schemas.

**Comment by vkatoch2000** [comment]
Thanks for reply
I am unable to locate test case mentioned by you under e2e which is using databaseSchema  as option

**Comment by ivarconr** [comment]
You see the usage here: [db-pool.js](https://github.com/Unleash/unleash/blob/master/lib/db/db-pool.js) where the code defaults to 'public' if options does not specify something else. 

All e2e tests ends up calling [database-init.js#L52](https://github.com/Unleash/unleash/blob/master/test/e2e/helpers/database-init.js#L52) with name as input, which is set as the databaseSchema name. 

A concrete example is [feature.e2e.test.js#L7](https://github.com/Unleash/unleash/blob/master/test/e2e/api/admin/feature.e2e.test.js#L7) where name is sent in as the argument to the setupApp function.

**Comment by vkatoch2000** [comment]
it works , as suggested by ivarconr
