### ISSUE TITLE
client_apps_total prometheus metrics always 0

### ISSUE THREAD

**Issue by Starefossen** [Unleash/unleash#3776]
### Describe the bug

The `client_apps_total` Prometheus metric is always 0 regardless of how many clients are created / in use.

### Steps to reproduce the bug

1. Start Unleash
2. Create an api token through `admin/api`
3. Connect to Unleash instance with the new api token to make it seen by Unleash
4. Fetch Prometheus metrics

### Expected behavior

I expect the `client_apps_total` metrics to be 1 when there is one created client that has successfully connected with the Unleash instance.

### Logs, error output, etc.

```bash
Nothing out of the ordinary
```

### Screenshots

Unleash Admin API UI
<img width="1348" alt="Screenshot 2023-05-15 at 14 55 49" src="https://github.com/Unleash/unleash/assets/968267/70f0426c-a0b1-4f01-b6a0-89c5594cf340">

Grafana Metrics Explorer
<img width="1988" alt="Screenshot 2023-05-15 at 14 57 40" src="https://github.com/Unleash/unleash/assets/968267/c124aa0f-63db-406f-a814-a10cf67ae9c3">

### Unleash version

Unleash 4.23.1 (Open Source)

### Subscription type

Open source

### Hosting type

Self-hosted

### SDK information (language and version)

n/a

**Comment by gardleopard** [comment]
Hi,

Thank you for reporting this!

 A quick look in our metrics show that we get data on this. Could you please provide what sdk and what version you are using so that we can see if we can reproduce it?

**Comment by Starefossen** [comment]
This is Unleash 4.23.1 (https://github.com/nais/unleash) it's the OSS version with a Google Cloud Identity Aware Proxy authentication middleware. The clients are created manually through the Admin UI and they are connecting to the Unleash instance with the latest version of Unleash client SDK for Node.js.

Here is the relevant part from `/internal-backstage/prometheus` for one of our instances:

```
# HELP feature_toggle_update_total Number of times a toggle has been updated. Environment label would be "n/a" when it is not available, e.g. when a feature toggle is created.
# TYPE feature_toggle_update_total counter

# HELP feature_toggle_usage_total Number of times a feature toggle has been used
# TYPE feature_toggle_usage_total counter

# HELP feature_toggles_total Number of feature toggles
# TYPE feature_toggles_total gauge
feature_toggles_total{version="4.23.1"} 2

# HELP users_total Number of users
# TYPE users_total gauge
users_total 2

# HELP projects_total Number of projects
# TYPE projects_total gauge
projects_total 1

# HELP environments_total Number of environments
# TYPE environments_total gauge
environments_total 3

# HELP groups_total Number of groups
# TYPE groups_total gauge
groups_total 0

# HELP roles_total Number of roles
# TYPE roles_total gauge
roles_total 5

# HELP segments_total Number of segments
# TYPE segments_total gauge
segments_total 0

# HELP context_total Number of context
# TYPE context_total gauge
context_total 5

# HELP strategies_total Number of strategies
# TYPE strategies_total gauge
strategies_total 9

# HELP client_apps_total Number of registered client apps aggregated by range by last seen
# TYPE client_apps_total gauge
client_apps_total{range="allTime"} 0
client_apps_total{range="30d"} 0
client_apps_total{range="7d"} 0
```

**Comment by gardleopard** [comment]
Thank you again, we will look into it. 

With the node sdk you should get some metric like this as well:
client_sdk_versions{sdk_name="unleash-client-node",sdk_version="3.19.0"} 1763

Do you have that in your prometheus metrics as well?

**Comment by Starefossen** [comment]
These are empty:

```
# HELP client_sdk_versions Which sdk versions are being used                                 
# TYPE client_sdk_versions counter
                                                                                                                                                                                           
# HELP optimal_304_diffing Count the Optimal 304 diffing with status                         
# TYPE optimal_304_diffing counter         
```

Here is one public example how the the toggles are fetched using the `@unleash/nextjs` SDK: https://github.com/navikt/sykmeldinger/pull/369/files

**Comment by gardleopard** [comment]
Thank you. We will follow up this in the team now. My hypothesis is that the nextjs sdk is not calling the register endpoint when used as a server side sdk.

**Comment by Starefossen** [comment]
Ahh.. makes sense. I will do some tests with some other SDKs in the mean time.

**Comment by kwasniew** [comment]
Next.js SDK doesn't support metrics as of now: https://github.com/Unleash/unleash-client-nextjs#known-limitation

**Comment by Starefossen** [comment]
I think we can close this. If there are some place where the metrics are documented I can make a note that this metric is limited to SDKs that supports this feature and not all clients created in Unleash as I originally thought. 

It would be nice to have a counter for total created clients, but that would be another feature.

**Comment by gardleopard** [comment]
I wonder if it makes sense to put here: https://github.com/Unleash/unleash/blob/main/src/lib/metrics.ts#L140 as this is the explaination of the data. What do you think?
