### ISSUE TITLE
How to integrate Logout support  when using basic authentication prehook in admin UI

### ISSUE THREAD

**Issue by vkatoch2000** [Unleash/unleash#380]

**Comment by vkatoch2000** [comment]
How to integrate Logout support  when using baic authentication hook in admin UI , if we lock on sign out its is doing nothing

**Comment by vkatoch2000** [comment]
for authentication i develop this using example
function basicAuthentication(app) {
    app.use('/api/admin/', (req, res, next) => {
        var credentials  = auth(req);

        if (credentials && credentials.name == process.env.UNLEASH_USERNAME_VALUE  && credentials.pass == process.env.UNLEASH_PASSWORD_VALUE ) {
            const user = new User({ email: `${credentials.name}@wirelesscar.com` });
            req.user = user;
            next();
        } else {
            return res
                .status('401')
                .set({ 'WWW-Authenticate': 'Basic realm="example"' })
                .end('access denied');
        }
    });

    app.use((req, res, next) => {
        req.session.nowInHours = Math.floor(Date.now() / 3600e3);
        next();
    });
}

module.exports = basicAuthentication;

**Comment by vkatoch2000** [comment]
function basicAuthentication(app) {
    app.use('/api/admin/', (req, res, next) => {
        var credentials  = auth(req);

        if (credentials && credentials.name == process.env.UNLEASH_USERNAME_VALUE  && credentials.pass == process.env.UNLEASH_PASSWORD_VALUE ) {
            const user = new User({ email: `${credentials.name}@xyz.com` });
            req.user = user;
            next();
        } else {
            return res
                .status('401')
                .set({ 'WWW-Authenticate': 'Basic realm="example"' })
                .end('access denied');
        }
    });

    app.use((req, res, next) => {
        req.session.nowInHours = Math.floor(Date.now() / 3600e3);
        next();
    });
}

module.exports = basicAuthentication;

**Comment by ivarconr** [comment]
You probably have to intercept calls to `/api/user/logout` and make sure to redirect to the login-flow. This will probably vary, depending on how you have integrated basic auth. 

Some details on the basic auth logout issue;
https://stackoverflow.com/questions/233507/how-to-log-out-user-from-web-site-using-basic-authentication

**Comment by vkatoch2000** [comment]
will update you once done

**Comment by vkatoch2000** [comment]
It works using this ....
function basicAuthentication(app) {

    app.use('/api/admin/user/logout', (req, res, next) => {
      return res.status('401')
                    .set({ 'WWW-Authenticate': 'Basic realm="example"' })
                    .end('You have successfully logged out');
    });

    app.use('/api/admin/', (req, res, next) => {
        var credentials  = auth(req);

        if (credentials && credentials.name == process.env.UNLEASH_USERNAME_VALUE  && credentials.pass == process.env.UNLEASH_PASSWORD_VALUE ) {
            const user = new User({ email: `${credentials.name}@xyz.com` });
            req.session.user = user;
            next();
        } else {
            return res
                .status('401')
                .set({ 'WWW-Authenticate': 'Basic realm="example"' })
                .end('access denied');
        }
    });
}
