### ISSUE TITLE
Add support for 'projects'

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash#381]
It would be nice to add support for projects. The idea is to simplify workflow for users and reduce load on clients. 

Some **loose** thoughts: 
- A project should be defined with a unique name, and id, and a description. One should be able to use permission system to assign users the rights to see specific projects. 
- One toggle can be assigned to one (or more) projects. 
- Clients should only ask for toggles connected to projects they care about. 
- Clients not asking for a specific project should get toggles not assigned to a project (backward compatibility).

**Comment by GrgDev** [comment]
I'd just like to 👍 this with the additional comment that I was about to open a new feature request that would have been covered by this one anyways.

More specifically, it appears to me that no matter what, all requests to the `/api/client/features` endpoint will always get all the information for all feature flags, regardless of if you want them all or not. This is probably fine for awhile but as more and more people use a particular Unleash instance with more and more feature flags, it eventually becomes a problem of a lot of wasted bandwidth at larger scales, given enough active feature flags and apps. It would be nice to be able to let clients specify a subset that they specifically care about.

**Comment by GrgDev** [comment]
Correction: Most of the time the `/api/client/features` endpoint returns a `304 Not Modified` response but that doesn't really change the fact that if I bounce the unleash server or the client fleet or some other case that might prevent a valid `304 Not Modified` from being sent, a bunch of data is being sent that most of the clients probably don't care about.

**Comment by juancgalvis** [comment]
are anyone working on this issue? i want to contribuite with it, to make it available on 4.x release

**Comment by ivarconr** [comment]
Not at the moment. But it is on the roadmap. If you have capacity and interests in contributing we should probably start defining the specifications. 

Maybe we could discuss this a bit further on [slack](https://join.slack.com/t/unleash-community/shared_invite/enQtNjUxMjU2MDc0MTAxLTJjYmViYjkwYmE0ODVlNmY1YjcwZGRmZWU5MTU1YTQ1Nzg5ZWQ2YzBlY2U1MjlmZDg5ZDRmZTMzNmQ5YmEyOGE)?
