### ISSUE TITLE
Support audit trail

### ISSUE THREAD

**Issue by geekyme** [Unleash/unleash#382]
Unleash will frequently be used by several individuals so there needs to be a way to track “who did what”.

This will often be the needs of enterprises. I don’t see any documentation on this. Any ideas whether this could be implemented / already implemented?

**Comment by ivarconr** [comment]
So you have the "history" view per toggles and also an aggregated view of all changes. Here you can see what changed and by who. 

![image](https://user-images.githubusercontent.com/158948/51819304-36d64780-22d2-11e9-9b62-ce9faf7ce18e.png)

Is this enough? Or is there more that should be added in your view? 

(I must admit that the view could leverage some polish)

**Comment by geekyme** [comment]
This is enough. Thanks.
