### ISSUE TITLE
feature: add webhook events for 'potentially stale' flags

### ISSUE THREAD

**Issue by yossi-chen** [Unleash/unleash#3898]
### Describe the feature request

We have webhooks for feature-stale-on and off, but they are being triggered upon user actions.
I'd like to set up alerts when feature flags are potentially stale, so I know that its time to remove them from the code.

### Solution suggestions

Add a webhook event for feature-potentially-stale

**Comment by sjaanus** [comment]
Hi @yossi-chen, we have prioritize to add this functionality this quarter.
