### ISSUE TITLE
Unleash provider for OpenFeature

### ISSUE THREAD

**Issue by kiranpatel11** [Unleash/unleash#3912]
### Describe the feature request

OpenFeature is an attempt to standardize the feature toggle API.

Unleash can also be added as provider for OpenFeature SDKs.

### Background

Standardization and provide vendor agnostic APIs.

### Solution suggestions

Reference: https://openfeature.dev/docs/reference/concepts/provider

**Comment by pransh15** [comment]
Hi @kiranpatel11 👋 

Thanks for submitting this issue. I'll be closing this issue since this is a duplicate. We already have an open discussion about OpenFeature in #3896, would be helpful to take this conversation there.

Short answer for reference:

> We are monitoring the space and are interested in OpenFeature, but currently we do not have the bandwidth internally to pursue this. As we always do, we listen to our community and insightful ideas to understand how we can we provide value.
> 
> Perhaps, if your or someone from the community would like to take this up, we'd be happy to help kickstart the initiative!
