### ISSUE TITLE
Toggling features in an out of sync browser can have unintended consequences

### ISSUE THREAD

**Issue by Catuna** [Unleash/unleash#394]
If I have an outdated view of the feature list where my browser shows a feature being on when it is actually off and I toggle that feature, my view is that I took the feature from the off state into the on state, in reality what I actually did was take the feature from the on state to the off state.

This is because when the toggle button is pressed it only tells the server to "toggle" not which state I am intending to set it to. The client also does not receive feedback as to what actually happened on the server, and will show me that the feature was toggled on when the server actually toggled it off.

My suggestion would be to have the client tell the server which state it intends to set the feature to, for example by implementing "toggle/on" and "toggle/off" instead of just "toggle". The server can then either set the correct state based on what the client intended, or alternatively send an error to the client informing them the state has changed and they need to reload the page.

Another solution would be to have some real-time sync of feature toggle status, however if the connection is broken for whatever reason then this can still happen.

**Comment by ivarconr** [comment]
Yes indeed. 

> My suggestion would be to have the client tell the server which state it intends to set the feature to, for example by implementing "toggle/on" and "toggle/off" instead of just "toggle". The server can then either set the correct state based on what the client intended

This sounds like a great solution ;)
