### ISSUE TITLE
/applications list in UI should be searchable

### ISSUE THREAD

**Issue by henrik242** [Unleash/unleash#404]
A proper search/filter field would be nice.

Also, ctrl-F doesn't work on this page  (at least not in in FF (v65.0.1 on MacOSX Mojave)), so the list is a bit painful to navigate.

**Comment by ivarconr** [comment]
Yes, application list never got any love. We should reuse the same filter component used for feature toggle lists.

**Comment by ivarconr** [comment]
https://github.com/Unleash/unleash-frontend/pull/225/commits/5c12581adf081593074f8883554ceb7a393834d9
