### ISSUE TITLE
feat: Add copy button next to feature flag name

### ISSUE THREAD

**Issue by elmaxe** [Unleash/unleash#4098]
### Describe the feature request

I would like there to be a "copy feature flag name" button next to the feature flag name

![image](https://github.com/Unleash/unleash/assets/33149910/a37e74fa-bd21-46e9-84bf-fa40347916d1)

Perhaps also in the dots menu (the copy button is not for copying the name):
![image](https://github.com/Unleash/unleash/assets/33149910/b33edc9e-b220-4a24-ae46-23cb9e142a19)

### Background

We define our feature flags as a type in our typescript code. Whenever we add a new feature flag we have to manually copy its name to the type. Being able to copy it quickly would be nice

**Comment by nunogois** [comment]
Hi @elmaxe, thank you for opening this issue with your suggestion. We'll take it into account and discuss it internally. Hope we can get back to you soon!

**Comment by Curis-lab** [comment]
I want to contribute to this issue, but I didn't understand it perfectly. Do you know where the flag name is? Where should I add copy button? What kind of process do you want? Could you explain me?

**Comment by nunogois** [comment]
Hi @Curis-lab, thank you for your interest in contributing!

We have something like this in mind:
![image](https://github.com/Unleash/unleash/assets/14320932/88b6f985-604c-47a3-8922-68338061f8a1)

![image](https://github.com/Unleash/unleash/assets/14320932/534e91f1-fe7e-4a27-af8e-d0c9fb719227)

But we're open to other suggestions. Let me know if this helps 🙂

**Comment by mohanrajnambe** [comment]
Hi @nunogois, I would like to take up and work on this issue.

**Comment by nunogois** [comment]
Hi @mohanrajnambe, of course, I've assigned it to you. Thank you for volunteering!

**Comment by mohanrajnambe** [comment]
Hi @nunogois, I have raised a PR for the feat. Please guide me through, if I have missed any step. Thank you!
