### ISSUE TITLE
Question - bulk isEnabled Functionality?

### ISSUE THREAD

**Issue by dfederico** [Unleash/unleash#413]
Was wondering if there is a way to send several toggle names at once with a context, isEnabled looks like it just expects a string, not an array of strings or any variation on that.  Any best practices/guidance appreciated!

**Comment by ivarconr** [comment]
Hi @dfederico,

This is a SDK specific concern and currently the official SDKs does not provide such an interface.

It is fairly simple to implement this yourself by simple array reduce

E.g. an JavaScript implementation would look like:

```js
const context = {userId: '123'};
const toggleNames = ['Demo', 'featureX'];
const toggleStatus = toggleNames.reduce((result, name) => {
        result[name] = isEnabled(name);
        return result;
}, {});

// toggleStatus={"Demo":false,"featureX":true}
```

I am unsure of the value to add this to the official API of the clients as I believe in keeping it as simple and concrete as possible. 

What do you think?

**Comment by dfederico** [comment]
So my overall goal was to reduce network requests to the unleash server, preventing a call for each feature flag individually.  A reduce or a map would certainly work to yield the correct values, but would still query individually.  I was just wondering if there was value in handling several requests at once, or maybe even getting the status of all feature flags on the unleash server in one request.

**Comment by ivarconr** [comment]
> So my overall goal was to reduce network requests to the unleash server

To be super fast, the client SDK caches all feature toggles and their current configuration in memory. The activation strategies are also implemented in the SDK. This makes it really fast to check if a toggle is on or off because it is just a simple function operating on local state, without the need to poll data from the database. Se more in [client specification](https://unleash.github.io/docs/client_specification).

**Comment by ivarconr** [comment]
@dfederico did that answer your question? Ok to close?

**Comment by dfederico** [comment]
Yes that answered it, good to close!  thanks for your help.

**Comment by react-ghost** [comment]
Just find that the useUnleash interface is ```const useFlag: (name: string) => boolean;```

Because React hook cannot be called on the function, useFlag cannot use the above solution.
How can use bulk isEnabled functionality on the React?

Thank you in advance!
