### ISSUE TITLE
Unable to run migration on mysql dabase

### ISSUE THREAD

**Issue by dhiva** [Unleash/unleash#416]
I am trying to setup unleash with mysql but I am unable to install any of the migration files as there errors (ER_INVALID_DEFAULT and ER_PARSE_ERROR) executing them. I am currently using MySQL 5.7.25 which has support for json data type. Could you please provide support for MySQL database.

**Comment by ivarconr** [comment]
Sorry, currently we only support PostgreSQL, and both migrations and queries are tightly connected to this constraint. 

I have on the roadmap to enable adaptable data-sources, this will require some rework in the code.

I close this in favour of #316
