### ISSUE TITLE
Failing to create custom strategy

### ISSUE THREAD

**Issue by yuriron** [Unleash/unleash#419]
I defined new custom strategy that should enable feature based on tenant. I pass tenant in code, but it doesn't seems to work:
`
 UnleashContext unleashContext = 
 UnleashContext.builder().userId(userId).addProperty("tenant", tenant).build();
        boolean isEnabled = unleash.isEnabled("ExtendedGreeting", unleashContext, false) ? "Hello " + userId : userId;
`

Please advice.

**Comment by ivarconr** [comment]
Hi, 

I assume you use the java-client. How did you implement the tenant strategy in the client? And did you remember to pass it in to the constructor?

**Comment by yuriron** [comment]
Hm. I didn't pass it to constructor. I didn't found relevant example. Could you please provide one?
And yes, you are right, I use Java client. Only userWithId strategy works for me.

**Comment by ivarconr** [comment]
Yes, you should implement the logic for the strategy like this:

```java
final class TenantStrategy implements Strategy {

    protected static final String PARAM = "tenants";

    @Override
    public String getName() {
        return "tenant";
    }

    @Override
    public boolean isEnabled(Map<String, String> parameters) {
        return false;
    }

    @Override
    public boolean isEnabled(Map<String, String> parameters, UnleashContext unleashContext) {
        Optional<String> currentTenant = Optional.ofNullable(unleashContext.getProperties().get("tenant"));
        if(currentTenant.isPresent()) {
            List<String> configuredTenants = asList(parameters.get(PARAM).split(",\\s?"));
            return configuredTenants.contains(currentTenant.get());
        } else {
            return false;
        }
    }
}
```

And remember to register it with Unleash:

```java
UnleashConfig config = new UnleashConfig.Builder()
        .appName("test")
        .instanceId("my-hostname:6517")
        .unleashAPI("http://localhost:4242/api")
        .build();

Unleash unleash = new DefaultUnleash(config, new TenantStrategy());
```

**Comment by yuriron** [comment]
Thanks, it worked.
