### ISSUE TITLE
🟢  feat: Terraform provider

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash#4201]
### Describe the feature request

Make it possible to provision and manage resources in Unleash via Terraform.

### Background

Terraform is an open-source infrastructure-as-code software tool created by HashiCorp. It is quite popular among companies using Unleash. 

### Solution suggestions

If anyone have past experience with Terraform and wants to contribute, let us know. 

A possible good start:
https://github.com/philips-labs/terraform-provider-unleash

**Comment by gastonfournier** [comment]
We've opened a public channel in our community Slack to have a more direct communication [#terraform-provider](https://app.slack.com/client/TGN5JSCV7/C05LJG6RU05)

**Comment by gastonfournier** [comment]
We have an alpha version released https://registry.terraform.io/providers/Unleash/unleash 

We are still working on enabling new resources, testing, and maturing the provider, but as usual, we build incrementally and seek fast feedback. 

Use it, leave us a comment on Slack https://slack.unleash.run/

**Comment by simenandre** [comment]
I would love to see (and help build) a Pulumi provider as well. Might be a subject for Pulumiverse (the community org built around Pulumi).

**Comment by gastonfournier** [comment]
Hi @simenandre! That'd be cool! I am unsure how Pulumiverse works, maybe you can provide me with more details in our [community chat](https://unleash-community.slack.com/archives/C05LJG6RU05/p1701971476460489). 

The terraform provider took a lot of investment on our side and it's still in a maturing phase where not all the features we want are supported. We'll continue to adapt it based on the feedback and needs of both customers and the community. So, before committing to a new integration, my take would be to try something like https://github.com/pulumi/pulumi-terraform-bridge or ask for help from the community as you suggested.

**Comment by ivarconr** [comment]
We would love to get some external help and guidance here @simenandre! We are a heavy user of Pulumi internally. Thanks for raising this! 

Looping in @dgorton.
