### ISSUE TITLE
Suggestions for more "enterprise readiness"

### ISSUE THREAD

**Issue by zivyatziv** [Unleash/unleash#424]
Hi,

I've recently implemented unleash, tried it out a little and came up with the following suggestions:
1. Unleash 'mission statement' is 'Unleash is an enterprise ready feature toggles service'. As such, it should be able to provide distribution of features based on a Customer and Environment.
1.a Let's say I have many customers, I have different deployments for every customer. I use Unleash to release different features based on different customers (let's say one customer is in west Europe and another is in east Europe).
1.b Negotiations are being made between customer 'A' and we want to upgrade our security, hence we both have "development" environments in which we test and produce the new features before deploying it to production.
![image](https://user-images.githubusercontent.com/39673349/56471227-b2224200-6458-11e9-8cc8-f38a2c3724d7.png)

2. As such, having a feature name is a primary key is wrong.
2.a Primary key should be a running sequence.
![image](https://user-images.githubusercontent.com/39673349/56471281-5f955580-6459-11e9-8e7d-d38db16a7e5e.png)

2.b Validation should be based on all fields: Name, Customer, Environment.
![image](https://user-images.githubusercontent.com/39673349/56471255-11805200-6459-11e9-8e34-9da7aa00a2ab.png)

3. Search should filter through customers and environments also.
![image](https://user-images.githubusercontent.com/39673349/56471268-3b397900-6459-11e9-91fc-38153dfbff9f.png)

4. Creating / Updating / Toggling a feature with an environment of reserved words like 'prod', 'production', 'dist', 'distribution' should be marked as 'dangerous' and pop up an error message to the user showing said warning:
![image](https://user-images.githubusercontent.com/39673349/56471136-8f435e00-6457-11e9-89df-5189b7f397b2.png)
4.a As such, features in reserved environments should be visibly different from others.
![image](https://user-images.githubusercontent.com/39673349/56471208-91f28300-6458-11e9-9777-5462d20ff8d8.png)

5. It is very common for a feature to be dependant on another feature, such as Feature 'A' is a pre-requisite of Feature 'B' which is a pre-requisite of Feature 'C'. Defined: C > B > A.
5.a Disabling / Enabling a root feature will either toggle accordingly all child features
5.b Disabling / Enabling a root feature will pop a list with all child features and disable/enable features specifically with the ability to select all.

I have implemented points 1-4, I can share my code, and I'd be happy if we can integrate it with unleash. (Both frontend and backend wise).
I don't have it separated for each 'new feature / content' rather all together.

Please share your thoughts on my proposal and thanks for your efforts!
ZY

**Comment by ivarconr** [comment]
Hi @zivyatziv,

Thanks for sharing your ideas and thoughts on how you want Unleash to work!

I agree that Unleash should better support multiple Environments. Until now users of Unleash has solved this by deploying one instance of Unleash in each Environment. I want to change this, and have started to look into it. Expect more details on this in the following weeks. 

> As such, having a feature name is a primary key is wrong.

If I was redesigning Unleash today I would probably have solved it with a running sequence number. This _might change_ when start looking in to adding environment support. 

> Creating / Updating / Toggling a feature with an environment of reserved words like 'prod', 'production', 'dist', 'distribution' should be marked as 'dangerous' 

Maybe. I am not a to big fan of 

When it comes to your needs to better support your customers and different needs for them I will argue that this is exactly what activation strategies are for. You can define your own activation strategy which takes customer-identifier as input and combines this with whatever you like (e.g percentage based roll-out). 

However I must admit that activation strategies are not as flexible as it should be. I have started thinking about one new “flexible” strategy type, where you should be able to define which context parameters you care about, and simple rules for combining them. This would materialize itself in a simple DSL which can be natively supported by all client implementations (avoiding the need to do custom implementations). 

Example on how it could look like:

```
IF ‘customer’ IN ‘listOfCusomers’ 
AND ‘device’ IN ‘listOfDevices’
OR ‘userId’ IN ‘listOfUserIds’
DO ‘gradualRollout’ ‘100’
```

> It is very common for a feature to be dependant on another feature, such as Feature 'A' is a pre-requisite of Feature 'B' which is a pre-requisite of Feature 'C'. Defined: C > B > A.

On of the core design goal of Unleash is to keep things simple. We have not have any problem by handling this over the years inside FINN.no across hundreds of applications.
