### ISSUE TITLE
Supporting SSL

### ISSUE THREAD

**Issue by skbolton** [Unleash/unleash#426]
This seems like it might be in the middle of a lot of the dependencies of this project but I wanted to see what you guys have to say about it. In our company we use SSL to all connections to our databases. I am seeing references to issues in `db-migrate` of how to do it, but looking at the way that unleash calls it in the migrator there is no way to specify ssl in the configs.

If not currently supported then maybe an option in `unleash.start(...)` could be PR'ed?

**Comment by ivarconr** [comment]
> I am seeing references to issues in db-migrate of how to do it, but looking at the way that unleash calls it in the migrator there is no way to specify ssl in the configs.

Which issues are you thinking about? 

The two database libraries used by unleash, `db-migrator` and `knex`, both uses `pg` under the hood and should support SSL connections. Currently I am using Unleash in production with the `ssl=true` flag and all connections are over ssl with version set to `TLSv1.2` both during migration and at runtime. 

`postgres://unleash_user:passord@localhost:5432/unleash?ssl=true`

> If not currently supported then maybe an option in unleash.start(...) could be PR'ed?

Yes of course, and I will be glad to assist.

**Comment by skbolton** [comment]
Perfect. I was not aware of that option and it worked great.
