### ISSUE TITLE
Run the App on a different path?

### ISSUE THREAD

**Issue by jbiancot** [Unleash/unleash#4298]
Hi there,

I was wondering how I could run the Unleash app and API on a different base URL, e.g:

http://localhost:4242/unleash/  instead of  http://localhost:4242/

Thanks,

**Comment by shubhamku044** [comment]
Can't we direct from localhost:4242 to localhost:4242/unleash?

**Comment by gastonfournier** [comment]
Hi @jbiancot, 

I think you're looking for `server.baseUriPath`. You can find documentation here: https://docs.getunleash.io/reference/deploy/configuring-unleash

Let me know if that solves the problem
