### ISSUE TITLE
[Question] Caching

### ISSUE THREAD

**Issue by lhrolim** [Unleash/unleash#439]
Hi is there any cache mechanism enabled for Unleash? Does every request hit the database?

Is there any possibility to insert a Redis layer to prevent those hits?

Thanks

**Comment by ivarconr** [comment]
The client SDKs will do the caching locally and sync with the server in the background. "isEnabled" calls with work on local state and not hit HTTP or DB at all.

**Comment by lhrolim** [comment]
@ivarconr just as a followup:

Is there any place on the current documentation that mentions such valuable piece of information?

Otherwise it could be a good addition to the main doc: some sort of "how it works" section

**Comment by ivarconr** [comment]
It is mentioned here: https://unleash.github.io/docs/client_specification#system-overview

But this should probably be lifted a bit to make it more accessible?
