### ISSUE TITLE
[Question] Is it possible to load unleash server to an endpoint?

### ISSUE THREAD

**Issue by benbenedek** [Unleash/unleash#440]
Thank you for creating this awesome product, It is super helpful and time-saving to not develop this tool in-house.

My question: is it possible to mount unleash server into an endpoint rather than start a new express instance for it (with its own port)? 

Thank you for your help.

**Comment by ivarconr** [comment]
Thanks for your kind words!

> is it possible to mount unleash server into an endpoint rather than start a new express instance for it (with its own port)?

No this is currently not possible.

However you can connect it to an [IPC endpoint](https://nodejs.org/api/net.html#net_identifying_paths_for_ipc_connections),via the [pipe options](https://unleash.github.io/docs/getting_started#2-or-programmatically). Not sure if this will be of any help for what you are asking.

**Comment by benbenedek** [comment]
@ivarconr Thanks, I'll read more into these options.
