### ISSUE TITLE
feat: Strategy Constraints. 

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash#442]
The idea is that we can provide one activation strategy that is flexible enough to **replace most of today’s activation strategies**. The idea is that this strategy will avoid the need for users of Unleash to provide their own strategy implementation in the client SDK. We call this strategy the `Flexible Rollout Strategy`.

## How will it work?
The Flexible Rollout Strategy should allow the user to specify a set of constraints. All constraints are AND-ed together, meaning that all of them needs to be satisfied. The last constraint of the strategy is the rollout-percentage. 

Solving this will address the following issues: #424, #389, #229

### Admin UI
![2019-05-24-142716_900x767_scrot](https://user-images.githubusercontent.com/158948/58328008-52410180-7e31-11e9-90dc-72385bee3427.png)

### Protocol Example
```json
{
  "name": "Demo",
  "description": "hello world",
  "enabled": true,
  "strategies": [
    {
      "name": "FlexibleRollout",
      "id": "123123",
      "parameters": {
        "rollout": "52",
        "stickiness": "default",
        "groupId": "Demo"
      },
      "constraints": [
        {
          "contextName": "environment",
          "operator": "IN",
          "values": ["local", "dev"]
        }
      ]
    }
  ],
  "createdAt": "2019-04-30T20:34:31.690Z"
}
```

**Constrain operators** that should be supported:
- IN  		`<list of values>`
- NOT IN 	`<list of values>`

We can configure multiple Flexible Rollout strategies to target different segments of users, customers, environments, or whatever. 

**stickiness** is used to define how we guarantee consistency for gradual rollout. The same userId and the same rollout percentage should give predictable results. Configuration that should be supported:
- DEFAULT - Unleash chooses the first value present on the context in defined order userId, sessionId, random. 
- USERID - guaranteed to be sticky on userId. If userId not present the behaviour would be false
- SESSIONID - guaranteed to be sticky on sessionId. If sessionId not present the behaviour would be false.
- RANDOM - no stickiness guaranteed. For every isEnabled call it will yield a random true/false based on the selected rollout percentage. 

**groupId** is used to ensure that different toggles will hash differently for the same user. The groupId should default to feature toggle name, but need to be overridable to make it possible for a user to correlate rollout of multiple feature toggles. 

**id** must be a unique id for that strategy configuration of this feature toggle. If a feature toggle uses three different activation strategies each definition needs to use a unique metric id. It is preferable if this is just a random string, and should not be changed even if the strategy order is changed. It should be used by the client SDK to tag metrics sent back to unleash. This way we will be able to show in the UI which activation strategy configuration that resulted in this toggle being evaluated to true. 

## Use cases
1. We can combine multiple Flexible Rollout Strategies to enable for the team and some users
```
userId IN “11, 12” AND rollout=100 
OR
customerId IN ”123” AND rollout=50
```

2. Combine multiple Flexible Rollout Strategies to support different rollout across environments
```
environment IN “dev, stage” AND rollout=100 
OR
environment IS “PROD” AND rollout=1
```

3. Combine multiple Flexible Rollout Strategies to support different rollout across regions and customers

```
region IN “europe, africa” AND customer IN “11, 12” AND rollout=10 
OR
region IN “us” AND customer IN “99, 88” rollout=10
```

4. Flexible Rollout strategy will replace “default” strategy
```
rollout=100
```

5. Flexible Rollout strategy will replace “userWithId” strategy
```
userId IN “123, 123” AND rollout=100
```

6. Flexible Rollout strategy will replaces “rollout” strategies (*)
```
rollout=45
```
*) Users should select what stickiness they prefer (default, userId, sessionId, random)

## Static Context fields

To support this strategies, and also custom strategies, the Unleash Context should be extended with two static fields. These values should be defined as part of the initialisation of the client SDK (applicationName is already a required field) and should be bootstrapped on the context object. 
- environment - Name of the current environment (local, dev, stage, prod)
- application - The name of the application

## Things we still need to figure out
- Admin UI should know about possible context parameters. 
  - Users should be allowed to define all their custom context parameters. 
  - Client SDK should report which context parameters they support. This can be sniffed out from actual usage. 
- Metrics should add labels to make it possible to show metrics per strategy. 
 We should also consider to add applicationName as a metric label. 
- It should be possible to define type of value, and in some cases a defined list of values a parameter takes. (Ex: Environments should be a “select input” where the users of Unleash can define a set of environments they support.). Some type examples:
  - IP
  - List of define values
  - Timestamps
  - Regex (I am very skeptical about providing regex support across languages. Can be a performance and security trap) 
- Should we define a way to “reuse” a Flexible Rollout strategy configuration across feature toggles? It can be a bit tedious to “redefine” the same config across multiple toggles. 
  - Suggestion: “Duplicate strategy configuration”

**Comment by ivarconr** [comment]
So this is how it would look like in the UI if you do a 100% rollout to local+dev and 10% rollout to prod:
![image](https://user-images.githubusercontent.com/158948/58330517-5112d300-7e37-11e9-8073-93009796d217.png)

**Comment by ROUDALI** [comment]
great job (y)

**Comment by ivarconr** [comment]
After thinking a bit more about this I believe also custom strategies should be allowed to take advantage of constraints.

**Comment by ivarconr** [comment]
I order to move in this direction we need to introduce two new fields in the [Unleash Context](https://unleash.github.io/docs/unleash_context) 

- environment
- appName

Both these static context fields should be configured at initialisation of the unleash SDK and be set as default values of the Unleash Context provided to the strategy implementations.

**Comment by elhoyos** [comment]
@ivarconr I'm really excited seeing this coming through as it is. Looks fantastic!

> groupId is used to ensure that different toggles will hash differently for the same user. The groupId should default to feature toggle name, but need to be overridable to make it possible for a user to correlate rollout of multiple feature toggles.

Could you clarify on the usefulness to override the `groupId`, please? I've been unable to think of a use case that explains the correlation of multiple feature toggles.

**Comment by ivarconr** [comment]
> I'm really excited seeing this coming through as it is. Looks fantastic!

Thanks, I hope this will make Unleash somewhat easier to use. 

> Could you clarify on the usefulness to override the groupId, please?

Good question. I have a vague memory if this being important for correlate roll-out, when different toggle names is used to control various parts of the same feature. This might be an anti-pattern? 

On that note: 
I have decided to split this task in two. After starting the initial implementation i realised that "Strategy Constraints" would benefit all strategies, and should be a applicable to all strategy configurations. "FlexibleRollout" strategy support will be a different task.

**Comment by elhoyos** [comment]
>...to control various parts of the same feature.

If for the same feature, yeah, I think we could encourage users to use a single toggle instead.

Taking this thinking further and switching multiple toggles of different features at the same time, like a web-site re-launch, looks very convenient at first sight. However, it certainly is inappropriate and defies the safer route to go into small steps. It just overcomplicates things. A single toggle would still be feasible and easier to manage. 

Now, let's assume the multiple toggles scenario exists. Because the project has a very special marketing campaign that could not get planned accordingly or the dev team has realized later that to toggle a set of kill switches is necessary. We could allow the operators to choose (label?) and switch multiple features from the administration UI.

In any case, it looks to me that we could manage the hashing of different toggles for the same user without asking for the `groupId` in the UI. Does it make sense?

**Comment by ivarconr** [comment]
I agree to your reasoning (others would have to state why they require to coordinate roll-out across toggles if they disagree). 

I think we should keep the groupId in the protocol, but default it to the toggle name. This makes it possible to revert later. It's important to have toggle name as part of the hashing salt, together with the user id, to ensure that we are not always testing a new features on the same users.

**Comment by AroglDarthu** [comment]
Perhaps you could increase reuse of constraints over featureflags by separating the constraints to an **TargetAudience** of sorts:
- TargetAudiences
```json
[
  {
    "name": "Scandinavia",
    "id": "123",
    "constraints": [
      {
        "contextName": "Country",
        "operator": "IN",
        "values": ["Denmark", "Norway", "Sweden"]
      }
    ]
  },
  {
    "name": "MiddleAgedWomen",
    "id": "456",
    "constraints": [
      {
        "contextName": "gender",
        "operator": "IN",
        "values": ["F"]
      },
      {
        "contextName": "age",
        "operator": "IN",
        "values": ["30", "31", "etc", "45"]
      }
    ]
  },
  {
    "name": "YoungMen",
    "id": "789",
    "constraints": [
      {
        "contextName": "gender",
        "operator": "IN",
        "values": ["M"]
      },
      {
        "contextName": "age",
        "operator": "IN",
        "values": ["18", "19", "etc", "25"]
      }
    ]
  }
]
```
- FeatureFlags
```json
[
  {
    "name": "Feature1",
    "description": "hello world",
    "enabled": true,
    "strategies": [
      {
        "name": "FlexibleRollout",
        "id": "123123",
        "parameters": {
          "rollout": "52",
          "stickiness": "default",
          "groupId": "Feature1"
        },
        "targetAudiences": [
          "123",
          "456"
        ]
      }
    ],
    "createdAt": "2019-04-30T20:34:31.690Z"
  },
  {
    "name": "Feature2",
    "description": "hello world",
    "enabled": true,
    "strategies": [
      {
        "name": "FlexibleRollout",
        "id": "123123",
        "parameters": {
          "rollout": "52",
          "stickiness": "default",
          "groupId": "Feature2"
        },
        "targetAudiences": [
          "123",
          "789"
        ]
      }
    ],
    "createdAt": "2019-04-30T20:34:31.690Z"
  }
]
```

**Comment by ivarconr** [comment]
Thanks, this makes sense.

**Comment by ivarconr** [comment]
This is part unleash-enterprise, https://www.unleash-hosted.com/articles/strategy-constraints

**Comment by ilves** [comment]
So this feature is not added to opensource version?

**Comment by kad3nce** [comment]
I am working on our initial Unleash integration now. We immediately ran into a case where we need to write custom activation strategies to activate on properties other than user id (account id in this case). Strategy constraints would solve this easily. Strategy constraints seem like a far superior approach, which sits right at the core of Unleash, and dramatically changes the way one would use it. It's odd to me that something so fundamental would be a hosted-only feature.

Also, it seems like bad form to interact with the community in a number of threads to converge on a superior design and then decide to take it into the closed product with such a terse explanation. Can we get a little more insight into your thinking here, please?

What were the reasons you decided to go this route? Will this functionality ever come to the community version?

**Comment by ivarconr** [comment]
fyi; https://github.com/Unleash/unleash/pull/2112
