### ISSUE TITLE
Logout from unleash

### ISSUE THREAD

**Issue by ROUDALI** [Unleash/unleash#443]
how we can handle logout in Unleash?

**Comment by ivarconr** [comment]
It depends on how you integrate your authentication logic. In general terms the UI will call /api/admin/user/logout when the user requests logout. This will clear the request session. If your auth provider requires special logout logic you will need to provide a logout-function on the request object. 

Which version of Unleash are you using?
(there was a bugfix regarding logout in 3.2.5)

**Comment by ROUDALI** [comment]
ok i see thank's i'm using 3.2.10 by the way
