### ISSUE TITLE
Enable feature for userId through API

### ISSUE THREAD

**Issue by ErwinSteffens** [Unleash/unleash#446]
Is there a simple option to enable a feature for a userId through the API?

We are introducing a new storage system. We need to do a per customer migration process in which we copy data and want to enable the new storage system for each customer in Unleash.

What we are thinking of now:
* Creating a new activation strategy in which the customer enrollment date is used to check if it is enrolled after a certain date, so it automatically uses the new storage system.
* Run migration to new storage for each customer on a slow rate so we can monitor performance and after each migration, flip the feature flag through the API.

I see we can now update a feature through the admin API (https://unleash.github.io/docs/api/admin/features#update-a-feature-toggle), but we have to put in all userIds. I think it would be better to be able to just add a single userId.

Any suggestions on how to handle this situation?

**Comment by ivarconr** [comment]
Are we are talking about a huge amount of userIds? If the number is high  I would suggest to use a custom strategy instead and set a specific flag ("is_migrated") on the user, which is used to match against in the strategy implementation. This will also make you less dependent of the synchronisation delay from the unleash-api to the client applications.

**Comment by ErwinSteffens** [comment]
Yes, something with 5 figures. Good that you mention sync delay, which could be a real issue for this use-case.

I am in doubt if using feature flags for this would be the way to go. When we store a flag with the user we can also directly use this one in our application.

**Comment by ivarconr** [comment]
> I am in doubt if using feature flags for this would be the way to go. When we store a flag with the user we can also directly use this one in our application.

Indeed. Could be nice if a [kill-switch](https://medium.com/unleash-hosted/kill-switches-best-practices-73be89b9a718) makes sense?

We did something similar (switching from NFS to S3). We solved the switch by starting to write/read to S3 and with a fallback read to NFS, if the object was missing in S3. We used kill-switch to exclude S3 all together in the beginning until we where confident that things worked well.

**Comment by ivarconr** [comment]
> I think it would be better to be able to just add a single userId.

Agreed. [HTTP PATCH](https://tools.ietf.org/html/rfc5789) support could be a good fit for this use case. PR welcomed :)

This is related to #220, which also would be a possible solution.

**Comment by ErwinSteffens** [comment]
The thing you described is exactly our use-case and I think your solution would fit our needs. 

Thanks for your suggestion!
