### ISSUE TITLE
NOT instead of ! for negate operator

### ISSUE THREAD

**Issue by Nezz** [Unleash/unleash#4465]
### Describe the feature request

Please consider using NOT instead of ! to indicate the negate operator for the sake of all the non-technical people who think that exclamation mark means that it's important

### Solution suggestions

Quick mockup:
<img width="450" alt="Screenshot 2023-08-10 at 11 07 23" src="https://github.com/Unleash/unleash/assets/431167/aee7ae92-d8e6-4c55-961b-1afb32230b4c">

**Comment by pransh15** [comment]
Hi @Nezz 👋 
Thanks for submitting this request. It's an interesting ask - I'll take it to the Product team and see what they have to say about it. 😄

**Comment by ivarconr** [comment]
@nicolaesocaciu can you please take a look and put it on the UX improvement backlog?

**Comment by sighphyre** [comment]
Marking this as "Maybe later" so the bot doesn't close this
