### ISSUE TITLE
High CPU usage when running on AWS Fargate

### ISSUE THREAD

**Issue by mikefrancis** [Unleash/unleash#4483]
### Describe the bug

Hi there,

We're seeing ~95% CPU usage on a ECS container running on Fargate with the following provision:

```
cpu: 256
memory: 512
```

Is this normal? When updating to:

```
cpu: 512
memory: 1024
```

This goes down to ~80%. We are just wondering if Unleash is by default a CPU hungry app, or we have just not configured our service properly.

Thanks in advance

### Unleash version

5.3.3 (latest docker tag)

### Subscription type

Open source

### Hosting type

Self-hosted

**Comment by ivarconr** [comment]
This is not expected at all. Things to consider:
- how does the log look like? Is it successfully connecting to the database?
- if unleash is running as expected, how much load to it get? If it's hanmered with thousands of req/s that typically takes some CPU to handle.

**Comment by mikefrancis** [comment]
@ivarconr Logs look normal (I think - anything to look out for?), app is successfully connected to the database and the load shouldn't be anything abnormal, this is a site that's getting 100s of visits a day.

**Comment by ivarconr** [comment]
This should be fine, a single Unleash instance should be able to handle that without any problems. 
Is this the official docker image or have you modified it in any way? 

Are you able to inspect, and maybe share your prometheus data? (feel free to share them privately on [slack](https://slack.unleash.run) if it contains sensitive data about your instance). Particular interested in the CPU usage reported by the node.js process, API paths being called and db query times.

**Comment by mikefrancis** [comment]
@ivarconr Thanks for your quick responses. We think we've discovered the issue, our client had been incorrectly configured to have a very short refresh interval. We're rolling out a fix for this and will report back but can probably close this issue afterwards!

Want to make sure this is the case so if others have this problem they can follow our investigation.

**Comment by mikefrancis** [comment]
Yes, this was the case. Closing!
