### ISSUE TITLE
Where to download the latest SDK？

### ISSUE THREAD

**Issue by AlgoYu** [Unleash/unleash#4484]
### Describe the feature request

I use Java language, JDK11, where can I download the latest client SDK? I saw the latest SDK is https://mvnrepository.com/artifact/no.finn.unleash/unleash-client-java/4.4.1 in the warehouse

**Comment by kwasniew** [comment]
```
https://mvnrepository.com/artifact/io.getunleash/unleash-client-java
```

If you want more info about the official Unleash client for Java you can find the details in our docs or the SDK README itself:
* https://docs.getunleash.io/reference/sdks/java#step-1-install-the-unleash-java-sdk
* https://github.com/Unleash/unleash-client-java#step-1-install-the-unleash-java-sdk
