### ISSUE TITLE
improper button layout on sign in page and cookie popup 

### ISSUE THREAD

**Issue by nishaaannnt** [Unleash/unleash#4578]
### Describe the bug

1. The "Next" button on sign-in page is not properly aligned. The width of the button should be full.
2. On visiting the website first time in mobile view the cookie popup has its button misaligned

### Steps to reproduce the bug

1. Just visit the signin page to view the issue
2. Open the website in a new browser to see the cookie popup

### Screenshots

Cookie Popup in Mobile view -
![image](https://github.com/Unleash/unleash/assets/100792085/ecb7b39c-b99f-4133-9c1f-8abc7461d85e)

Sign In page -
![image](https://github.com/Unleash/unleash/assets/100792085/5e0ad9e0-08e7-471a-9bb9-ab4064ebd9c6)

### Subscription type

None

### Hosting type

None

**Comment by aditipatelpro** [comment]
Hi @thomasheartman , I would love to work to this issue? Could you please assign it to me?

**Comment by thomasheartman** [comment]
Hey, @aditipatelpro! I'd be very happy to assign this to you 😄 However, the issue with the cookie popup is on the website, so that's controlled by our CMS and not by this repo. As for the second issue, I'm not entirely sure where that is. Can I get back to you about this on Monday (I'll try and get some info about where this is)? In the meantime, if you find where this is defined, feel free to go ahead and fix the second issue 😄

**Comment by aditipatelpro** [comment]
Hi @thomasheartman, thank you for the update 😄. 
I believe I was able to reach out for this issue only. I never approached for the second issue.
However, could you help me with what labels, on the issues I wish to contribute to, I should be/ should not be looking for?

**Comment by thomasheartman** [comment]
@aditipatelpro Ah, okay, got it! As for labels for certain issues: it might depend on what kind of issues you want to contribute to, but aside from bugs and feature requests, we don't really label our issues very much. What is it that you're looking for?

**Comment by aditipatelpro** [comment]
@nunogois, @thomasheartman  Thank you for your recognition. 😃 
I will keep an eye on the open issues, if anything interests me I will reach out. And I will also reach out to the Slack community.

Thank you for your guidance 🌷.
