### ISSUE TITLE
joi@14.3.1: This module has moved and is now available at @hapi/joi

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash#458]

**Comment by michaellelis-hotmart** [comment]
Any predictions for this issue? I noticed that the hoek@6.1.3 and topo@3.0.3 dependencies follow the same problem. (@hapi/hoek and @hapi/topo).
I also found a stuck PR with part of the solution: https://github.com/Unleash/unleash/pull/511

**Comment by ivarconr** [comment]
Jeah, it seems like the biggest change is related to a major change on how extend works, and it affects this one: https://github.com/Unleash/unleash/blob/980b42fd4a7cf103c98ea6d7183db368c01f46ed/lib/routes/admin-api/util.js

I just haven't had time to prioritize this

**Comment by ivarconr** [comment]
Btw, feel free to contribute @michaellelis-hotmart on #511 or on the other dependencies.

**Comment by michaellelis-hotmart** [comment]
Cool! Can I open PR with my user?

**Comment by ivarconr** [comment]
> Cool! Can I open PR with my user?

Yes of course. It's the beauty of Open-Source.
