### ISSUE TITLE
GCP firestore adapter for DB

### ISSUE THREAD

**Issue by deadletterq** [Unleash/unleash#4588]
### Describe the feature request

Hi there! Would it be possible to have other DBs supported? Specifically, I'm looking for the support of GCP Firestore. 

### Background

Firestore, and similar, is managed by GCP, which makes it very easy for easy to medium-sized projects to use.

**Comment by nunogois** [comment]
Hi @deadletterq - Thank you for raising this issue! I think this is not something we are planning at the moment, but I'll still raise it with the rest of the team just so we're aware that there's interest in this. We'll get back to you!

**Comment by sighphyre** [comment]
Hey @deadletterq, we're pretty tied into Postgres at this point, I'm not even sure this is possible without a major rewrite. So sadly, I don't think we'll be doing this one

I'm going to close this but if you have inputs please feel free to add them in or reopen it if there's things we haven't considered
