### ISSUE TITLE
Strategy to match regex

### ISSUE THREAD

**Issue by Lewiscowles1986** [Unleash/unleash#460]
When looking at a managed offering https://eu.unleash-hosted.com/demo/#/strategies it seems regex strategy is unavailable.

The business I work for already has a feature flag service which includes this. We are looking to standardise our tech stack in some places including the home rolled feature-flags.

Is this something you would be open to a PR on?

**Comment by ivarconr** [comment]
You can extend Unleash with a [custom strategy](https://unleash.github.io/docs/guides/custom_activation_strategy) which support regex. 

One of the biggest challenges by supporting regex is to make it work the same across SDKs spanning multiple languages.

**Comment by Lewiscowles1986** [comment]
So thank you for getting back to me. I didn't mean sending a regex into unleash, but having server-side contain a matcher which uses a server-side submitted regex (one language I hope). Then from a client perspective it's transmitting in the server regex format a string which can be parsed / compiled.

I noticed the extension framework, and had made notes that I thought the match was client-side. Unfortunately with a polyglot stack that would mean either not having feature parity (why we are looking for a feature flag service) or heavy maintenance burden.

Thank you again for your time. Would I be right in thinking that  it's not a good fit and I should close this out?

**Comment by ivarconr** [comment]
> Rather having server-side contain a matcher which uses a server-side formatted (assumption of single language) submitted regex (one language I hope). Then from a client perspective it's transmitting in the server regex format a string which can be parsed / compiled.

This sounds like a possible solution, but there is some complexity in implementing this correctly. 

It would be very helpful for me if you could give some concrete examples / use cases of what you are trying to solve.

**Comment by Lewiscowles1986** [comment]
One of the problems regex allows us to solve for is feature flagging by partial name ahead of time for testing features. `"test-companyname-internal-.*"` resembles a glob match we were performing to feature-flag a new on-boarding experience (without releasing to customers)

We also have customers with more than one account who have customisations of our SaaS multi-tenant platform, and prefix their team name with their company. This makes itself useful without exposing internals of our application to facilitate this in self-service. We add a pattern matching flag on team, alter several flags and it saves everyone time and effort
