### ISSUE TITLE
Not able to enable demo flag in unleash demo environment

### ISSUE THREAD

**Issue by msdinesh07** [Unleash/unleash#4607]
### Describe the bug

Not able to enable 'demoApp.step4' flag for production environment in 'https://app.unleash-hosted.com/demo/projects'.

### Steps to reproduce the bug

Login to https://app.unleash-hosted.com/demo/projects

Search for 'demoApp.step4' flag name.

Try to enable this in prod environment.

### Subscription type

Open source

### Hosting type

Hosted by Unleash

**Comment by nunogois** [comment]
Hi @msdinesh07 - Thank you for reaching out. Could you please clarify what you're trying to achieve? As far as I know the production environment is disabled by default in this project, so everything is working as intended. The demo app and guide should be using the `dev` environment, not `prod`, so you should not need to use this environment for the demo.
