### ISSUE TITLE
Intermittent failures

### ISSUE THREAD

**Issue by Lewiscowles1986** [Unleash/unleash#463]
Every so often I get failures from tests that other times pass. The failures are inconsistent and never output a test case, line number etc

![Screenshot 2019-06-20 at 00 26 07](https://user-images.githubusercontent.com/2605791/59807966-1004c600-92f2-11e9-9820-cce4579bc455.png)

The only thing I can put it down to is how I have my postgres setup (in a docker container), and incredibly poor test runner design that I get no feedback.

![Screenshot 2019-06-20 at 00 28 31](https://user-images.githubusercontent.com/2605791/59808036-64a84100-92f2-11e9-9c37-0c615533049f.png)

the command I'm running (because at first I wondered why it was happening) 

`TEST_DATABASE_URL=postgres://user:password@localhost:5432/unleash_test npx ava -v`

**Comment by Lewiscowles1986** [comment]
😊 `npx ava -v -s` seems to work as well as `npx ava --reset-cache` I've no idea why concurrency harms the tests, nor why resetting cache is an issue

**Comment by ivarconr** [comment]
To make test execution fast we had to make it possible to run tests in parallel. e2e uses a real database (on purpose) and to not have multiple tests hurting each-other we thus use a trick where each test file gets a separate database-schema. This means there is a common setup for all e2e-test where it has to "initalize" the database. 

The experience so far has been that this works well when having postgres installed locally and also have been fairly stable on travis. I suspect a docker based postgres might add some extra latency of some sort and thus hurt performance. It might be that we have to add some extra logic in the `/test/e2e/helpers/test-helper.js`  to account for this. 

Which version of postgres do you use inside the docker container?

**Comment by Lewiscowles1986** [comment]
It's 9.5, but the part that is most annoying is that it passes maybe 1/3rd of the time. I'll checkout that file. The thing I'm working on is picking up the DB independence works, having a move of parts around. If it is postgres then the problem should solve itself.

**Comment by ivarconr** [comment]
solved in #504
