### ISSUE TITLE
Add missing events to Slack Addon

### ISSUE THREAD

**Issue by spgandhi** [Unleash/unleash#4658]
### Describe the feature request

The Webhook addon has more events than the Slack Addon. I am specifically interested in receiving updates about flag variants updates so the team can know when an AB Test configuration changes. 

The Webhook addon has `feature-variant-updated` event, but the same does not exist on Slack Addon. I see some more events that exist on webhook addon but not on slack addon. Would love to see feature parity between the two

### Background

The Product, Data Science and Leadership team is highly interested in knowing when an AB Test is turned on/off or if any configuration changes. So its important to be able to receive slack updates when a feature variant is updated

**Comment by gardleopard** [comment]
Hi, this fixed in https://github.com/Unleash/unleash/commit/523cf87f266cf491a96d1fb12c2c4c2c47ab826e. Unleash 5.4 has this fix.

**Comment by spgandhi** [comment]
Thanks @gardleopard ! Closing the issue 🥂
