### ISSUE TITLE
Weird behaviour on the Metrics tab in admin

### ISSUE THREAD

**Issue by aminix** [Unleash/unleash#475]
Hi,

We are seeing a strange behaviour in the Metrics tab of Unleash.

Facts:
1- We have a feature toggle enabled with a strategy of 100% with a gradualRolloutSessionId for the last 24hrs.
2- This is what our metrics tab show:
<img width="1201" alt="Screenshot 2019-08-06 at 15 38 51" src="https://user-images.githubusercontent.com/755817/62553357-1b428f80-b867-11e9-843b-cfc93f3b4ade.png">

Expected behaviour:
To have just a bit less than a 100% in "Yes" and almost 0 in "No" because it's activated on 100% for the last day.

Actual behaviour:
It's exactly 50% in "Yes" and "No".

Is there something I'm missing? Does this behaviour make sense?

**Comment by ivarconr** [comment]
It all comes down to your session IDs:

- how are they disributred?
- are they always part of the Unleash context?

**Comment by aminix** [comment]
They are distributed through a cookie we assign to every user when they land in the page.

We see the same strange behaviour for the gradualRolloutUserId strategy.

Facts:
1- We have a feature toggle enabled with a strategy of 50% with a gradualRolloutUserId for the last 2 months
2- This is what our metrics tab show:
<img width="1218" alt="Screenshot 2019-08-06 at 16 47 21" src="https://user-images.githubusercontent.com/755817/62554891-e257ea00-b869-11e9-8966-b59bc9764744.png">

Expected behaviour:
Those numbers should be closer to 50%

**Comment by ivarconr** [comment]
Which client SDK and version are you using?
What do you assign as the value for sessionId/userId for the first user request, before the cookie has been assigned?

**Comment by ivarconr** [comment]
> They are distributed through a cookie we assign to every user when they land in the page.

I was thinking of the value distribution. How random are they?

**Comment by aminix** [comment]
Oh, got you.

1- We use uuid/v4 as session id so it's random
2- We always make the request with that uuid, if it's not assigned at request moment, we create it
3- We use the npm package "unleash-client": "^3.2.1"

**Comment by ivarconr** [comment]
I have tried to create a small test for your scenario:
https://github.com/Unleash/unleash-client-node/pull/141/files

To me it looks like the strategy implementation does what it should for percentage=100. 

Is it a problem with the metrics or does the strategy actually resolve to false in 50% of the cases? 

(this issue should probably be moved to unleash-client-node)

**Comment by aminix** [comment]
Thanks for the test! You gave me good insight on where to look for debugging, when I have time I'll check more.

I'll close this, thanks.
