### ISSUE TITLE
Project overview filtering is not saved correctly

### ISSUE THREAD

**Issue by thomasheartman** [Unleash/unleash#4789]
### Describe the bug

When using the project overview table filtering capability, some choices are not persisted properly. This means that when you refresh the page, their default values are back. This applies to the "tags" column and the "environment" columns.

### Steps to reproduce the bug

1. Go to any project with feature flags.
2. Use the project overview column filter to hide *all* optional columns (only "name" should be left)
3. Refresh the page
4. Observe that the "Tags" column and all the environments have been reselected.

### Expected behavior

When you make a choice, I'd expect the filter to save that choice across reloads. Further, I'd expect all columns to act the same way: either all reset or all save. 

### Screenshots

Before reload:

![image](https://github.com/Unleash/unleash/assets/17786332/3d0a22ba-1eba-4c7a-89b6-65ffabbf31e6)

After reload:

![image](https://github.com/Unleash/unleash/assets/17786332/f211fe6c-1ff5-4901-b60f-3d61e924c9ea)

### Unleash version

5.4.0+2455.e568090d (Enterprise)

### Subscription type

Enterprise

### Hosting type

Hosted by Unleash

**Comment by Tymek** [comment]
Fixed in https://github.com/Unleash/unleash/pull/4843
