### ISSUE TITLE
Please can you make constraint values filterable when you are adding/removing them

### ISSUE THREAD

**Issue by lukemorganmadgex** [Unleash/unleash#4860]
### Describe the feature request

I want to be able to filter contstrain values when i am adding/removing them - its so annoying that you can filter them down here: 

<img width="635" alt="Screenshot 2023-09-28 142458" src="https://github.com/Unleash/unleash/assets/120197037/1fdcb51d-cbc1-4cff-982c-03f5d6fa0bff">

but not here: 

<img width="569" alt="Screenshot 2023-09-28 142513" src="https://github.com/Unleash/unleash/assets/120197037/31a28897-b5c6-4aab-85dc-36220d8c06b5">

it's making searching for values to remove a real annoyance.

**Comment by thomasheartman** [comment]
Hey, @lukemorganmadgex! Thanks for raising the issue 😄 I think you have a good point here. I'll take this back to one of our dev squads to see if it's something we can look into in the next few weeks.

But in the meantime: That looks like a whole lot of IDs to put in a single constraint. That's definitely going to make it harder, regardless. If you don't mind, could I make a suggestion? Is there some other way you can group these client properties? Such as a `propertyGroup: "special"` field or something?

It looks like you're using a larger number of special IDs than Unleash was designed for. It'll still work, but it might not be the best way to do it. In fact, we discuss something like this in the documentation on [managing constraints](https://docs.getunleash.io/topics/managing-constraints) (specifically the section on [rethinking your options](https://docs.getunleash.io/topics/managing-constraints#rethinking-your-options)). So it might be worth checking that out and seeing if that can make this situation a little better for you somehow ☺️
