### ISSUE TITLE
[Slack App] Notifications in Slack don't mention segment constraint

### ISSUE THREAD

**Issue by mathroc** [Unleash/unleash#4912]
### Describe the bug

A feature flag was enabled for a few user IDs and someone change it to have a segment constraint. A notification was pushed to Slack to inform us that the feature flag was updated that said:

> [Someone] updated [MyFeatureFlag](https://unleash..../projects/my-project/features/MyFeatureFlag) in project my-project by updating strategy flexibleRollout in production constraints from [userId is one of (x, y, z)] to empty set of constraints

Reading the message make it sounds like it's now enabled for everyone

### Steps to reproduce the bug

1. Add a Slack integration
2. Enabled a feature flag with some constraint on production
3. Remove the manual constraints and add a segment constraint

### Expected behavior

The notification on Slack should be something like:

> [Someone] updated [MyFeatureFlag](https://unleash..../projects/my-project/features/MyFeatureFlag) in project my-project by updating strategy flexibleRollout in production constraints from [userId is one of (x, y, z)] to [segment: my-segment]

### Unleash version

Unleash 5.4.1

### Subscription type

Don't know

### Hosting type

Self-hosted

**Comment by daveleek** [comment]
Thank you for the bug report @mathroc, we'll have a look and get back to you

**Comment by daveleek** [comment]
@mathroc apologies for late reply. We have looked at this and made an improvement, it's merged and available in Open Source Unleash right now. it will be part of the next Unleash Enterprise version release.

It will list changes in referenced segments list with lists of segment ids in slack messages, similar to how userids are represented

**Comment by mathroc** [comment]
that's great, thank you :pray:
