### ISSUE TITLE
feat: Open API documentation

### ISSUE THREAD

**Issue by Lutz-Hilken** [Unleash/unleash#492]
Hi,

would it be possible to offer a swagger document that describes the REST API?
Having this, it would be easy to create additional clients, also for the administrative interfaces.

Thanks!
Cheers, Lutz.

**Comment by ivarconr** [comment]
Yes it's a good idea to document the API endpoints following the Open API specifications. Keep in mind however that most of the complexity in Unleash is implemented in the client SDKs, and thus we have created a test specifications to ensure correct implementation across languages: https://github.com/Unleash/client-specification

**Comment by Lutz-Hilken** [comment]
Yes, I see.
But the client APIs do not cover the administrative calls...
Basically, what I want to do is the ensure, that features, which are used by my code, are available in the unleash database. When our product starts, it should check for the availability of the used features and create (or even remove) features for further use within the Unleash web site.
If the client APIs would offer access to the administrative functions, great! But having a Swagger Doc opens up the way for generating clients for other languages as well...

**Comment by evenh** [comment]
I'm toying with an idea of building a Terraform provider for Unleash. A "live" Swagger/OpenAPI for the administrative API would be very helpful in that regard.

**Comment by gazconroy** [comment]
Hi @Lutz-Hilken 

I'm a technical writer with a good few years under my belt but learning the API documentation 'ropes' at the moment and want to get some real-world examples in my portfolio. 

The existing markdown files for the project provide a great basis for generating an Open API specification. Let me know if you're interested in my lending a hand.

**Comment by ivarconr** [comment]
Hi, @gazconroy,

If you have time and motivation your help would be highly valued. I will be able to provide help on all the details, and will also assist on setting up the the tools required to get started. 

One thing to consider is that all input data is already validated with [joi](https://joi.dev/), and it would be good if it is possible to automate some of the Open API from that? 

How technical are you? How can I best support you getting started?

**Comment by gazconroy** [comment]
Cheers @ivarconr 

As first steps, I'll install the Docker image to get a feel for things. I notice that there are GitHub tools for converting Joi schemas to Open API 3. https://github.com/sdrubolo/joi-to-openapi. 

'Round tripping' isn't so straightforward, or even desirable, but let's generate an initial Open API spec and see where that leads us

**Comment by ivarconr** [comment]
> 'Round tripping' isn't so straightforward, or even desirable, but let's generate an initial Open API spec and see where that leads us

I agree. I think it would be good to get started and see how we can do this in the most efficient matter.

Let me know when/if there is anything I can assist you on.

**Comment by gazconroy** [comment]
I've made a start on building the specification but can you provide some of that Joi data so that I can see how it can be incorporated?

**Comment by ivarconr** [comment]
You can have a look at the feature toggle definition:

https://github.com/Unleash/unleash/blob/master/lib/routes/admin-api/feature-schema.js#L61

Relevant for POST/PUT on `/api/admin/features`.

**Comment by gazconroy** [comment]
As I understand it, this code creates, validates and exports the strategies, variants and feature schemas. Is there some form of ['middleware'](https://www.digitalocean.com/community/tutorials/how-to-use-joi-for-node-api-schema-validation#step-4-%E2%80%94-creating-the-schema-validation-middleware) to generate JSON responses from sample input data? That _would_ be helpful in generating those aspects of the Open API specification.

I'm a humble technical writer, though, so in no may take this as meaning 'I'm about to cobble up some JS to do just that' - I will leave that to wiser heads (who may well say 'Already done...see here').

**Comment by ivarconr** [comment]
> Is there some form of 'middleware' to generate JSON responses from sample input data?

Sort of, all "controllers" will use the shared util to handle the error response, and the code for it is located in [util.js](https://github.com/Unleash/unleash/blob/master/lib/routes/admin-api/util.js#L27-L46). 

In the case of a validation error it will actually just return a `400`with the "joi" error directly as body, and this is today used by the UI to show a proper validation message. Example:

```json
{
	"_original": {
		"name": "",
		"description": "asd",
		"type": "release",
		"strategies": [{
			"name": "default"
		}],
		"enabled": true,
		"createdAt": "2020-11-07T20:49:49.921Z"
	},
	"details": [{
		"message": "\"name\" is not allowed to be empty",
		"path": ["name"],
		"type": "string.empty",
		"context": {
			"label": "name",
			"value": "",
			"key": "name"
		}
	}],
	"isJoi": true
}
```

In the case of a name conflict there will be a more direct error message:

```json
{
	"isJoi": true,
	"name": "NameExistsError",
	"details": [{
		"message": "An archived toggle with that name already exist"
	}]
}
```

I must admit though that this is probably an area where we could improve though. From your experience it would be good to get a feedback on how we can standardize this a bit more.

**Comment by gazconroy** [comment]
If the will in the project exists, an interactive specification document like Swagger UI will certainly help that API standardisation: terminology, naming conventions, completeness and the like.

**State of play**

I've built a partial model of the API and am ready to tweak and test things out before expanding further.

**However, a bit of help is needed here....**

Things seem to be working correctly in that the example scripts from the SDK are pulling in events from the server. However, I'm struggling to get the Open API tools to authenticate. In an attempt to 'debug' the issues, I tried Postman with similar results:

`{"type":"unsecure","path":"/api/admin/login","message":"You have to indentify yourself in order to use Unleash."}`

I've pumped what seems to be the correct Oauth2 authentication details into Postman (localhost callback URL, client ID and secret, email scope, and so on) but the curl output is 

`curl --location --request GET "http://localhost:4242/api/admin/archive/features" --header "Authorization: Bearer [ACCESS TOKEN]" --header "Cookie: unleash-session=[COOKIE NAME?]; unleash-session.sig=[COOKIE.VALUE?]"`

I'm guessing Postman grabbed those session cookie strings during its access token creation process (since I had no hand in their generation).

If I can get Postman to work, I reckon I can figure out how to get Swagger UI to behave!

**Comment by ivarconr** [comment]
> However, I'm struggling to get the Open API tools to authenticate.

I guess you are sing the built-in "unsecured" authentication where you need to provide an email? This one is not really intended to be used in a real setup, and rather replaced with some custom authentication mechanisms (we plan to improve this in v4x). 

In hindsight I see that we should have the "unsecure" authentication mechanism to also accept some form of simple "basic auth" just to make API based integration easier. I believe this should be pretty simple, I will look in to this and see if I can easily extend the current implementation with this. 

In the meantime you can actually disable authentication all together by setting the following environment variable:

`ADMIN_AUTHENTICATION=none`

This will disable authentication all together and should allow you to verify

**Comment by evenh** [comment]
> I guess you are sing the built-in "unsecured" authentication where you need to provide an email? This one is not really intended to be used in a real setup, and rather replaced with some custom authentication mechanisms (we plan to improve this in v4x).

Related to this, is there any plans to support a set of "fixed" auth mechanisms out of the box (+ support pluggable auth)? As mentioned, I'm toying around with a Terraform provider for Unleash and being so flexible in auth-mechanisms is certainly a challenge.

**Comment by gazconroy** [comment]
That sounds like a valuable addition.

Non-programmer getting stuck again...I'd optimistically hoped that changing the _options.js_ line from

`adminAuthentication: process.env.ADMIN_AUTHENTICATION || 'unsecure'`

to

`adminAuthentication: 'none'`

would have switched the server's mode to 'no authentication' but that doesn't appear to be the case. Feedback from GET requests still indicates it is in 'unsecure' authentication mode.

What's the correct, simplest method for setting this environment variable?

**Comment by ivarconr** [comment]
If you are using [unleash programatically](https://unleash.github.io/docs/getting_started.html#2-or-programmatically) you can send in this option to the start method.:

```js
unleash.start({
    databaseUrl: 'postgres://unleash_user:password@localhost:5432/unleash',
    port: 4242,
    adminAuthentication: 'none',
});
```

if you are using it via docker the easiest would be to set the environment variable: 

```
docker run -d -e ADMIN_AUTHENTICATION=none \ 
-e DATABASE_URL=postgres://user:pass@10.200.221.11:5432/unleash unleashorg/unleash-server

```

**Comment by gazconroy** [comment]
I'm not getting any joy with Docker. The image falls over after a few seconds:

![docker issues](https://user-images.githubusercontent.com/26181682/98806317-e9788b00-2410-11eb-8222-fead8bb9dc15.png)

Running programmatically, and forgive me for being so basic but:

- Replacing the contents of unleash.js with the provided code and running the unleash command (`unleash -d postgres://unleash_user:password@localhost:5432/unleash -p 4242`) does not change the result (unsecure authentication)
- Attempting to load unleash.js directly into node throws up errors (I realise this is likely not the right thing to do but. as you may have guessed, I don't know what the right way is)

![node load](https://user-images.githubusercontent.com/26181682/98808315-cd2a1d80-2413-11eb-946f-00c8225fa13b.png)

**Comment by ivarconr** [comment]
Can we connect on slack @gazconroy ? I have some time in about 1 hour.

**Comment by gazconroy** [comment]
Sure. I may not be at my desk then but will have my phone with me. Contact me on Slack so that we can set a mutually acceptable time.

My Slack member ID is U01DZQUVCMC

**Comment by gazconroy** [comment]
I've made some commits into PR 652. It's a 'heading towards complete' version of the Open API specification.

I have a few questions and would be grateful for feedback on them:

**200 responses**

*Most* return a version number as the first part of the response. What is this version number?

Most responses also contain a *variants* object. In this object, there is a 'weight' item. How does Unleash use weighting to determine which variant to use? What is the range of numbers that can be entered here?

**/admin/metrics/applications** and **/admin/metrics/seen-apps**

In the response:

- *url* - Is this a link to more information about the application? Must the url be relative?
- *color* - Is this the colour of the URL link? What is the format? Hex-coded? # prefix?
- *icon* - Is this the icon to use for the link? Is it a url, too? Relative?

**/admin/metrics/applications/{appName}**

In the response:

- *lastSeen* - Is this the last time that the application accessed Unleash?
- *createdAt* - Is this when the application was created?
- *links/self* - What is this? The relative location from where the application runs? This doesn't seem to match file structure, though: if I run simple-usage.js from /examples, this reports */api/applications/my-application*

**get /admin/events**

In the response:

- *id* - Is the event number (for all events on the Unleash server?). Resets to 0 when the server is shut down?
- *CreatedBy* - Is this the name of the application's creator? Where is this data taken from?
- *diffs* - What are diffs? A list of modifications to a Feature Toggle?
- *diffs/kind* - What do these letters signify? What's the full list?
- *diffs/paths/pathItem* - What do these paths signify?
- *lhs* ansd *rhs* - Sometimes boolean, sometimes an object, sometimes null. What are they?

**get /admin/feature-types**

In the response:

- *lifetimeDays* - What does this mean and which Feature Toggle types does it apply to?

**Comment by sgebb** [comment]
I want to generate a client for smalltalk, so I really need a functioning openapi-spec. I'm not sure that manually writing it based on a users understanding of the API is a good idea, shouldn't this just be generated by the server using a tool like swashbucle or nswag?

**Comment by gazconroy** [comment]
You make some good points,  @sgebb, some of which I was going to raise myself.

**What should the Open API specification (OAS) be used for?**

Apologies for what may seem basic queries but I believe the questions I'm asking _should_ be asked since one of the several things an OAS does is 'sell' the API to people at all levels. [It's not necessarily just a code generating tool, it's not just a [quick reference guide.](guide.](https://blog.restcase.com/openapi-documentation-and-beyond/)

@sgebb  is suggesting a code-first as opposed to an [API first](https://apisyouwonthate.com/blog/api-design-first-vs-code-first) strategy. This is entirely valid but I'd suggest still answering those awkward questions that pesky users have.

**My next steps**

I'll push another commit today with a few extra tweaks, a Redocly output and some general additional documentation suggestions.

After that, I will put Unleash on my back burner until there's consensus about where the OAS aspect is heading.

**Comment by sgebb** [comment]
@gazconroy Don't get me wrong I'm very thankful of what you're doing. I'm gonna attempt using it, at least until an official version comes out. I'm not really saying that it should be code-first, but since Unleash is a basically finished product then the code is clearly already written. Writing an API-spec manually after the product is made seems very backwards to me. What happens when the API evolves, are we supposed to manually update the spec with future changes?

**Comment by gazconroy** [comment]
@sgebb I'm glad you raised the point - it needed saying. It's a good insight into Unleash for me.

It's the age-old (!) dilemma: how and who updates the docs when the code changes? Either in-code (embedded markup), alongside code (NSwag) or outside code (the OAS directly). 

In a way, the tool doesn't matter because the documentation still needs to be written by someone. The answer to the question depends on the workflow and responsibilities in the team.  Happy to help out, whatever the case, but I think I should put my 'direct into OAS' efforts on pause for now (until wiser heads decide on what to do next).

**Comment by ivarconr** [comment]
> I want to generate a client for smalltalk, so I really need a functioning openapi-spec. I'm not sure that manually writing it based on a users understanding of the API is a good idea, shouldn't this just be generated by the server using a tool like swashbucle or nswag?

This is the end goal @sgebb. But I think the first step here, implemented by @gazconroy is a fantastic first step in to how this should be. There will be a lot of value from this "manual" work that we can incorporate in a more automated generated solution later. Generating the definitions for Unleash is currently not straight forward as we use a combination of express, custom controllers and joi for schema validations. For the next version of Unleash we plan to look in to improving this, and standardizing a bit more on a framework, and [fastify](https://www.fastify.io/) is a strong candidate for this. 

I also must add that a client SDK will usually only touch a small subset of the full API, and much of the work is actually implemented in the SDK itself to make it scale. You can read a bit more on the high level details in the [client specifications](https://unleash.github.io/docs/client_specification), we even have a [client specifications project](https://github.com/Unleash/client-specification) to help verify the client SDK implementation.

**Comment by ivarconr** [comment]
@gazconroy I will answer your question here:

> Most return a version number as the first part of the response. What is this version number?

It is used if we need to break something, and guides the SDK to do correct parsing. I think we only utilized this once (and we might change this in the future.)

> How does Unleash use weighting to determine which variant to use? What is the range of numbers that can be entered here?

This is used by the client SDK. The weight needs to be a number between 0 and 1000 according to the [variant schema](https://github.com/Unleash/unleash/blob/master/lib/routes/admin-api/feature-schema.js#L32). The client SDK will summarize all variant weights and hash the number and divide the users among them. The distribution will be according to the weight as a fraction of the sum of weight. 

**/admin/metrics/applications and /admin/metrics/seen-apps**
- url - This is an absolute url to the actual application (optional, ex: http://someapp.internal.url)
- color - this is actually a deprecated property. It is not used anymore. 
- icon - This is a string name. It must be a valid name in the list from [material design icons](https://material.io/resources/icons/?style=baseline)


**/admin/metrics/applications/{appName}**

In the response:
- lastSeen - Is the last time the application talked to unleash (sent metrics, registered, fetched toggles). 
- createdAt - Is the first time the application registered with Unleash.
- links/self - Deprecated, I think we can remove this property. 


**get /admin/events**

id - All event have a unique id. Will increase for ever (a sequence in db) 
CreatedBy - this is the username for the current user. It is taken from the User object on the current 
session. Can either be an "email" or a "username". 
diffs - This is the computed json diffs from the current version and last version of the feature toggle, using [deep-diff](https://www.npmjs.com/package/deep-diff#differences)
diffs/kind - See [deep-diff](https://www.npmjs.com/package/deep-diff#differences)
diffs/paths/pathItem - See [deep-diff](https://www.npmjs.com/package/deep-diff#differences)
lhs ansd rhs - see [deep-diff](https://www.npmjs.com/package/deep-diff#differences)


**get /admin/feature-types**
lifetimeDays - It is the number of days the toggles of this days is intended to be used. We utilize this information to issue deprecation notices. See https://unleash.github.io/docs/feature_toggle_types for more details.

**Comment by gazconroy** [comment]
In the latest PR, I've added the client API calls. A couple of questions, though:

For GET /client/metrics, the existing markdown says: _'Register a metrics payload with a timed bucket.'_

- **Timed** - There's a start and stop time here. I'm guessing this is a 'window' to observe the metrics
- **Payload** - This seems to be a 'yes' or 'no', each with an associated number. Does this mean the number of times the feature toggle was enabled (yes) or disabled (no) within the time period. Is the number an input parameter? If so, what is the significance of that?

In the client variants schema (200 response for GET /client/features):
- What are the various **weight** types and what do they do?
- Is there a finite list of **types** for the payload (or is that entirely client-dependent)?

**Comment by ivarconr** [comment]
> Timed - There's a start and stop time here. I'm guessing this is a 'window' to observe the metrics

Correct. This is the time period the sdk have used to observed these metrics. 

> Payload - This seems to be a 'yes' or 'no', each with an associated number. Does this mean the number of times the feature toggle was enabled (yes) or disabled (no) within the time period

The SDK will count each time a feature toggle was requested and if it evaluated to enabled (yes) or disabled (no). It will count within the defined time period. 

Every time metrics are sent to the server the client SDK starts a new metric bucket.

**Comment by ivarconr** [comment]
> What are the various weight types and what do they do?

Weight is just a number between 0 and 1000. The SDKs shall distribute the allocation to each variant according to the relative weightings as a fraction of the sum of all variant weights. 

Some examples;
- 4 variants with all having weight '1000' means that the traffic should be spread equally, meaning 25% each. 
- 3 variants with 100 and one with weight=900 means that 90% (900/1000) should go to the variant with 900.

> Is there a finite list of types for the payload (or is that entirely client-dependent)?

No, it can i theory be anything, and up to the user. It UI currently supports json, csv, text. But there are also customers using the API directly for this, and we are not limiting what the payload can be.

**Comment by ivarconr** [comment]
http://unleash.herokuapp.com/oas/
