### ISSUE TITLE
Export/import whole toggle configs between unleash instances

### ISSUE THREAD

**Issue by roligheten** [Unleash/unleash#496]
A task I often find myself doing when using Unleash is creating the same toggle on dev/prod/staging environment. How I usually do this is keeping two/three tabs of Unleash and copying first name, then description, and finally setting strategy manually. This is a bit tedious and it would be cool if I could simply "copy" a whole Unleash toggle and "paste" it into another instance of Unleash (name, description, strategy in one go)

One way this could be achieved is an "export toggle" button which copies a serialized version of the toggle to clipboard, when this is pasted into either a special "import toggle" dialog or simply in one of the fields (name/description) of "new toggle" screen, the whole config is copied over.

It is a pretty small feature but I think it would be a good way of reducing friction for developers working with Unleash :slightly_smiling_face:

**Comment by ivarconr** [comment]
yes PR welcome. 

I would like to add that this is primarily an issue with how you have set up Unleash in your org. E.g. Unleash-hosted is set up such that it works across all environments and you can constrain strategies based on environment.

**Comment by zivyatziv** [comment]
> I would like to add that this is primarily an issue with how you have set up Unleash in your org. E.g. Unleash-hosted is set up such that it works across all environments and you can constrain strategies based on environment.

This does not cover DR scenarios though.
I believe that there should be a "dummy Unleash" for "games" or "development" purposes and one for actual production use.


@Catuna 
You could always do it with API calls, you can extract data from `/api/**client**/features` and then post to `/api/**admin**/features/` (note the admin-api requires authentication)

**Comment by ivarconr** [comment]
You also have the import/export API for this:

https://unleash.github.io/docs/import_export

**Comment by Lolchek-R** [comment]
@ivarconr In this import/export API usage doc it says a lot of times `You should never use this in production environments.` and I have trouble to understand the context in which it is said. Does that sentence mostly addresses the case of using `drop` option or the whole importing of feature toggles through the API?

**Comment by ivarconr** [comment]
Yes, that sentence is mostly about dropping existing toggles. Which can be quite stupid as it will overriding everything.
