### ISSUE TITLE
SSL enabled with DATABASE_SSL=false

### ISSUE THREAD

**Issue by mortenmj** [Unleash/unleash#498]
When using the DATABASE_* variables introduced with #437, the value provided to DATABASE_SSL is ignored, and SSL is always enabled. This results in an error during startup, stating "The server does not support SSL connections."

Expected behavior would be to disable SSL if the variable is not set, or if set to false. Currently, using Postgresql without SSL requires use of the DATABASE_URL variable.

Ref Postgresql documentation (https://jdbc.postgresql.org/documentation/head/connect.html):

> ssl = boolean
> Connect using SSL. The driver must have been compiled with SSL support. This property does not need a value associated with it. The mere presence of it specifies a SSL connection. However, for compatibility with future versions, the value "true" is preferred. For more information see Chapter 4, Using SSL.

**Comment by ivarconr** [comment]
Thanks, you are absolutely right.

**Comment by ivarconr** [comment]
fixed as part of https://github.com/Unleash/unleash/pull/577
