### ISSUE TITLE
Unable to disable api tokens in v5

### ISSUE THREAD

**Issue by dodgerbluee** [Unleash/unleash#5087]
### Describe the bug

I'm trying to upgrade a v3 version of unleash to v5. I don't want to move all my application client sdks at once, and was hoping to disable the api token requirement until a later date. Maybe I'm reading into this wrong, but when I try to use authentication.enableApiToken or env. AUTH_ENABLE_API_TOKEN via https://docs.getunleash.io/reference/deploy/configuring-unleash, I still can't unleash without unauthorized messages.

### Unleash version

5.5.6

### Subscription type

Open source

### Hosting type

Self-hosted

**Comment by sjaanus** [comment]
Hey @dodgerbluee,

Thanks for reaching out! 

I've just tested the environment variable `AUTH_ENABLE_API_TOKEN` on my end, and it seems to be functioning correctly. When I access `/api/admin/projects` without an API key, it promptly returns my projects.

To better assist you:

1. Could you specify which API endpoint you are trying to hit when you receive the unauthorized message?
2. Are you making a direct call to this endpoint, or are you seeing this error through one of the SDKs?
3. Any additional information or context would be invaluable in helping us identify and address the issue.

Looking forward to your response, and I'm here to help!

**Comment by sighphyre** [comment]
Hey @dodgerbluee, if I'm reading your question correctly, this is about API keys and SDK clients. Unfortunately, there isn't really a way to do this with v4/v5 because Unleash expects to be able to work out what environment the SDK is requesting, which is part of the API token

**Comment by dodgerbluee** [comment]
> Hey @dodgerbluee, if I'm reading your question correctly, this is about API keys and SDK clients. Unfortunately, there isn't really a way to do this with v4/v5 because Unleash expects to be able to work out what environment the SDK is requesting, which is part of the API token

There isn't a way to only provide the first part of the api key? Since I am are migrating, its all under default

**Comment by sjaanus** [comment]
Hi @dodgerbluee! 😊

Unfortunately, we need the entire API key for it to work correctly.
