### ISSUE TITLE
Ensure, that toggles are available

### ISSUE THREAD

**Issue by Lutz-Hilken** [Unleash/unleash#509]
Hi,
we are planning to use Unleash within our product. It fits pretty good so far... ;-)
But now, what I want to do is:
I define my toggles as an enumeration in the code, so the set of toggles is known from the beginning. This gives me some kind of "static" control over the used features.
Now, when I start my application server, I would like to check the availability of toggles in the Unleash server/db and to create/reactivate toggles for easy configuration later on.
I've implemented a small REST client, that does that work. Creation of toggles works fine, but a second run in turn fails with a 400 - BadRequest, instead of some useful status. 
Is this done by intention?
Thanks!
Cheers, Lutz

**Comment by ivarconr** [comment]
Unleash-server api will return 400 if you try to create a toggle which already exists. 

Do you know that unleash will display unknown toggles under the "Application" view for your application? 

https://tech.finn.no/images/2017-03-10-unleash-your-features-gradually/8_undefined_toggle.png
![image](https://user-images.githubusercontent.com/158948/66387342-12378100-e9c4-11e9-8c89-609c08768013.png)


Would this solve your use case?

**Comment by Lutz-Hilken** [comment]
The documentation told me this regarding existing toggles:

> Used by the admin-dashboard to create a new feature toggles. The name must be unique, otherwise you will get a 403-response.

Did not now that unknown toggles are shown for applications. Thanks for the tip. But I would like to have a complete configuration when the application starts. This makes live easier for our application support team...

**Comment by ivarconr** [comment]
Yes your right, the logic changed at one point from 403 to 400. 

It is probably more correct for the api to return 403 in this scenario, as the data is valid, but still not possible because of server side constraints.

**Comment by zivyatziv** [comment]
There's a couple approaches I'd suggest.
a. You could get from `/api/client/features` the list of all the features, then iterate through the JSON and basically make a dedup array of the features you wish to create.
b. You could parse the error message that you get on your **application server,** it is supposed to be 'A  toggle with that name already exist'
[Link](https://github.com/Unleash/unleash/blob/master/lib/routes/admin-api/feature.js#L74)
c. You can alter the unleash/lib/routes/admin-api/feature.js file ([feature.js](https://github.com/Unleash/unleash/blob/master/lib/routes/admin-api/feature.js)) and create a method that creates a bulk of features, and ignores if you have an "already exists" error, I would use the already existing methods like `await this.featureToggleStore.hasFeature(**name**);`. You can see a proper usage here: [Link](https://github.com/Unleash/unleash/blob/master/lib/routes/admin-api/feature.js#L71)

**Comment by Lutz-Hilken** [comment]
Hi,
thanks for the reply!
I voted for a.), as this makes most sense from my point of view.
An additional method would be fine, but I don't want to change the "official" release... ;-)
Cheers!

**Comment by batjko** [comment]
Technically, though, if the toggle already exists, the creation should fail with 409 (conflict), rathe than invalid request or even unauthorized, which could be quite misleading.
