### ISSUE TITLE
fix: Logout should not be xhr call

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash#520]
Today the "logout button" in the UI ends up doing a XHR call to `api/admin/user/logout`. This works fine if logout is as simple as clearing the session and/or deleting cookies. 

Sometimes it also requires a "redirect-flow" to logout from the auth-services as well. 

Therefore it would be beneficial if logout was a regular HTTP call to a logout endpoint (e.g. `/logout). This would allow custom handling of logout by the use of a pre-route handler.

**Comment by goober** [comment]
We are using Openshift's Oauth Proxy and can see that this change would benefit our use case

**Comment by ivarconr** [comment]
Thanks of letting me now, will try to have fix on this soon!

**Comment by goober** [comment]
Hi @ivarconr 

Just want to check if there are any planned work on this issue? 

Otherwise I maybe can squeeze it in and see it I can get it to work

**Comment by ivarconr** [comment]
Sorry, I have had my focus other places, and this has not been critical to our setup. If you have some time to look at it would be awesome, I've be happy to guide you, should not be that hard actually. 

Feel free to [join our slack](https://join.slack.com/t/unleash-community/shared_invite/enQtNjUxMjU2MDc0MTAxLTJjYmViYjkwYmE0ODVlNmY1YjcwZGRmZWU5MTU1YTQ1Nzg5ZWQ2YzBlY2U1MjlmZDg5ZDRmZTMzNmQ5YmEyOGE) if you need some more interactive discussions.
