### ISSUE TITLE
Build Generic Strategy

### ISSUE THREAD

**Issue by juancgalvis** [Unleash/unleash#529]
Unleash is for me the feature flags open source project most important with an wide support of programming lenguages, but I think that exists one special limitation to use it in production environments. The limitant is the strategies concept, because if I want to use a custom strategy, I should implement it on my client, so I am not be able to modify my feature flag settings because the strategy needed does not exists on all my clients. I suggest you a generic strategy wich be evaluated also on client side. This strategy can have many rules of type: attribute <-> operator <-> value for example: (age > 18) && (city == Medellin) 

if the issue is approved, I will start to implement and send a pull request with the migration to create the strategy and start with client implementation for java, nodejs ...

**Comment by juancgalvis** [comment]
Sorry Duplicated with #442

**Comment by ivarconr** [comment]
#442 is part of unleash-enterprise offered as part of https://unleash-hosted.com/
