### ISSUE TITLE
[Question] Usage on browser/mobile apps

### ISSUE THREAD

**Issue by kceb** [Unleash/unleash#532]
I noticed that the SDKs are mainly written for the backend, which is secure, and where I plan on doing the majority of my feature flagging. 

Is it not recommended to use something similar on the frontend? Say I only want a certain number of beta users to see a tab on the menu, what would be the recommended way to handle that?

I could add an attribute to the user returned in the API call that says they are able to see that tab, but I don't want to go down this route unless I have a good reason to.

Is there a lack of client-side (browser/mobile app) SDKs mainly because of security issues involved with storing the Unleash API token on the client?

**Comment by ivarconr** [comment]
You generally do not want to expose all the internal toggle configuration to all your users. The browser always operates in the context of a single user. 

Unleash-hosted, the enterprise offering, has solved this by introducing the unleash-proxy, please see
 https://www.unleash-hosted.com/articles/the-unleash-proxy

It also have a lightweight [client for the browser](https://github.com/unleash-hosted/unleash-proxy-client-js)

**Comment by ivarconr** [comment]
For reference the proxy is now Open-Source;
https://docs.getunleash.io/sdks/unleash-proxy
