### ISSUE TITLE
Feature request: Allow spaces/special chars in application names

### ISSUE THREAD

**Issue by itssimple** [Unleash/unleash#534]
We just started using Unleash on a small scale in a project where we pass all our end customers logins from, so we can (per application), shut down the login when we need.

A problem that we noticed with this approach is that the application names are not escaped on the server, so we cannot set custom icons, links or colours on applications with space (`%20`) and plus (`+`).

Version: 3.2.20

**Comment by ivarconr** [comment]
Thanks for reporting, this needs to be fixed ;)

**Comment by ivarconr** [comment]
I have looked in to this, and the current issue is that we require the appName to be URL-friendly in the [current schema](https://github.com/Unleash/unleash/blob/master/lib/routes/admin-api/metrics-schema.js#L10). It might not be necessary to require it to be url-friendly as long as it is url-encoded when it appears on the URL. I will do some testing, just to verify it does not bring other errors removing this requirement.

**Comment by itssimple** [comment]
If it breaks stuff, I'll just wrap my code to make my input URL-safe, already done that for the feature-flags, because those also break if they contain spaces or plusses (and possibly other special characters, that isn't allowed in it's raw form in a URL)
