### ISSUE TITLE
Removing a custom strategy that is assigned to a toggle causes error

### ISSUE THREAD

**Issue by ryexley** [Unleash/unleash#535]
Unleash Hosted v3.2.20

Steps to reproduce the issue:

1. Create a new custom strategy
1. Assign the new custom strategy to a feature toggle
1. Delete the new custom strategy (note, delete it _while it's still assigned_ to a toggle)
1. Try to open the toggle that the deleted custom strategy is assigned to

Result: I see a blank page rendered. Seems there is a failure rendering the feature toggle page for toggles that have custom strategies that have been deleted assigned to them.

**Comment by ivarconr** [comment]
thanks. I can verify this bug. The current workaround seems to be to recreate the strategy, remove it from the toggles, then create the strategy again.

**Comment by ryexley** [comment]
@ivarconr agreed, that was how I fixed it as well. I re-created the strategy, _then_ browsed back to the feature toggle again, removed the strategy from the feature toggle, and then went back and removed the custom strategy again.

**Comment by ivarconr** [comment]
Fixed in 1ed0657ce8c6e2af235b954dcfa578146896aea6 and will be released as 3.2.21
