### ISSUE TITLE
Include environment in token info for "Confirm deletion"

### ISSUE THREAD

**Issue by snosratiershad** [Unleash/unleash#5444]
### Describe the feature request

As you may create different tokens for different environment its good idea to include token environment here:
![image](https://github.com/Unleash/unleash/assets/66680742/362c7bfd-3efb-45f2-b452-e90fba210c0b)

**Comment by FredrikOseberg** [comment]
Thanks! We'll add this as a potential enhancement. Also, if you'd like to contribute this to the project feel free to setup a PR that includes this info in the deletion screen.
