### ISSUE TITLE
Securing Unleash

### ISSUE THREAD

**Issue by kceb** [Unleash/unleash#557]
I've gone through the examples here: 

https://github.com/Unleash/unleash/blob/master/docs/securing-unleash.md

to set up auth and I played around with the heroku app that has Google OAuth set up. I'm curious what purpose this authentication serves if anyone with a Google account can sign in. Is the server intended to only be accessible within a private VPC/network or is there an expectation to extend the [examples](https://github.com/Unleash/unleash/blob/master/examples/google-auth-hook.js) with custom logic that checks for specific emails?

Thank you

**Comment by ivarconr** [comment]
You need to implement user-management and/or api-access yourself in Open-source. 

This comes out of the box with [Unleash-hosted](https://www.unleash-hosted.com/open-source).
