### ISSUE TITLE
Feature Request: Helm chart

### ISSUE THREAD

**Issue by evanstucker-hates-2fa** [Unleash/unleash#559]
I deploy everything to my Kubernetes clusters using Helm charts. I was unable to find a Helm chart for unleash. Is someone working on one already, or should I create one?

**Comment by ivarconr** [comment]
Maybe it should be part of this one? https://github.com/Unleash/unleash-docker

**Comment by ivarconr** [comment]
https://github.com/unleash/helm-charts
