### ISSUE TITLE
admin ui does not warn when forgetting to hit update

### ISSUE THREAD

**Issue by AndreasChristianson** [Unleash/unleash#561]
The admin ui is a spa with an application state. If you forget to hit "Update" when changing a feature toggle, the spa tracks the change as if it had been made. 
Example:
1. change a feature toggle's activation settings
2. forget to click update
3. navigate to other pages within the app
4. navigate back to the feature toggle activation settings
5. the settings seem to exist there, but have not actually persisted.

![Screen Recording 2020-02-19 at 10 38 43 AM mov](https://user-images.githubusercontent.com/33329956/74854538-1629c700-5305-11ea-8b90-54551927b71b.gif)

**Comment by ivarconr** [comment]
thanks, I agree that this is not optimal. Will put it on our roadmap.

**Comment by ivarconr** [comment]
Fixed in `3.8.0`, unsaved changes are now cleared.
