### ISSUE TITLE
Is it possible to use AWS Secret Manager to connect AWS RDS  in Unleash

### ISSUE THREAD

**Issue by vkatoch2000** [Unleash/unleash#563]
Is it possible to use AWS Secret Manager to connect AWS RDS  With AWS secret manager

AWS secret manager support key rotation

**Comment by ivarconr** [comment]
Currently not supported by Unleash service. A SQL proxy running locally could solve it for you. 

For Unleash to support this we would need to introduce a function options used to resolve the correct password and expiration checks and use this when configuring db-connections in knex.

**Comment by ivarconr** [comment]
https://aws.amazon.com/rds/proxy/
