### ISSUE TITLE
black-duck binary analysis found security vulnerabilities 

### ISSUE THREAD

**Issue by OlegGerber** [Unleash/unleash#5637]
### Describe the bug

black-duck binary analysis found security vulnerabilities for image unleashorg/unleash-server:5.6.9
more details with full analysis log can be found on security issues tab:
https://github.com/Unleash/unleash/security/advisories/GHSA-cvcf-ccr7-fwcq

Please advice if this issue are real or can be triaged.
Thanks in advance.

### Unleash version

5.6.9

### Subscription type

None

### Hosting type

None

**Comment by thomasheartman** [comment]
Hi, @OlegGerber! Looks like @ivarconr already responded to the issue. From a quick glance, that seems to cover everything, but I'll follow up to see if there is anything else we need.

**Comment by ivarconr** [comment]
Security findings addressed in latest v5.7 patch.

**Comment by OlegGerber** [comment]
Many thanks for your support.
I scanned the new image and it looks significantly better, most of the issues are resolved.
I opened a new security issue for the leftovers. See below: https://github.com/Unleash/unleash/issues/5754
