### ISSUE TITLE
Default Variants

### ISSUE THREAD

**Issue by bailejl** [Unleash/unleash#566]
I recently used Unleash to create a demo project of feature flag use cases.  Instead of building strategies of the various uses cases, I explicitly declared which user got which variant.  Some of my use cases would be easier with the proper strategy or with default variants.

It would be nice to declare a default variant when the flag is on and off.  Then the consumer would only have to consumer itself with the variant.  Just an idea for an enhancement.

Also, here is a link to the feature flag demo.  I plan on using it in the future for a local meet up.  https://github.com/bailejl/feature-flag-demo

**Comment by ivarconr** [comment]
Thanks for sharing. 
Not a bad idea to have a default variant for on/off.
