### ISSUE TITLE
feat: Clean shutdown of server

### ISSUE THREAD

**Issue by 0x203** [Unleash/unleash#570]
First of all: thanks for working on this project and making it accessible to us!

### Context

We are starting the unleash server in the same process as our backend server, using `unleash.start()`.
When we receive a SIGINT or SIGTERm, we want to shutdown cleanly so that node exits on it's own because of an empty event loop.

### What we tried

Our current attempt to do this boils down to this:

```js
const { server } = await unleash.start({...});
whenShuttingDown(server.close);   // this registers a handler that get's executed when we get a SIGTERM
```

This successfully closes the server and releases the port etc. However, we found that the DB pool is still active and keeping connections open.

### Question / Request

Is there a way to programmatically close the DB pool again? Or, more broadly speaking: to "restore" to the state before `start()` was called?
Like this:

```js
const { server, db } = await unleash.start({...});
whenShuttingDown(server.close);   
whenShuttingDown(db.end);   
```

or

```js
const unleashServer = await unleash.start({...});
whenShuttingDown(unleashServer.shutdown);
```

or 

```js
const { app, server } = await unleash.start({...});
const db = app.get("config").db;
whenShuttingDown(server.close);   
whenShuttingDown(db.end);   
```

or ...?

**Comment by ivarconr** [comment]
Ooh, thanks for this great question. 

You can get a hold of the knex db-pool via `stores.db` return from unleash.start().

From this you should be able to shutdown the db connection. But this would not be enough, as there are internal timers in unleash as well. 

I purpose that we should add a stop() method returned from the start() method, and unleash should make sure to clean up everything for you.

**Comment by 0x203** [comment]
Thanks for this answer!

[Reading the code](https://github.com/Unleash/unleash/blob/master/lib/server-impl.js#L61-L64), it seems `stores` is not directly returned by the `start` function. However, you set me on the right track and I could get it (seemingly) working for now with this:

```js
const { server, stateService } = await unleash.start({...});
whenShuttingDown(server.close);   
whenShuttingDown(stateService.config.stores.db.destroy); 
```

This works on a "clean" server, so one that never got a request from a client. I guess the timeouts you mention aren't created in that case.

I like you proposal to have a `stop` method, it would a clean solution for this. My code example above is too much relying on internals, I think. Also, it misses the timeouts.

**Comment by dezitter** [comment]
I will submit a PR today for this issue 👍

**Comment by ivarconr** [comment]
Wow, cool. Let me know if you need assistance!

**Comment by dezitter** [comment]
Thanks @ivarconr! Please have a look at https://github.com/Unleash/unleash/pull/665.

**Comment by 0x203** [comment]
Thanks you very much!
