### ISSUE TITLE
Get Features API does not return description

### ISSUE THREAD

**Issue by Tymek** [Unleash/unleash#5740]
### Discussed in https://github.com/orgs/Unleash/discussions/5724

<div type='discussions-op-text'>

<sup>Originally posted by **ianbbqzy** December 21, 2023</sup>
We are using https://docs.getunleash.io/reference/api/unleash/get-features to fetch a list of features. The response body mostly matches the schema as advertised, except that there is no "description" field. We verified that most of our features have descriptions, so I'm wondering if there is a bug on the server end.

E.g. this is the response that I get back
```
{
    "version": 2,
    "features": [
        {
            "type": "fake-type",
            "name": "fake-name",
            "createdAt": "2023-10-23T23:15:18.792Z",
            "lastSeenAt": "2023-12-15T17:14:54.576Z",
            "stale": false,
            "environments": [
                {
                    "name": "development",
                    "enabled": true,
                    "type": "development",
                    "sortOrder": 100,
                    "variantCount": 0
                },
                {
                    "name": "production",
                    "enabled": false,
                    "type": "production",
                    "sortOrder": 200,
                    "variantCount": 0
                }
            ]
        }
    ]
}
```</div>

**Comment by ivarconr** [comment]
That endpoint does indeed return the description for feature toggles as well. It is the same API endpoint being used by the UI. 

You can validate this on the demo instance 
1. Login in at: https://app.unleash-hosted.com/demo/
2. Open https://app.unleash-hosted.com/demo/api/admin/projects/12712871/features in a separate tab. 

Validate description is part of the response


```json
{
    "version": 2,
    "features": [
        {
            "type": "release",
            "description": "Demo dataa ",
            "favorite": false,
            "name": "APIV2",
            "createdAt": "2024-01-04T04:23:18.273Z",
            "stale": false,
            "impressionData": false,
            "lastSeenAt": null,
            "environments": [
                {
                    "name": "default",
                    "enabled": true,
                    "type": "production",
                    "sortOrder": 1,
                    "variantCount": 0,
                    "lastSeenAt": null,
                    "hasStrategies": true,
                    "hasEnabledStrategies": true
                },
                {
                    "name": "development",
                    "enabled": false,
                    "type": "development",
                    "sortOrder": 2,
                    "variantCount": 0,
                    "lastSeenAt": null,
                    "hasStrategies": false,
                    "hasEnabledStrategies": false
                },
                {
                    "name": "production",
                    "enabled": false,
                    "type": "production",
                    "sortOrder": 3,
                    "variantCount": 0,
                    "lastSeenAt": null,
                    "hasStrategies": false,
                    "hasEnabledStrategies": false
                },
                {
                    "name": "dev",
                    "enabled": false,
                    "type": "development",
                    "sortOrder": 4,
                    "variantCount": 0,
                    "lastSeenAt": null,
                    "hasStrategies": false,
                    "hasEnabledStrategies": false
                },
                {
                    "name": "prod",
                    "enabled": false,
                    "type": "production",
                    "sortOrder": 5,
                    "variantCount": 0,
                    "lastSeenAt": null,
                    "hasStrategies": false,
                    "hasEnabledStrategies": false
                }
            ]
        }
    ]
}
```

**Comment by ianbbqzy** [comment]
I verified what you suggested on the demo app but it's still not working for us.

I tried http://unleash.company.ai/api/admin/projects/default/features and none of the feature toggles has no description.
If I go to the UI, it indeed calls this API, but even on our UI http://unleash.company.ai/projects/default, the table does not display the description either. there is also no "description" to be selected in the list of columns.

Then I tried http://unleash.company.ai/api/admin/projects/default/features/fake-feature and it does have the description, which is the endpoint used by the corresponding UI, which is probably why the description also shows up on that UI.

FYI we are self-hosting and have 200+ toggles. Is there anything that we need to do to enable "description" maybe just on the UI to start?

**Comment by sjaanus** [comment]
@ianbbqzy what unleash version are you running?

**Comment by ianbbqzy** [comment]
4.22.0

**Comment by ivarconr** [comment]
Hi @ianbbqzy, description was not included in the API response for features request on Unleash v4.22. You will only get it when you fetch the toggle details, e.g.

`http://localhost:4242/projects/:projectId/features/:toggleName`

Luckily, it should be quite straight forward to upgrade to latest version of Unleash (v5.8), which will also include a bunch of bug and security fixes.
