### ISSUE TITLE
Why is this happening 

### ISSUE THREAD

**Issue by jayok1234** [Unleash/unleash#5756]
### Describe the feature request

Why is aws showing my location elsewhere,  and I'm not getting web messages.  Does anything here have to do with my device jackd app not working?

### Background

Please stop blocking or restricting server and interaction my device

**Comment by sighphyre** [comment]
Hey @jayok1234, is this related to Unleash? This looks like an AWS issue?

**Comment by ivarconr** [comment]
Not related to Unleash.
