### ISSUE TITLE
Endpoint /api/frontend throws UnknownError when configured with AuthType.None

### ISSUE THREAD

**Issue by daveleek** [Unleash/unleash#5785]
### Describe the bug

When configuring Unleash with AuthType.None the endpoint /api/frontend breaks both with and without token.
It throws an "UnknownError" with the error message:
> Cannot destructure property 'type' of 'undefined' as it is undefined.

The desired behavior is shown in the endpoint /api/client/features which works both with and without token when Unleash is configured with AuthType.None

### Steps to reproduce the bug

1. export AUTH_TYPE=none
2. Start Unleash locally
3. Attempt to GET http://localhost:4242/api/frontend without specifying an Authorization header

### Expected behavior

Should return all toggles belonging to default project and the result of their evaluation.
If no token is supplied, the api should return all toggles belonging to default project and the result of their evaluation
If a token is supplied, the token's environment and project data should be respected.

### Logs, error output, etc.

```bash
[dev:backend] [2024-01-08T12:12:36.630] [DEBUG] controller/ProxyController - I encountered an error that wasn't an instance of the `UnleashError` type. The original error was: {}. It was mapped to {
[dev:backend]   "id": "85701fbb-1e14-4078-acf0-2db0e8126ea1",
[dev:backend]   "name": "UnknownError",
[dev:backend]   "message": "Cannot destructure property 'type' of 'undefined' as it is undefined.",
[dev:backend]   "details": [
[dev:backend]     {
[dev:backend]       "message": "Cannot destructure property 'type' of 'undefined' as it is undefined.",
[dev:backend]       "description": "Cannot destructure property 'type' of 'undefined' as it is undefined."
[dev:backend]     }
[dev:backend]   ]
[dev:backend] }
[dev:backend] [2024-01-08T12:12:36.630] [ERROR] controller/ProxyController - Server failed executing request: {} TypeError: Cannot destructure property 'type' of 'undefined' as it is undefined.
[dev:backend]     at ProxyService.assertExpectedTokenType (/Users/davidleek/Documents/code/unleash/dist/lib/services/proxy-service.js:79:38)
[dev:backend]     at ProxyService.clientForProxyToken (/Users/davidleek/Documents/code/unleash/dist/lib/services/proxy-service.js:45:22)
[dev:backend]     at ProxyService.getProxyFeatures (/Users/davidleek/Documents/code/unleash/dist/lib/services/proxy-service.js:24:35)
[dev:backend]     at ProxyController.getProxyFeatures (/Users/davidleek/Documents/code/unleash/dist/lib/routes/proxy-api/index.js:129:58)
[dev:backend]     at /Users/davidleek/Documents/code/unleash/dist/lib/routes/controller.js:45:23
[dev:backend]     at Layer.handle [as handle_request] (/Users/davidleek/Documents/code/unleash/node_modules/express/lib/router/layer.js:95:5)
[dev:backend]     at next (/Users/davidleek/Documents/code/unleash/node_modules/express/lib/router/route.js:144:13)
[dev:backend]     at validateMiddleware (/Users/davidleek/Documents/code/unleash/node_modules/@wesleytodd/openapi/lib/validate.js:109:14)
[dev:backend]     at validSchemaMiddleware (/Users/davidleek/Documents/code/unleash/node_modules/@wesleytodd/openapi/index.js:72:14)
[dev:backend]     at Layer.handle [as handle_request] (/Users/davidleek/Documents/code/unleash/node_modules/express/lib/router/layer.js:95:5)
[dev:backend]     at next (/Users/davidleek/Documents/code/unleash/node_modules/express/lib/router/route.js:144:13)
[dev:backend]     at /Users/davidleek/Documents/code/unleash/dist/lib/routes/controller.js:24:16
[dev:backend]     at Layer.handle [as handle_request] (/Users/davidleek/Documents/code/unleash/node_modules/express/lib/router/layer.js:95:5)
[dev:backend]     at next (/Users/davidleek/Documents/code/unleash/node_modules/express/lib/router/route.js:144:13)
[dev:backend]     at /Users/davidleek/Documents/code/unleash/dist/lib/routes/controller.js:14:16
[dev:backend]     at Layer.handle [as handle_request] (/Users/davidleek/Documents/code/unleash/node_modules/express/lib/router/layer.js:95:5)
[dev:backend] [2024-01-08T12:12:36.632] [INFO] HTTP - 500 GET /api/frontend
```

### Additional context

This is related to this issue: https://github.com/Unleash/unleash/issues/3005 along with linked PRs

### Unleash version

5.8

### Subscription type

Open source

### Hosting type

Self-hosted

**Comment by thomasheartman** [comment]
Nice one! I think we should add under "expected outcome":

> If no token is supplied, the api should return all toggles belonging to default project and the result of their evaluation
> If a token is supplied, the token's environment and project data should be respected.

But what happens if you provide an invalid token? 401 or the same as if no token? I'd lean towards the 401 because that's clearer to the user.

This also isn't entirely true:
> The desired behavior is shown in the endpoint /api/client/features which works both with and without token when Unleash is configured with AuthType.None

Because the api/client/features endpoint disregards the token entirely if AuthType is None: so even if you provide a token with a specified enviroment / projects, it disregards it and gives you all projects in the default environment. That's a separate bug, though.

**Comment by thomasheartman** [comment]
Oh, and for the record: I'm not entirely convinced that allowing you to call the endpoint without a token is the right thing to do, because it feels like we're encouraging it that way, and it probably won't do what you want it to do. However, there is an argument to be made that at least the client and frontend APIs will work the same if we do, so you get a consistent experience.

**Comment by daveleek** [comment]
Thank you @thomasheartman!

> I think we should add under "expected outcome":

Done!

> But what happens if you provide an invalid token? 401 or the same as if no token? I'd lean towards the 401 because that's clearer to the user.

Yeah that makes sense to me as well!

> This also isn't entirely true:

Ugh, I missed that! But yes, separate issue!

> I'm not entirely convinced that allowing you to call the endpoint without a token is the right thing to do, because it feels like we're encouraging it that way, and it probably won't do what you want it to do. However, there is an argument to be made that at least the client and frontend APIs will work the same if we do, so you get a consistent experience.

Indeed, this feels like it needs doing now for consistency, but deprecation and clearer use case could be warranted down the road

**Comment by thomasheartman** [comment]
Closing this now that https://github.com/Unleash/unleash/pull/6247. It seems the github auto-closer doesn't like the word "and".
