### ISSUE TITLE
any plans for a rust client?

### ISSUE THREAD

**Issue by rbtcollins** [Unleash/unleash#581]
I see there is a specification for clients, but can't see a community crate in crates.io, nor a repo here...

**Comment by ivarconr** [comment]
I would be happy to assist is anyone is up for the challenge. My rust knowledge is rather limited, but would love to learn a bit more by guiding someone in the implementation of a Unleash Client SDK.

**Comment by rbtcollins** [comment]
Thanks. We've developed one https://github.com/cognitedata/unleash-client-rust, docs https://docs.rs/unleash-api-client/0.1.0/unleash_api_client/index.html,
