### ISSUE TITLE
feat: Hooks to push notifications outbound

### ISSUE THREAD

**Issue by agardnerIT** [Unleash/unleash#587]
I'd like to push a notification to a webhook whenever I change a feature flag toggle.

For example, I'd like to change a flag and POST to a webhook with a payload that I define:

```
1. Change feature flag.
2. Send POST to https://example.com/endpoint1 with JSON payload
{"foo": "bar"}
```

**Comment by ivarconr** [comment]
This is actually already possible, but we plan to simplify this with explicit config and template language. 

To get this today read this example:
https://unleash.github.io/docs/guides/feature_updates_to_slack

**Comment by agardnerIT** [comment]
OK thanks, I see @jetzlstorfer mentioned this is slack too. I think we're considering it for the same use case so I'll catch up with him and see if he got anything working.

**Comment by jetzlstorfer** [comment]
Hi @agardnerIT  - yes I got it working. I don't have an example available on github but we can definitely follow up

**Comment by ivarconr** [comment]
@gnab already started on an initial "integrations" framework here in a [separate branch](https://github.com/Unleash/unleash/tree/integrations). I will try to pick it up and see if we can get it done.
