### ISSUE TITLE
The feature flags survey

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash#588]
We want to do a short survey on Feature flags. Not using Unleash? Not a problem, we would love to hear from you anyway - please respond using this link: [Unleash Feature flag survey](https://docs.google.com/forms/d/e/1FAIpQLSfcavE14vKclakkvlpMpYxEDwFnteQPxV3wS-G7qjTbV1bMIQ/viewform) 

We will pick 10 lucky winners among the responders, which get a $25 Amazon gift card. Feel free to share - also to non-Unleash users.

**Comment by elhoyos** [comment]
Hi @ivarconr, what is the purpose of the survey?

**Comment by ivarconr** [comment]
We want to learn a bit more about the landscape of the feature flags, which solutions are used, why they are using feature flags etc.

In addition; if they are using Unleash (Open-Source or Enterprise) we want to learn why they are using Unleash, and how we can improve the product.
