### ISSUE TITLE
StateService import generates empty events even if nothing is changed

### ISSUE THREAD

**Issue by b-dzoba** [Unleash/unleash#594]
We have some custom strategies which have to be applied to every enviroment. To avoid manualy creating these strategies we implemented import from file like this:
```
unleash
    .start({
       ...
    })
    .then(async ({app, stateService}) => {
      await stateService.importFile({file: 'server/strategies.json', userName: 'unleash'})
    });
```
However, this approach generates empty events in Unleash every time app restarts even if there are no real changes. Is it possible to change this behavior and generate events only if there is any real change in a strategy?
![unl](https://user-images.githubusercontent.com/30266053/81069127-286dd700-8eea-11ea-88ed-96b9ae6a3c9d.PNG)

**Comment by ivarconr** [comment]
Agree, empty events sounds a bit unnecessary.

**Comment by ivarconr** [comment]
**possible solution:**
Do of equal check before creating the change event. This also applies to feature toggles. 

PR welcome!

**Comment by ivarconr** [comment]
I think this can be solved with a small filter like this:

```js
toggleToImport.filter(newToggle => JSON.stringify(oldToggle) !== JSON.stringify(newToggle))
```
