### ISSUE TITLE
Listing Archived feature returning 500 error

### ISSUE THREAD

**Issue by ab-smith** [Unleash/unleash#5944]
### Describe the bug

Hello,
The API to get the archived features has been deprecated as mentioned below and it returns 500. What is the new standard way to get this please? do you mind updating the doc as well to reflect that?
https://docs.getunleash.io/reference/api/unleash/get-archived-features
Thank you

### Screenshots

<img width="837" alt="image" src="https://github.com/Unleash/unleash/assets/11318384/9583d6a1-e553-45b6-8dba-dc7a792a9adb">

### Subscription type

Enterprise

### Hosting type

None

**Comment by sjaanus** [comment]
Thank you for reporting this. I will take a a look.

**Comment by sjaanus** [comment]
Actually this is a bug, thanks for reporting it. This will be fixed in 5.9, which comes out this week.
