### ISSUE TITLE
feat: Add events for applications

### ISSUE THREAD

**Issue by goober** [Unleash/unleash#595]
Today there are events triggered when `feature` or `strategy` are created or changed. However I can see some usage for adding an additional event for `application-created`. Another event that could be useful is when an application is registering that is uses a new feature-toggle. 
 
See https://unleash.github.io/docs/api/admin/events

To give some context we have a case where we are trying to conform to the company's ITIL procedures while making it easy for developers to work with feature-toggles. We need to register a ticket in another system when a new feature-toggle is used by an application and then keep track of all changes done with that feature-toggle until it is archived.

**Comment by ivarconr** [comment]
should be pretty straight forward
