### ISSUE TITLE
instanceId clarification

### ISSUE THREAD

**Issue by xXxXxXxXxXam** [Unleash/unleash#602]
Hi! In looking at [docs](https://unleash.github.io/docs/api/client/register) and some of the sdks, it isn't super clear what the intent of the `instanceId` is.  Are there strict rules/guidelines for what it should be, or is it more open ended for implementations to decide?

Is it meant to be unique per device? For example, if on a mobile phone, it would be an id that was unique to that phone.  Each phone would have a different it.

Or unique per session? For example, in a mobile app, it would be different each time the app was opened?

Or unique per user-device? For example, it was unique to the device, but if a user logs out, it is regenerated.

Or unique to the app?  The app would have the same id on all devices?

Just want to make sure we are using it properly/as-intended.  Thanks!

**Comment by ivarconr** [comment]
Hi,

as most of SDKs are written for server-side the purpose of instanceId is to identify the the server instance (usually an application is replicated in n instances in a production environment). 

The purpose is to make it easy to verify that all instances of an application is able to connect to unleash, and when they where last seen. This can be valuable during debugging:
![image](https://user-images.githubusercontent.com/158948/83337323-983d6a80-a2ba-11ea-906d-5bcffca013e4.png)

**Comment by xXxXxXxXxXam** [comment]
Thanks!
