### ISSUE TITLE
Enable archived feature toggle through the REST API 

### ISSUE THREAD

**Issue by attiand** [Unleash/unleash#6040]
### Describe the bug

If I try to enable an archived toggle through the REST API I get a 200 (OK) in return. As the toggle is not active and the operation has no effect on the toggle I expected 4nn something.

### Steps to reproduce the bug

Running the following http requests (in vscode rest client):

```
# The unleash url
@url = 

# The admin api key
@key = 

@toggle = mytoggle

@env = development


### Create toggle
POST {{url}}/api/admin/projects/default/features
Content-Type: application/json
Accept: application/json
Authorization: {{key}}

{
    "name":"{{toggle}}",
    "type":"release",
    "description":"My toggle description"
}


### Archive toggle
DELETE {{url}}/api/admin/projects/default/features/{{toggle}}
Authorization: {{key}}


### Enable toggle
POST {{url}}/api/admin/projects/default/features/{{toggle}}/environments/{{env}}/on
Accept: application/json
Authorization: {{key}}
```

### Expected behavior

The last http response should be in the 400 range, but I get `200 OK`

### Unleash version

5.8.1

### Subscription type

Open source

### Hosting type

Self-hosted

**Comment by andreas-unleash** [comment]
Hi @attiand .  Thanks for bringing this to our attention. You are right, enabling an archived toggle will not have any impact, because 1. they are not served and 2. when you revive all environments will be turned off.  You are also right the response should be 400.

**Comment by andreas-unleash** [comment]
This [fixes it](https://github.com/Unleash/unleash/pull/6049).  It will be out with 5.9
