### ISSUE TITLE
Feature Suggestion: Disable Auto-Start of Unleash

### ISSUE THREAD

**Issue by Jakobo** [Unleash/unleash#605]
* **Unleash Version(s):** 3.3.5
* **Description:** Support `options.autostart = false` to disable the builtin call to `.listen()` on the express application

In some scenarios, unleash may be part of a more complex Express application. For example, you might be using unleash for feature flagging alongside an ML flagging system, or have more complex metrics endpoints you'd like to support on the same server. Currently, [the start method](https://github.com/Unleash/unleash/blob/master/lib/server-impl.js#L56) always triggers `.listen()` on its express app.

This proposal is to _not_ call `.listen()` when `options.autostart` is explicitly set to `false`, and instead automatically resolve the promise from `unleash.start`.

This doesn't take into account possible confusion around "start" not starting a server. If this is a concern, an alternative method `create({...options})` could exist, which automatically sets `autostart: false`.

### What it Would Look Like
```js
// example of autostart = false
const app = express();
const {app: unleashApp, server} = await unleash.start({
  ...options,
  autostart: false,
  baseUriPath: "/unleash"
});
console.log(typeof server); // undefined
app.use(unleashApp); // already mounts to baseUriPath

app.listen(process.env.PORT);
```

### Current Workaround
Without this feature, you can still prevent the default server from launching, though it's a bit of a hack. Using `options.preHook`, you can replace the internal express app's `listen()` method, nest the app into your own express app, and then externally start the server. However, you cannot `await` on the start method nor destructure the results as the promise will never resolve.

```js
// workaround
const app = express();
unleash.start({
  ...options,
  preHook: (unleashApp) => {
    app.use(unleashApp); // already mounts to baseUriPath
    unleashApp.listen = () => console.log("unleash relying on external express app");
  },
  baseUriPath: "/unleash"
});

app.listen(process.env.PORT);
```

**Comment by ivarconr** [comment]
Thanks, I like the suggestion. In fact, today, I would probably have designed it without and `app.listen` when unleash is used programmatically. 

PR welcomed! 
I would prefer the additional `create` function to make clearer for the user what happens.

**Comment by Jakobo** [comment]
I think that's a reasonable ask. I'll see what I can do for getting a PR together this weekend. It should be as simple as changing how we return the promise if `options.start` is false. Played around with a few option names and "start" felt the most obvious.
