### ISSUE TITLE
Error: Unleash Repository error

### ISSUE THREAD

**Issue by staufman** [Unleash/unleash#608]
Looking through our logs (both local development as well as live production), we seem to be seeing lots of the following error:

`Error: Unleash Repository error: Response was not statusCode 2XX, but was 502`

It's not clear if this is causing any issue _per se_ but we'd love to figure out what's going on so we can remove the noise from our logs. We see the message several times a day, usually spaced apart by a few hours.

Any idea what's happening here?

**Comment by ivarconr** [comment]
I agree, this should not be there. I assume this is in connection with the hosted offering? 

Would you mind reaching out on support@unleash-hosted.com or [connect with us on slack](https://join.slack.com/t/unleash-community/shared_invite/enQtNjUxMjU2MDc0MTAxLTJjYmViYjkwYmE0ODVlNmY1YjcwZGRmZWU5MTU1YTQ1Nzg5ZWQ2YzBlY2U1MjlmZDg5ZDRmZTMzNmQ5YmEyOGE)?

**Comment by ivarconr** [comment]
(Based in the error message, I assume you are using the Node.js SDK. It could actually be the "[Node.js 502 Bad Gateway Issues](https://github.com/nodejs/node/issues/24958)" you are facing. If you are using node 10 please make sure you are at `v10.15.x` or higher)

**Comment by staufman** [comment]
We're on Node 10.15.3 so presumably it's not due to our Node version? I'll go ahead and email support. Thanks!

**Comment by ivarconr** [comment]
closing this as it is being followed up in the support system.
