### ISSUE TITLE
Client  API Token-based Authentication

### ISSUE THREAD

**Issue by ryanermita** [Unleash/unleash#609]
I was able to create a `preRouterHook` to secure the client API endpoints. I followed the instructions provided on the [Securing Client section](https://unleash.github.io/docs/securing_unleash#securing-the-client-api) of Unleash documentation. But instead of sharing a `sharedSecret` key, I implement a token-based authentication. It works well during the initial client request to Unleash server.

Unleash client SDK polls from Unleash server depend on the set interval. The challenge happens when the token expires. The polling process will receive an unauthorized response due to the expired token. 

Is there a workaround to implement token-based authentication for client API? Or sharing `sharedSecret` is the currently supported implementation to secure the client API?

**Comment by ivarconr** [comment]
> Unleash client SDK polls from Unleash server depend on the set interval. The challenge happens when the token expires. The polling process will receive an unauthorized response due to the expired token.

Multiple of the client SDKs support dynamic headers (e.g. node sdk have the [customHeadersFunction](https://github.com/Unleash/unleash-client-node). This can be utilized to make sure the client always uses a valid token.

**Comment by ryanermita** [comment]
Thanks @ivarconr 
as per checking with python and java sdk repo. custom headers function is not yet supported.
we'll do some work around for the mean time, if time permits we'll contribute developing those feature for Python and Java SDK.  thanks again!

**Comment by ivarconr** [comment]
For reference, the Java SDK support [dynamic headers](https://github.com/Unleash/unleash-client-java#dynamic-custom-http-headers).

**Comment by ryanermita** [comment]
Thanks, @ivarconr, I'll try if this will also work on Python.
