### ISSUE TITLE
store feature toggles by user

### ISSUE THREAD

**Issue by jorgebo10** [Unleash/unleash#612]
Hi,

I've seen that logging in with different users shows always the same feature toggles. I assume that feature toggles are not stored per user. Is this feature planned for any release in the feature?
Thanks

**Comment by ivarconr** [comment]
We look at feature toggles as a collaboration tools for working with applications. We will introduce a project/namespace concept as part of the enterprise offering, but I can't say for sure if any of this will land in the open-source edition yet.
