### ISSUE TITLE
Unleash DB connection does not expose as config some SSL properties for Postgres

### ISSUE THREAD

**Issue by tcondeixa** [Unleash/unleash#613]
I'm trying to connect unleash to RDS postgres using SSL, but there are no options available to set the ca certificate nor to set rejectUnauthorized to false (https://node-postgres.com/features/ssl). In my case I'm not using two-way SSL connection but it might be usefull for other people to have also the path to key and certificate as a config option.

Is it possible you allow that to be specified in the options to start the unleash server?

Thanks a lot and nice you have been doing with unleash.

**Comment by ivarconr** [comment]
You can actually send all db options instead of databaseUrl: https://github.com/Unleash/unleash/blob/master/lib/options.js#L25

**Comment by tcondeixa** [comment]
> You can actually send all db options instead of databaseUrl: https://github.com/Unleash/unleash/blob/master/lib/options.js#L25
> 
> The ssl object is just passed on to the underlaying postgres driver and may contain custom CA certificate.

great, thanks a lot. Maybe adding that to the documentation will help others in the future.

**Comment by ivarconr** [comment]
You may also consider NODE_EXTRA_CA_CERTS and register the aws root certificate with your node application.

**Comment by tcondeixa** [comment]
> You may also consider NODE_EXTRA_CA_CERTS and register the aws root certificate with your node application.

I was about to consider that too, but if we have the option to set the rds certificate only for the DB connection I would prefer it. Is there any advantage in using NODE_EXTRA_CA_CERTS instead from your perspective?

**Comment by ivarconr** [comment]
I'm not sure of the actual benefits. Could be easier to instruct on a more global level, depending on how you manage configurations. AWS tends to change these certificates every 3 years.
