### ISSUE TITLE
Will this always be free/open-source?

### ISSUE THREAD

**Issue by ricardovf** [Unleash/unleash#621]
We are studying different options for feature flags management. Unleash seems great, we can run in our own cloud in a secure manner. Will this always be the case? Will the software be kept opensource and updated even when the company behind grows?

Thanks

**Comment by ivarconr** [comment]
Hi @ricardovf thanks for reaching out and showing an interest in Unleash. 

Unleash was born open source and our intention is to make it stay open source, as we fundamentally belive in the idea that software built for developers must be open source.  Also most of the customers are coming via the open source. 

We have chosen to pursue a commercial open source model (1). Building a company around Unleash has been the only way for us to be able to maintain and further develop Unleash. Some functionality will start out as enterprise only, but we are putting most of it in the open source. We will also move functionality from enterprise to the open source, when the time for that is right. We are constantly trying to find the right balance.

I would actually argue that having a successful company building on the open-source edition is an important aspect on securing further development and maintenance of Unleash. It also secures access to support, if that would be needed at some point. 

1) https://en.m.wikipedia.org/wiki/Business_models_for_open-source_software)

**Comment by ricardovf** [comment]
That is great to hear! We will start to test next week and my best wishes for the success of unleash!
