### ISSUE TITLE
🔥 feat: System for Cross-domain Identity Management (SCIM)

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash#6220]
### Describe the feature request

We want to add support for System for Cross-domain Identity Management (https://scim.cloud). This will make it possible to synchronize users and groups directly from your identity provider. 

Plan: **Enterprise**

**Comment by gastonfournier** [comment]
This was accidentally not released in 6.1.0 but on 6.1.4. For self-hosted, please make sure to update at least to that version to get SCIM working.
