### ISSUE TITLE
Create more complex rules for variant overrides

### ISSUE THREAD

**Issue by MarcusBondezan** [Unleash/unleash#6239]
### Describe the feature request

It should be possible to create more complex rules to define who will be accessing some variant. For example, I'd like all my users who have their `userId` ENDING WITH `0` to access that variant. Something similar the strategy constraints where we can elaborate more about the rules.

**Comment by kwasniew** [comment]
Hey @MarcusBondezan We have strategy variants https://docs.getunleash.io/reference/strategy created for the very reason that you mentioned - to enable all the strategy constraints for variants. The solution is to create multiple strategies (each with its own complex targeting rules) and assign a variant to each of them. Let me know if it helps.

**Comment by ivarconr** [comment]
closing this as it is solved via strategy variants.
