### ISSUE TITLE
fix: list parameters should be trimmed

### ISSUE THREAD

**Issue by hansjmelby** [Unleash/unleash#629]
When we send comma seperated parameters to the strategy ,it would be a Nice feature if they where trimmed so toggle is working even if we accidently send in blanc space before parameter
Example input we accidently uses : "user1,user2, user3, user4"

**Comment by madsop** [comment]
Indeed. Sometimes you happen by accident to use "_user1_ " instead of "_user1_", and that might be hard to spot. Struggling to see scenarios where you actually want to have list entry elements with trailing spaces...

**Comment by ivarconr** [comment]
Just to make sure i understand the scenario correctly. 

1. You add comma-seperated list as the input and click add
![image](https://user-images.githubusercontent.com/158948/92925550-f5f55d00-f43a-11ea-9268-ecd4e3a75713.png)

2. The user interface shows all the ids as chips:
![image](https://user-images.githubusercontent.com/158948/92925633-10c7d180-f43b-11ea-806a-a8ea97ceb203.png)

result: 
Some values now contains leading spaces?

**Comment by ivarconr** [comment]
Thanks. I think this can be solved pretty easily in the UI! 🎉

**Comment by ivarconr** [comment]
will be fixed as part of 3.6.0
