### ISSUE TITLE
Built in 'disabled' variant not specified

### ISSUE THREAD

**Issue by rbtcollins** [Unleash/unleash#633]
https://unleash.github.io/docs/toggle_variants says that a disabled feature receives the built-in disabled variant, but doesn't specify the payload etc for that variant, and the client-specification test for it has no payload key so it seems to short-circuit. Not entirely sure what clients should do here to be compatible with expectations.

**Comment by ivarconr** [comment]
Thanks, agreed. 

The shape of a disabled variant will be:

```json
{
   name: 'disabled',
   enabled: false,
}
```

**Comment by rbtcollins** [comment]
I think in rust it will be most convenient to have payload always present rather than having it hidden behind an Option:

```#[derive(Clone, Debug, Default)]
pub struct Variant {
    pub name: String,
    pub payload: HashMap<String, String>,
    pub enabled: bool,
}
```

which would make the disabled variant look like:
```
Variant{
   name: "disabled".to_string(),
   ..Default::default()
 }
```
