### ISSUE TITLE
is there a way to import features in a "migration style"?

### ISSUE THREAD

**Issue by jose-tissei** [Unleash/unleash#636]
Because of some network rules in the company i work at, we cant have only one unleash server to manage all our environments(dev,acceptance,prod) and we don't want to manually replicate the features between environments.
I tried using the import feature with files, but everytime the server restarts it ovewrites the current feature config with the ones contained in the files.
I wanted it to import from the file only once.
Is there any alternative? if not, is there a way for me to create my own migrations to insert my features?
I want to create the features in code, but also be able to change then trough the ui.

**Comment by ivarconr** [comment]
I think we could add an additional flag to the import api to not override existing flags, if they exists. 

You can also use the API direcly (https://unleash.github.io/docs/api/admin/features). You will get a 409 if you try å create a feature toggle which already exists.
