### ISSUE TITLE
constraints are not documented at https://unleash.github.io/docs/api/client/features

### ISSUE THREAD

**Issue by rbtcollins** [Unleash/unleash#637]
This makes it hard for SDK developers to implement; even though constraints in the API are enterprise only; SDK developers need to know all the API surface area to match it. I suspect context extensions are in the space.

**Comment by ivarconr** [comment]
I have the docs ready here, mind have a look? 
https://docs.google.com/document/d/1WxdODm1xKLaArucD7E5nHg4nruftRfkaWibaGV32GaI/edit?usp=sharing

Will add them to the official docs soon.

**Comment by rbtcollins** [comment]
Yep, thats good - having it in the API reference will be good too; not sure if what you linked will influence that - the specific url I linked to :).
