### ISSUE TITLE
constraints: undefined behaviour for empty, present list

### ISSUE THREAD

**Issue by rbtcollins** [Unleash/unleash#639]
There's an undefined corner case I think could be clarified. A missing key in the API document is obvious: behave as though no constraints have been provided an execute the strategies to determine enablement of the feature. Less obvious though is this:
```
{
                "name": "Feature.constraints.empty",
                "description": "What should this do?",
                "enabled": true,
                "strategies": [
                    {
                        "name": "default",
                        "parameters": {},
                        "constraints": []
                    }
                ]
            }
}
```

I suspect the intent is that this should act like a missing constraints key, but it would be nice to explicitly document this - e.g. through an additional conformance test in the client spec repository.

**Comment by rbtcollins** [comment]
Actually i think this is implicitly defined by the first test in 10-flexible-rollout-strategy.json; but it would be nice to make it explicit.

**Comment by ivarconr** [comment]
Yes agree. Will add a test-case for that as a specific case. 

Also; What do you think about: 

a) having the API reject empty list of constraints?
b) ....or having the API clearing empty constraints property?

**Comment by rbtcollins** [comment]
I think b is probably better, as some schema-driven editors might include an empty list (as I think happened in the file for 10...), and that would be a poor user experience.

**Comment by ivarconr** [comment]
I briefly looked at having the joi-schema strip empty lists, but it does not look straight forward, and would like to not introduce to much magic data-manipulation. 

I will rather address it with a proper specification tests for the SDKs, for now. 
https://github.com/Unleash/client-specification/pull/8
