### ISSUE TITLE
constraints: undefined behaviour for missing context items

### ISSUE THREAD

**Issue by rbtcollins** [Unleash/unleash#640]
What should happen for cases where the context item is missing? As distinct from present but empty.

environment and appName can't be absent, but userId, sessionId, remoteAddress and anything in properties can be. 

If we treat an absent value as an empty value, then for operator IN the behaviour is fairly predictable - assuming no-one ever deliberately puts "" into a value in the constraints values list.

However, an absent value treated as an empty value for the operator NOT_IN isn't as obvious: treating it as empty will mean we enable the constraint every time, (again, assuming no-one ever deliberately puts "" into a value in the constraints values list). But It seems to me that similar to NULL in SQL, this is a place where we should treat lack of knowledge as not knowing enough, and not enable the constraint when the context is entirely missing the selected contextName, rather than enabling it simply because the user hasn't populated the field.

**Comment by ivarconr** [comment]
So I have done the following:

1. values of a strategy constraints cannot be an empty string (`''`). This causes confusion any way. The Unleash api know does this validation as part of the input schema for a feature toggle. 
2. Added a few extra test cases for empty lists: https://github.com/Unleash/client-specification/commit/4b73fc58a70b9637630137f91823c4778ac34c91


I do wonder though for 2) if a strategy constraints with an empty list of values actually makes sense? Would it be better to say that a strategy constraint **must have** at least one value defined?

What do you think @rbtcollins?

**Comment by rbtcollins** [comment]
so e.g. for remoteID, either null, or "at least one comma separated member" ? makes sense to me
