### ISSUE TITLE
flexibleRollout case defined differently in docs to client specification

### ISSUE THREAD

**Issue by rbtcollins** [Unleash/unleash#641]
The docs here - https://unleash.github.io/docs/activation_strategy#flexiblerollout specify stickiness, but do not define it as case insensitive. However, the case in the client specification file 10-flexible-rollout-strategy.json is lowercase, not uppercase, which doesn't match. 

Should the comparison be case insensitive, or should the expected case be lowercase and the docs are wrong?

**Comment by ivarconr** [comment]
The documentation is wrong, should be `camelCase`.
