### ISSUE TITLE
Cloned feature toggles clone "created at" too

### ISSUE THREAD

**Issue by Nezz** [Unleash/unleash#6426]
### Describe the bug

Cloned feature toggles clone the `createdAt` date too. This results in an incorrect "created at" date for cloned features.

### Steps to reproduce the bug

1. Clone a feature that was created in the past. I used the UI with "Replace groupId" disabled.

### Expected behavior

The "created at" field of the feature toggle should reflect when the feature was actually created.

### Screenshots

![image](https://github.com/Unleash/unleash/assets/431167/e21fb4f2-ae50-4e8f-946f-f2c942713247)

### Unleash version

5.9.6

### Subscription type

Enterprise

### Hosting type

Hosted by Unleash

**Comment by ivarconr** [comment]
Thanks. This can be fixed by a one line fix removing the createdAt field here: https://github.com/Unleash/unleash/blob/095b6eca849d3858fc8e4010092ee28846ee719f/src/lib/features/feature-toggle/feature-toggle-service.ts#L1326
