### ISSUE TITLE
Bug: Can't remove all variants via UI

### ISSUE THREAD

**Issue by cnelson** [Unleash/unleash#646]
- Add a toggle via the UI
- Add two variant values to the toggles
- Attempt to delete the variants
  - Deleting the first one succeeds as expected
  - Deleting the second one, returns an error in the JS console:
```js
bundle.js:1 Uncaught Error: There must be atleast one variable variant
    at So (bundle.js:1)
    at Object.removeVariant (bundle.js:1)
    at n.onRemoveVariant (bundle.js:1)
    at removeVariant (bundle.js:1)
    at Object.<anonymous> (bundle.js:1)
    at d (bundle.js:1)
    at bundle.js:1
    at v (bundle.js:1)
    at it (bundle.js:1)
    at rt (bundle.js:1)
```

When the system is in this state, it is possible to remove the variant by manually making a PUT request to `/api/admin/features/<feat>` with the variant key removed from the JSON body.

**Comment by ivarconr** [comment]
Thanks for your report :muscle: 

This is a small regression from a recent UI feature. Fixed on master now, and will be part of next version of Unleash. You can play with the fixed version here: https://unleash.herokuapp.com/
