### ISSUE TITLE
Query on what load unleash can handle

### ISSUE THREAD

**Issue by prathik** [Unleash/unleash#650]
I have a high throughput api that at peaks 100K rps and was looking for any benchmark data.

I did do a benchmark locally and found that there is an entry added in client_metrics anytime a metric is pushed, what is the retention period for it? Could this table keep growing?

I did load test at 100K RPS, unleash performed fine, the only thing I noticed was client metrics kept increasing.

**Comment by ivarconr** [comment]
Hi, thanks for you questions. Metrics are currently held for one hour and instances are kept for one day. 

This might change later, but we have no immediate plans for this. 

You may also disable metrics in the SDK.

**Comment by ivarconr** [comment]
also: Metrics is aggregated in the client SDK and sent at regular intervals (60s). Unleash will only store the aggregated metrics from all client instances.

**Comment by prathik** [comment]
@ivarconr oh that's great, metrics at every 60s should be fine.

**Comment by prathik** [comment]
@ivarconr do you have any idea about someone using unleash in a high throughput prod environment?

**Comment by ivarconr** [comment]
@prathik yes indeed. both Finn.no (100k req/s) and Nav.no is using it in production, with hundreds of micro-services connected.

**Comment by prathik** [comment]
@ivarconr great, that helps. Resolving this ticket.
