### ISSUE TITLE
DEBUG: Cleaning up feature flag test

### ISSUE THREAD

**Issue by sjaanus** [Unleash/unleash#6559]
### Describe the bug

Cleaning up feature flag test

### Steps to reproduce the bug

Cleaning up feature flag test

### Expected behavior

Cleaning up feature flag test

### Logs, error output, etc.

```bash
Cleaning up feature flag test
```

### Screenshots

Cleaning up feature flag test

### Subscription type

None

### Hosting type

None

**Comment by sjaanus** [comment]
@gitar-bot cleanup proPlanAutoCharge=true

**Comment by sjaanus** [comment]
@gitar-bot cleanup proPlanAutoCharge=true

**Comment by ivarconr** [comment]
@gitar-bot cleanup celebrateUnleash=false

**Comment by sjaanus** [comment]
@gitar-bot cleanup globalFrontendApiCache=true

**Comment by sjaanus** [comment]
@gitar-bot cleanup useMemoizedActiveTokens=true

**Comment by sjaanus** [comment]
@gitar-bot cleanup proPlanAutoCharge=true

**Comment by sjaanus** [comment]
@gitar-bot cleanup proPlanAutoChargeSubscriptions=true

**Comment by sjaanus** [comment]
@gitar-bot cleanup sdkReporting=true

**Comment by sjaanus** [comment]
@gitar-bot cleanup increaseUnleashWidth=true

**Comment by sjaanus** [comment]
@gitar-bot cleanup outdatedSdksBanner=true

**Comment by sjaanus** [comment]
@gitar-bot cleanup newStrategyConfigurationFeedback=true

**Comment by sjaanus** [comment]
@gitar-bot cleanup newStrategyConfigurationFeedback=true

**Comment by sjaanus** [comment]
@gitar-bot cleanup returnGlobalFrontendApiCache=true

**Comment by ivarconr** [comment]
@gitar-bot cleanup stripClientHeadersOn304=true

**Comment by sjaanus** [comment]
@gitar-bot cleanup applicationOverviewNewQuery=true

**Comment by sjaanus** [comment]
@gitar-bot cleanup applicationOverviewNewQuery=true

**Comment by sjaanus** [comment]
@gitar-bot cleanup applicationOverviewNewQuery=true

**Comment by sjaanus** [comment]
@gitar-bot cleanup applicationOverviewNewQuery=true

**Comment by sjaanus** [comment]
@gitar-bot cleanup applicationOverviewNewQuery=true

**Comment by sjaanus** [comment]
@gitar-bot cleanup applicationOverviewNewQuery=true

**Comment by sjaanus** [comment]
@gitar-bot cleanup executiveDashboard=true
