### ISSUE TITLE
Purpose of toggle types.

### ISSUE THREAD

**Issue by innovation16** [Unleash/unleash#664]
Hey Unleash Team, I see that in version 3.5.0, toggle types were introduced. What is the exact purpose of these types?
If I create a release toggle with activation strategy "userWithId" and an experimental type toggle with the same strategy, how will they be different from one another?
Also, does the expiration duration actually make the toggle stale afterwards?

**Comment by ivarconr** [comment]
Hi thanks for your questions. 

> What is the exact purpose of these types?

Currently it's a way to communicate the purpose of a toggle. Currently there is no difference. We have a few ideas on how to use this information in the future. E.g.: It would be natural to facilitate more detailed metrics for a "experiment" toggle.

It can also be very beneficial information for integration with other tools. 

> Also, does the expiration duration actually make the toggle stale afterwards?

Not yet, but we are experimenting with tools to help marking expired toggles as stale. Next we will use the stale information in CI scripts and in the SDK to inform the developers that they are using stale feature toggles. 

Also: We welcome ideas and suggestion on how to add more value on top of this details.

**Comment by innovation16** [comment]
Thanks for your response Ivar. These are great ideas, I will definitely share if something comes up while I try to see how our workflows will be satisfied with unleash.

Can you also help me understand the difference between a stale and an archived toggle.

**Comment by ivarconr** [comment]
Stale toggles are still shared with clients. While archived will not.

**Comment by innovation16** [comment]
Oh! makes total sense. Thanks for the clarification.
