### ISSUE TITLE
Application Scoped Toggles

### ISSUE THREAD

**Issue by innovation16** [Unleash/unleash#666]
We have a requirement such that the toggles fetched both by the client and admin api are based on the app identifier. It seems like the client api already does it. Is this correct?
Also, right now there is no way to map a feature toggle to an app. Only the custom strategies can be as their implementation is in the app. 

I read in this blog that this feature was something you intended to bring.  Are there plans to support it?

**Comment by ivarconr** [comment]
Unleash has support for "projects" as part of the enterprise version, where you can group toggles in to projects. In the future a client SDK can be configured to only fetch toggles for defined project(s). A project can be used by one or more applications. 

The project feature is not part of the community edition. 

In the community edition you can use custom activation strategies to control roll-out per app, but the configuration will be visible to everyone.
