### ISSUE TITLE
Suggestions for some method signature changes

### ISSUE THREAD

**Issue by ByungjunYou** [Unleash/unleash#6738]
After reading the below code in `feature-toggle-strategies-store.ts`, I was confused with some method signatures.

I think the return type of `getFeatureOverviewData` should be `Record<string, IFeatureOverview>` instead of `IFeatureOverview`. Because `acc[row.feature_name] = { type: ..., description: ... }` suggests that `acc` is a record whose key is string type and value is IFeatureOverview type.

https://github.com/Unleash/unleash/blob/79fcfc26b8cdb08bdf4bad7e7631c312327e99d5/src/lib/features/feature-toggle/feature-toggle-strategies-store.ts#L731-L777

https://github.com/Unleash/unleash/blob/283a8f4d8bb2d6118e5b2529e7b201d7a5e62602/src/lib/types/model.ts#L208-L220

In case of the parameter type of `sortEnvironments`, it also might be correct to use `Record<string, IFeatureOverview>`. Since `Object.values(overview).map((data: IFeatureOverview)` strongly suggest that `overview` is a record whose value is `IFeatureOverview` type.

https://github.com/Unleash/unleash/blob/53354224fcf7dd198ac3078fd8444c87397b9f2c/src/lib/features/feature-toggle/feature-toggle-strategies-store.ts#L108-L120

If the suggestions make sense to you, I'm also open to make a PR for the fix. :)

**Comment by sjaanus** [comment]
Good catch, addressed it here https://github.com/Unleash/unleash/pull/6750

**Comment by ByungjunYou** [comment]
@sjaanus 
Thank you for the fix :)
