### ISSUE TITLE
feat: deprecate strategies

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash#682]
It should be possible to deprecate strategies. This should "hide them" from the feature toggle activation configuration.

**Comment by chriswk** [comment]
I`ll have a look.
First plan:
Introduce a deprecated field
Add support for toggling
Make endpoint used by feature toggle activation only fetch strategies that are `!deprecated`

**Comment by chriswk** [comment]
Will drop the last bit with the filtering, since our frontend currently uses the same strategies list for both the list of all strategies and the dropdown list for strategies, we'll use a filter in the frontend when displaying the dropdown for adding a strategy to a feature.
