### ISSUE TITLE
Make CORS configuration entries independent so they can managed with API calls

### ISSUE THREAD

**Issue by carlosjgp** [Unleash/unleash#6890]
### Describe the feature request

I would like the Unleash instance CORS configuration to be split into independent entries so they can be managed with independent API calls

This would enable a Terraform provider to manage each entry independently allowing multiple deployments with different URIs to be managed automatically

### Background

A company deploying its solution providing tenancy isolation to their clients using multiple cloud accounts, AWS in my case, would use different subdomains for each of its clients
- https://client1.domain.com
- https://client2.domain.com
- https://client3.domain.com
- ...

**Comment by andreas-unleash** [comment]
Hi @carlosjgp , thanks for your input. I will bring this up with the team and get back to you.

**Comment by andreas-unleash** [comment]
Hi @carlosjgp , we realise this an important issue and we added it to our backlog.  Unfortunately it will not be prioritised immediately but we will keep the issue open until it is resolved.   If it is something you need promptly and would be willing to create a PR for it, we would be thrilled to review and get it in quickly.
