### ISSUE TITLE
feat: Add support for filtering toggles by tags or projects

### ISSUE THREAD

**Issue by chriswk** [Unleash/unleash#690]
To make use of the recently added tag support as well as make more use of our projects, we'd like to make it possible to filter toggles by tags on the toggle or which project they belong to.

Initial thought for query spec
GET `https://unleash.host.com/api/admin/features?tags[]=type:value` should return all features tagged with tag `(type, value)`
GET `https://unleash.host.com/api/admin/features?projects[]=one` should return all features belonging to project `one`

You should be able to add more than one tag to parameter, which raises the question as to whether it should be an `AND` or an `OR` filter.

**Comment by ivarconr** [comment]
> You should be able to add more than one tag to parameter, which raises the question as to whether it should be an AND or an OR filter.

Good question. For projects the obvious answer is OR because a feature toggle can only belong to a single project.

**Comment by ivarconr** [comment]
Also the client API needs to support this:

`https://unleash.host.com/api/client/features?tags[]=type:value`

The client API also supports "namePrefix" today. 

The filtering should happen at the DB layer.

**Comment by chriswk** [comment]
Maybe default to OR, and add an operator parameter with possible values AND|OR?
