### ISSUE TITLE
Getting this error while running unleash app nodejs express

### ISSUE THREAD

**Issue by vkatoch2000** [Unleash/unleash#691]
] server-impl.js - [39mFailed to migrate DB error: remaining connection slots are reserved for non-replication superuser and rds_superuser connections

**Comment by ivarconr** [comment]
well, then you probably have to few connections available. Is this an RDS instance? How much memory have you allocated? How many unleash instances do you have?

**Comment by vkatoch2000** [comment]
it stopped working once we migrated to https

**Comment by vkatoch2000** [comment]
This is syntax we have used
const init = async (databaseUrl) => {
    const unl = await unleash.create({
        databaseUrl: databaseUrl,
        databaseSchema: 'subscribe',
        adminAuthentication: 'custom',
        preRouterHook: cognitoAuthorizer,
        serverMetrics: false
    });
     console.log(databaseUrl)
    const app = express();
    const {key, cert, passphrase} =  fetchSSLPropertiesFromSecret();
    app.use(unl.app);
    https.createServer({
        key: key,
        cert: cert,
        passphrase: passphrase
    }, app).listen(8000, function () {
        console.log('unleash listening on port 443! Go to https://localhost:443/')
    });
}

**Comment by vkatoch2000** [comment]
We have investigated it, it seems if we send the cert and key in incorrect formatting I mean everything in one line, it's not working as well not throwing error inside fargate container but locally it's showing an error, I am closing this, we have moved the certs and key to parameter store in AWS to keep certificate formatting intact

**Comment by vkatoch2000** [comment]
Closing this issue
