### ISSUE TITLE
Unleash JDBC URl became malformed with password conatins % 

### ISSUE THREAD

**Issue by vkatoch2000** [Unleash/unleash#699]
Unleash postgres  URL  malformed when  password conatins % , unleash start up failed

**Comment by vkatoch2000** [comment]
a possible solution to encode the password in encodeURIComponent(some-password)

**Comment by ivarconr** [comment]
This is why you should migrate away from dbUrl and use the db options instead:

https://unleash.github.io/docs/configuring_unleash

**Comment by vkatoch2000** [comment]
can we pass sslmode=require in db option

**Comment by ivarconr** [comment]
I believe setting ssl=true would achieve exactly that.
