### ISSUE TITLE
feat: Bypass unsecure auth screen behind proxy

### ISSUE THREAD

**Issue by theneva** [Unleash/unleash#701]
Hi! :wave:

I'm running Unleash behind GCP's Identity-Aware Proxy, so I don't really have a desire to set up auth in Unleash itself.

By default, Unleash requires the user to identify themselves with email (or username, I guess):

![image](https://user-images.githubusercontent.com/1404650/106525074-b7446a00-64e3-11eb-9179-6e455803bc55.png)

IAP sends a few pieces of information on the logged-in user as HTTP headers. For example, Grafana lets me [specify a header](https://grafana.com/docs/grafana/latest/auth/auth-proxy/#auth-proxy-authentication) to automatically sign up users, such as:

```ini
[auth.proxy]
header_name = X-Goog-Authenticated-User-Email
header_property = email
```

It would be super nice if I could specify something similar to bypass the screen. This would also ensure that I get the same value for each user every time. Setting it through an environment variable would be ideal, so I could continue using unleash-docker directly :smile:

Would you be interested in adding this feature?

If it's relatively easy, feel free to point me in the right direction and I'll be happy to have a crack at it!

**Comment by ivarconr** [comment]
Hi @theneva :wave: 

I think this should be fairly easy to support (without deep knowledge of all the details). We could add a new `adminAuthentication` option called `proxy` ([see configuring unleash](https://unleash.github.io/docs/configuring_unleash)) and allow a separate set of options to the proxy authentication. 

The implementation would be a built-in middleware probably quite similar to [simple-authentication.js](https://github.com/Unleash/unleash/blob/master/lib/middleware/simple-authentication.js). 

A quick look at [Securing Unleash](https://unleash.github.io/docs/securing_unleash)is probably also worth it for the implementation. 

A PR would be highly welcomed if you are up for it.

**Comment by ZeeFiix** [comment]
If you only want to bypass this login screen, then you can do this already with the current 3.10.1 version.

I added the env variable:
      # Switch of default admin authentication "unsecure" based on cookies
      # so that authentication over proxy-support is not blocked
      ADMIN_AUTHENTICATION: "none"

to my docker container, and the login screen is gone.

When you do that, then th admin-api is completely unauthenticated ....
For me it is currently not a problem due the reason that i have proxies in front of which are doing the authentication.

**Comment by jlowgren** [comment]
Reviving this since it's not closed.

After upgrading to v4 I noticed `ADMIN_AUTHENTICATION=none` no longer seems to work. I'm curious how to go about bypassing Unleash's own authentication completely now when configuring Unleash entirely through environment variables?

Reading the [docs](https://docs.getunleash.io/deploy/configuring_unleash), I'm assuming this has been replaced with `authentication.enableApiToken: false`, but that doesn't seem to be configurable through environment variable?

**Comment by jlowgren** [comment]
Just noticed in the source that there's now an `AUTH_ENABLE_API_TOKEN` variable. I'll try that.

**Comment by jlowgren** [comment]
That wasn't it, but supposedly `AUTH_TYPE=none` should accomplish the same thing as `ADMIN_AUTHENTICATION=none`, but I'm just presented with an endless spinner. No error messages anywhere.

**Comment by FredrikOseberg** [comment]
> That wasn't it, but supposedly `AUTH_TYPE=none` should accomplish the same thing as `ADMIN_AUTHENTICATION=none`, but I'm just presented with an endless spinner. No error messages anywhere.

We're aware of the issue. Expect a fix shortly.

**Comment by jlowgren** [comment]
Great to hear! 🙂 

Eagerly awaiting the fix.

**Comment by FredrikOseberg** [comment]
> 

Fix should be available and released yesterday in 4.3.2.

**Comment by jlowgren** [comment]
It works now. Thanks for the quick resolution!

**Comment by sighphyre** [comment]
Seems like this has been solved
