### ISSUE TITLE
fix: fine-tune the default db-settings for poolMin and poolMax

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash#705]
Currently Unleash uses the current defaults for the database pool:
- poolMin: 2
- poolMax: 20

After testing these settings with multiple customers and environments we have figured out that better defaults values should be. We have not seen any performance benefit of the old values. 
- poolMin: 0
- poolMax: 4

This would also address a newly discovered error where the db connection is terminated unexpectedly if Unleash has not received traffic for a while. This seems to be related to the following issue: https://github.com/knex/knex/issues/3523

**Comment by ZeeFiix** [comment]
It would help if you also can add the information somewhere how this settings can can be configured over environment variables / variable.

Are there already metric available about the current pool size ?
Think about the situation when poolMax is reached ..... Will it slow down then everything ?

**Comment by ivarconr** [comment]
> Are there already metric available about the current pool size ?

This is a good suggestion. We should probably add this to the Prometheus metrics. 

> Think about the situation when poolMax is reached ..... Will it slow down then everything ?

Yes, and we already publish metrics for a a lot of the critical database queries in the Prometheus metrics. If the query time increases, it should probably be worth considering increasing the pool size.

**Comment by ZeeFiix** [comment]
Yeah, such thing i had in mind at the time where i had asked.
When i seed query time increasing my first questions would be:
- Is there a database-pool ?
- If yes, is he limited and probably full in use ?
- What are the longest running statements in the database.
  (This we normally check in db side due the reason, that there is running more. Not only 1 database)

**Comment by chriswk** [comment]
I'm currently starting work on this. 

I'll make sure to add documentation and the key metrics mentioned here, whether or not we easily can get current pool size might require a bit more digging, but we can at the very least expose current min/max settings at our prometheus endpoint
