### ISSUE TITLE
feat: Send clear shutdown message to log in case of gracefull shutdown

### ISSUE THREAD

**Issue by ZeeFiix** [Unleash/unleash#706]
Hi together,
during investigation of "production readiness" for enterprise usage i had a look about the behavior if unleash docker container is stopped (scaled to 0 replicas)

I wonder a little bit, that unleash is not writing anything to the logs about the triggered shutdown.
For operational monitoring and root cause analyses in case of errors in bigger projects and multiple, multiple services, it would be really very important to be able to see in the logs later during investigation, if a shutdown was for example made "accidentally"

Can you add a step to the shutdown process to write a log entries ?
- "INFO: Graceful shutdown signal (SIGTERM) received. Stopping everything !" 
- "ERROR: Immediate shutdown (SIGKILL) received. Take the fast lane to exit !!!"

I am not sure if handling of SIGKILL is possible in this way, but i think it is now clear what i want to tell. 
Where logging during shutdown is possible, it really would be great if something like these examples could happen.

**Comment by ivarconr** [comment]
We should definitely add a handler from`SIGTERM` where we stop internal background tasks and close all active db-connections.

I think this would be a proper way of handling `SIGINT`: 

```js
process.on('SIGINT', async function() {
   try {
      logger.info("Graceful shutdown signal (SIGTERM) received. Stopping everything !");
      await unleash.stop();
      process.exit(0);
   } catch (e) {
      logger.error("Unleable to shutdown Unleash. Hard exit!", e);
     prcoess.exit(1);
  }
});
```

**Comment by ivarconr** [comment]
It's not possible to listen for `SIGKILL` in a node.js application, according to the [node.js documentation](https://nodejs.org/api/process.html):

> 'SIGKILL' cannot have a listener installed, it will unconditionally terminate Node.js on all platforms.
