### ISSUE TITLE
admin panel stuck within login screen

### ISSUE THREAD

**Issue by wennemer** [Unleash/unleash#7069]
### Describe the bug

Hi,
We have deployed unleash 5.12.2 with helm chart 4.1.1 within our kubernetes cluster including an ingress service:

- Our react frontend can connect to the server and is 100% functional.
- The admin panel can be reached directly by portforwarding from the cluster and is 100% functional

--
- The admin panel can not be reached by the subdomain https://unleash.domain.com:

- The login page stuck in loading state showing the spinner.
- There are no errors within the developer tools using edge or chrome browser
- Firefox maybe gives us a hint:
```
Source-Map-Fehler: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Ressourcen-Adresse: 
Source-Map-Adresse: renderer.js.map

Source-Map-Fehler: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Ressourcen-Adresse: 
Source-Map-Adresse: react_devtools_backend_compact.js.map

Source-Map-Fehler: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Ressourcen-Adresse: 
Source-Map-Adresse: backendManager.js.map

Source-Map-Fehler: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Ressourcen-Adresse: 
Source-Map-Adresse: installHook.js.map
```

N

### Expected behavior

Login screen to admin panel shoul apear

### Unleash version

5.12.2

### Subscription type

Open source

### Hosting type

Self-hosted

**Comment by rishiraj88** [comment]
The source files may not be accessible.

Are the json files or the json map files to be read available? May we verify their paths (locations) for reading them?

**Comment by wennemer** [comment]
We find a solution:
We normally use custom error pages in our nginx service.
I think the admin ui needs the error pages of the unleash server instead of our owns.
After removing these regarding the unleash server, everything is fine.

Thanks!

**Comment by Miskamyasa** [comment]
The same for me. How did you solve it exactly?
