### ISSUE TITLE
Add ability to not write feature definition to file system and use in memory cache

### ISSUE THREAD

**Issue by debangob** [Unleash/unleash#7099]
### Describe the feature request

We have cases where unleash SDK can be run from self hosted apps and as a result can leak PII information that is stored in feature definitions( context, strategies etc). Those cases are preventing us from using unleash in the product. Please consider providing a solution or using in memory caching, instead of writing to file system.

### Solution suggestions

In memory caching for (.net) SDKs

**Comment by ivarconr** [comment]
I think it make sense to be able to disable writing to file. Other SDKs (Java, Node) allow you to inject a custom file handler, and you can do a noop). Is this not possible on .net @daveleek ?

**Comment by sighphyre** [comment]
> I think it make sense to be able to disable writing to file. Other SDKs (Java, Node) allow you to inject a custom file handler, and you can do a noop). Is this not possible on .net @daveleek ?

Not on this SDK. The backup code is currently newed up directly rather than injected and there's no external hook to override that. Probably not hard to change just needs a bit of time to do so

**Comment by ivarconr** [comment]
Could we make the [FileSystem option public](https://github.com/Unleash/unleash-client-dotnet/blob/main/src/Unleash/UnleashSettings.cs#L123-L126)? That would allow anyone to provide their own FileSystem implementation that is a no-op?

**Comment by daveleek** [comment]
We should probably not expose this interface/property directly. This is a strange and very technology tied abstraction that is due a redo, so we don't want to commit ourselves to it. We should start work on an abstraction that gets us closer to where we want to be headed with this SDK, that would allow us to specify backup handling noop/custom/file/etc

**Comment by debangob** [comment]
Any updates on this issue?
