### ISSUE TITLE
Feat: Extend "current" import/export capability to support file as a startup argument. 

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash#7128]
### Describe the feature request

Extend "current" import/export capability to support file as a startup argument. 

### Background

v6 drops support for old state-servive. The impact of this change is that we loose the file-based import as a startup argument. We want to add support for that in the current import/export service. 

related to
https://github.com/Unleash/unleash/issues/6306

**Comment by daveleek** [comment]
Solved as of #7219 

Uses environment variables:
- `IMPORT_FILE` for file to import
- `IMPORT_PROJECT` for project to import to, defaults to `default`
- `IMPORT_ENVIRONMENT` for environment to import for, defaults to `development`
