### ISSUE TITLE
ARM64 arch image

### ISSUE THREAD

**Issue by kamilgregorczyk** [Unleash/unleash#717]
It would be great to include arm64 arch manifest to docker images

**Comment by ivarconr** [comment]
Hi @kamilgregorczyk ,

We have a specific repo to manage our docker releases;
https://github.com/Unleash/unleash-docker

I am a bit sure if Unleash would even run on arm64. Would you be up to figuring out the requirements nå possible add a PR to the docker project with the extra steps required to also build this distribution?
