### ISSUE TITLE
Strategy parameter list format specification

### ISSUE THREAD

**Issue by evenbrenden** [Unleash/unleash#7354]
### Describe the feature request

The client specification tests [suggests that strategy parameter lists use spacing in between values](https://github.com/Unleash/client-specification/blob/380cbb86d8b6ce66198050891f385d747b7beaf8/specifications/02-user-with-id-strategy.json#L54). In practice, clients receive values without spacing:

```
"strategies": [
      {
        "name": "userWithId",
        "parameters": {
          "userIds": "1,2,3"
        },
        "constraints": []
      }
    ],
 ```

Also, if space is added when entering the values, leading whitespace is removed, but trailing is not:

![screenshot](https://github.com/Unleash/unleash/assets/2512008/65fa8122-524f-4fc5-896b-b349e5244315)

```
    "strategies": [
      {
        "name": "userWithId",
        "parameters": {
          "userIds": "a,b,c    ,d"
        },
        "constraints": []
      }
    ],
```

I cannot find a specification for this parameter list string - apologies if I missed it.

This was tested against `Unleash 3.17.4` - old, I know, but I cannot see any similar issues merged since.

### Background

A specification would tighten parsing in Unleash clients.

### Solution suggestions

Specify the format for the parameter list string.

**Comment by ivarconr** [comment]
Hi, Unleash v3 is EOL more than 1 year ago. 

userWithId strategy is a deprecated strategy. In newer versions of Unleash you will use constraints instead. Constraints model values as proper arrays in the format and this is not a problem anymore.
