### ISSUE TITLE
Slack integration post when archiving a toggle is missing data

### ISSUE THREAD

**Issue by SimenB** [Unleash/unleash#740]
A picture is worth more than a 1000 words: 
![image](https://user-images.githubusercontent.com/1404810/109619461-17f1b180-7b39-11eb-861e-a20d347bd7eb.png)

There's 2 `undefined` in there, as well as an empty code block rendered as six backticks

**Comment by ivarconr** [comment]
I forgot that we do not add any data to the archive event. :facepalm:
