### ISSUE TITLE
Datadog integration body temple does not allow for full request customization

### ISSUE THREAD

**Issue by Tymek** [Unleash/unleash#7646]
### Describe the bug

Integration added will still parse body template into markdown and put it into "text" property.

### Steps to reproduce the bug

- go to integrations
- select Datadog integration
- set custom body template, for example
```
{
  "title": "hello",
  "text": "world",
}
```

### Expected behavior

Entire output should match template.

### Logs, error output, etc.

Output is:

```json
{
    "text": "{\n  \"title\": \"hello\",\n  \"text\": \"world\",\n}",
    "title": "Unleash notification update",
    "tags": []
}
```

### Unleash version

`>=5.6`

**Comment by Tymek** [comment]
Upon further investigation, it is possible now to create generic webhook for this purpose (not with dedicated "Datadog" integration).

Go to "integrations" -> "webhook". Set URL https://api.datadoghq.com/api/v1/events , add custom headers:
{
  "DD-API-KEY": "<YourApiKey>"
}
... and provide your event template.
 
Datadog documentation: https://docs.datadoghq.com/api/latest/events/#post-an-event
 
Also, ability to access "{{eventMarkdown}}" in generic webhook will be out soon. This will make it easier to format "text" property.

**Comment by devillecodes** [comment]
Thanks @Tymek. This is a great option for us.

Do you have an estimate for when the `"{{eventMarkdown}}"` will be available in the generic webhook?

**Comment by Tymek** [comment]
> Do you have an estimate for when the `"{{eventMarkdown}}"` will be available in the generic webhook?

Early next week. I'll update this issue when we ship it.

For now, you can verify your event template by running Unleash core locally, from source.

- `git clone git clone git@github.com:Unleash/unleash.git`
- in `docker-compose.yml` change `image: unleashorg/unleash-server:latest` to `build: .`
- `docker compose up`
- http://localhost:4242/integrations/create/webhook
- user: admin, password: unleash4all
You should be able to see new description below body template.

**Comment by devillecodes** [comment]
Hey @Tymek. Just checking in. Any update on the `"{{eventMarkdown}}"` field release?

**Comment by Tymek** [comment]
6.1 is in the process of being gradually rolled out. It should be fully out by the end of the week.

You should be able to see what version our instance is on in UI on the bottom, in footer
![image](https://github.com/user-attachments/assets/69d333a5-3e3d-4cdd-a980-f84e0c8f6cb4)

**Comment by devillecodes** [comment]
Amazing, thank you! I can confirm that the new `"{{eventMarkdown}}"` field works as expected.

For anyone else reading this, I did have to wrap the field in `%%%` for Datadog to interpret it as Markdown, for example:
```json
{
    "text": "%%%\n{{eventMarkdown}}\n%%%"
}
```
