### ISSUE TITLE
Feature toggle auto toggle by date

### ISSUE THREAD

**Issue by cristobal** [Unleash/unleash#765]
Is there anyway to have a toggle switch on by a given date?
e.g. firebase remote config allows us to specify such a condition:

![Screenshot 2021-03-17 at 11 43 23](https://user-images.githubusercontent.com/155505/111455364-fe925d00-8715-11eb-8277-e12c77e8e7ab.png)

Just can't seem to find such a feature from the UI or in the documentation.

**Comment by ivarconr** [comment]
You solve it via a custom activation strategy:
https://docs.getunleash.io/docs/advanced/custom_activation_strategy

But this is something we have been discussing that Unleash should support out of the box.

**Comment by cristobal** [comment]
Nice thanks for the help @ivarconr 👍🏽 
Yup i agree it would be nice if Unleash supported this out of the box.

**Comment by ivarconr** [comment]
this can now be solved with the new strategy constraint operators, introduced in v4.9
https://www.getunleash.io/blog/strategy-constraint-operators-new-and-improved
