### ISSUE TITLE
feat: Support smaller steps to Gradual rollout percentage

### ISSUE THREAD

**Issue by dbgsprw** [Unleash/unleash#7650]
### Describe the feature request

I want the Gradual Rollout feature percentage steps smaller than 1% (e.g., 0.1%, 0.01%)

### Background

In services with a large user base, releasing updates in 1% increments represents a significant proportion. Therefore, finer granularity helps prevent the spread of bugs and is advantageous when testing with small client groups.

### Solution suggestions

Instead of using the [constant value normalizer (100) in the SDK](https://github.com/Unleash/unleash-client-java/blob/90a872a49bdd9c97519351f9c3f8c0fa9736c4ad/src/main/java/io/getunleash/strategy/StrategyUtils.java#L7), [Get all flags (SDK) API](https://docs.getunleash.io/reference/api/unleash/get-all-client-features) provide additional param, Max Rollout Percentage value(e.g., 100, 1000, 10000, ...). The SDK will use both the `Rollout Percentage value` and the `Max Rollout Percentage value` together to determine the rate.

If you want this feature, I can create the Pull Request.

**Comment by chriswk** [comment]
Hi @dbgsprw - We're not going to do this right now, adding the possibility for this to all SDKs is not a small task, we've noted your 

If you want something similar you could solve it by creating a constraint where your resolution is whatever you'd want it to be. You won't get a slider to adjust the rollout percentage, but you could get whatever resolution you'd like
0. Setup a default strategy (enabled | disabled)
1. Configure custom constraint field named userHash
2. Configure constraint on strategy to say userHash LTE 90000 (if you want to have 100000 increments and do 90% rollout)
3. When building your context, find a consistent hashing algorithm (we use murmur3) to hash whatever value you want your stickiness to be on. We use (userId, sessionId, random or customer choice) concated with the `_<name of the feature>`
4. Hash your value and then do modulo <maxvalue> on your hash
5. Insert the result of the modulo into your userHash field in your context.
6. Evaluate the toggle with your context, gradual rollout is now applied with more fine grained increments
