### ISSUE TITLE
fix: improve addon stability with try/catch 

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash#766]
We can not assume addons do not contain programmatic errors, thus we should wrap the call where we execute event-handlers for specific addons in a try/catch. Also addons are assumed to be "async", so we should also do an await for that. 

The relevant code to improve is:
https://github.com/Unleash/unleash/blob/master/src/lib/services/addon-service.js#L86-L90

We could consider mapping all matching event-handlers to a list of async functions and use a Prmise.all() with try/catch to execute all in parallel.

**Comment by davidalpert** [comment]
the code inlining in the comment above? as far as I know github does that sometimes if not all the time. I copied this link to those lines from a specific commit (i.e. replaced the branch with the SHA of that commit) and pasted this into the comment:
```
https://github.com/Unleash/unleash/blob/b4b222f4c934a6e017c51be14ae544a1183138bc/src/lib/services/addon-service.ts#L86-L90
```
without the backticks of course - github seems to have done the rest, though I can't find a reference to that [in their documentation](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls#commit-shas)

I can look into submitting a PR for the issue.
