### ISSUE TITLE
Validation for Feature Toggle Type when creating a feature toggle is missing

### ISSUE THREAD

**Issue by meldsza** [Unleash/unleash#7751]
### Describe the bug

When creating a feature toggle via the API, there is no validation whether the feature toggle type exists or not.

### Steps to reproduce the bug

```sh
curl --location --request POST 'http://unleash:4242/api/admin/projects/default/features' \
    --header 'Authorization: APIKEY' \
    --header 'Content-Type: application/json' \
    --data-raw '{
  "type": "asdadsadasasd",
  "name": "TestFeatureValidation",
  "description": "TestFeatureValidation",
  "impressionData": false
}'
```
Gives
```json
{"name":"TestFeatureValidation","description":"TestFeatureValidation","type":"asdadsadasasd","project":"default","stale":false,"createdAt":"2024-08-05T08:37:02.863Z","lastSeenAt":null,"impressionData":false,"archivedAt":null,"archived":false}
```

Note that the type `asdadsadasasd` does not exist

### Expected behavior

I would expect an error with status code 422 stating the that the feature toggle does not exist

### Unleash version

Unleash 6.0.6

### Subscription type

Open source

### Hosting type

Self-hosted

**Comment by gastonfournier** [comment]
Hi @meldsza we'll look into it. It's been like that since forever, but we think it's an opportunity to make our API better as we expect the type to be one of the known types.
