### ISSUE TITLE
Performance tests

### ISSUE THREAD

**Issue by thaiscaldeira** [Unleash/unleash#792]
Hello Unleash Team!

Me and my team are currently studying implementing Unleash for our program and would like suggestions about how to test its performance.  

So far we thought about using [gatling.io](https://gatling.io/) to test request limitations, but wanted to know if anyone else used tools such as DataDog to evaluate Unleash's performance.

**Comment by ivarconr** [comment]
Great that you are performance testing. You should be aware of that the SDKs do the heavy lifting and not the service itself. 

Would advice you to have a look at ;

- https://docs.getunleash.io/docs/user_guide/
- https://www.unleash-hosted.com/articles/our-unique-architecture/

For single page apps /native you also have the Unleash Proxy, which handles the performance;

https://www.unleash-hosted.com/articles/the-unleash-proxy/
