### ISSUE TITLE
customizable variant behavior

### ISSUE THREAD

**Issue by clhuang** [Unleash/unleash#813]
Are there any plans to have more sophisticated variant strategies than simply percentage distribution? e.g. the ability to override based on user ID, etc. 

LaunchDarkly supports this: 
![image](https://user-images.githubusercontent.com/1694228/116282108-3b9f3580-a73f-11eb-959b-66e20cbb9ca9.png)

**Comment by ivarconr** [comment]
Hi, for [feature toggle variants ](https://docs.getunleash.io/docs/advanced/toggle_variants) you can customize who gets which variant based on any context fields (userId, project, region or an custom field) via overrides, in the Unleash Enterprise edition. 

![image](https://user-images.githubusercontent.com/158948/116283084-ca39a400-a78b-11eb-8972-ca10a41fdfc2.png)
