### ISSUE TITLE
Add tag details while getting features from client endpoint

### ISSUE THREAD

**Issue by priyanka-tw** [Unleash/unleash#819]
Hi 

As of now `api/client/features` does not return a lot of metadata for that feature. Just as strategies are returned, can we add tag details as well. 

I am aware that tag details are available in `api/admin/features`. Since at the client level there can post-processing on the basis of the tags are fetched and partitioned.

**Comment by ivarconr** [comment]
You can query feature toggles based on tags like this:

`GET https://unleash.host.com/api/client/features?tag[]=simple:taga&tag[]simple:tagb`

This allows you to fetch only feature toggles with the given tag/value pairs. 

The data-set out of the client SDK endpoint is a bare minimum in order to reduce the payload to the clients.

**Comment by priyanka-tw** [comment]
Exactly, when I fetch toggles based on tags in the stated way, I will not be able to identify which feature belongs to which tag. 
So if I have to do any post-processing, I will have to fetch tags individually, like so:

`GET https://unleash.host.com/api/client/features?tag[]=simple:taga`
`GET https://unleash.host.com/api/client/features?tag[]=simple:tagb`

And then handle the individual responses. 
This in turn increases the number of calls I have to make to the unleash server.

**Comment by ivarconr** [comment]
Could you please explain why you would like this included in the client API? The purpose of the `/api/client` endpoints is to support the client SDKs and be efficient. 

**How do you envision to use this information in your applciation?** 

Adding tags to the response will require us to due some cleverness on how we retrieve this data, to be efficient. We are a bit careful on not adding unnecessary data points to the `/api/client/features` before we have support for them in our SDKs.

**Comment by sighphyre** [comment]
Hi @priyanka-tw, I'm going to close this for now since it's been stale for a long while. If you think this shouldn't have been closed please feel free to reopen, we'd love to hear about your use case and how we can make Unleash better

**Comment by KrishKayc** [comment]
This is the use-case where I found tags being returned from client features would be helpful

   - I am adding the feature number / JIRA card story number as a TAG to the toggle
   -  Now in /api/client/features if tags come up, I can quickly figure out which toggles are created for which feature cards and do further analysis (in an automation script)
   - If not in tags, there is no way to link a feature name to a toggle. We can use description though but it is not the convention and will feel weird. 

If there are other suggestion for the above use case, please recommend. Don't want to use /api/admin/features as the automation tool might not have access and generating access token for this purpose is not intended

**Comment by atanas-balevsky** [comment]
We've similar use case where we'd like to evaluate a set of features based on their tag. e.g. `client.is_enabled_by_tag(tag_name, context) -> dict[str, bool]`

also using the client lib (python in our case) and its cache we can't read the features from /api/client/features and filter the cached features later for a specific tag

**Comment by varshapalat** [comment]
We have a similar usecase to fetch all the tags for a feature. This is in order to store and retrieve metadata info for a feature eg. consumers for this feature toggle
