### ISSUE TITLE
Sidepanel merged with footer, not differentiable

### ISSUE THREAD

**Issue by ShubhamShakyawal** [Unleash/unleash#8324]
### Describe the bug

link: https://app.unleash-hosted.com/demo/projects/demo-app

The side panel of the website is merged with the footer.

Here, the distinction is present:
![unleash pic 1](https://github.com/user-attachments/assets/169ab74c-245a-4129-816d-5065a2436492)

Whereas at the bottom, there is no distinction:
![unleash pic 2](https://github.com/user-attachments/assets/4ca8f19d-bc33-4406-9f3f-468d4dff56a9)

**Comment by ShubhamShakyawal** [comment]
Can I work on this issue? If it is really an issue, assign it to me.

**Comment by FredrikOseberg** [comment]
@ShubhamShakyawal I ran this by our UX department and this is actually intended, so if you don't mind I'll close this issue. Thank you!
