### ISSUE TITLE
Running multiple replicas

### ISSUE THREAD

**Issue by jdechicchis** [Unleash/unleash#835]
Is running multiple replicas of unleash supported out of the box by simply pointing all replicas to the same database? I may have missed it but I couldn't find a definitive answer in the docs.

**Comment by ivarconr** [comment]
Yes indeed that's supported. We should probably add that details to the [Deploy and manage section](https://docs.getunleash.io/docs/deploy/getting_started). 

Would you like purpose some wording on that @jdechicchis ?

**Comment by jdechicchis** [comment]
Perhaps we can add a short description at the end of the "Start Unleash Server" section right before the "Option one - use Docker" header such as
> To run multiple replicas of an unleash server simply point all instances to the same database.

I'm open to any additions since I'm not very familiar with unleash. In particular, I'm not sure if there is any additional complexity or "gotchas" that may warrant it's own section

**Comment by ivarconr** [comment]
#845
