### ISSUE TITLE
Unleash-Session Cookie Sent In Headers

### ISSUE THREAD

**Issue by ruthChavshush** [Unleash/unleash#8410]
### Describe the bug

Hi @ivarconr 
Further to this [issue](https://github.com/Unleash/unleash/issues/8029)
Sorry for the delay,
I cant reproduce it in the demo because its dns is different from my site which fetches the toggles, so the cookies are not shared.

### Subscription type

None

### Hosting type

None

**Comment by ruthChavshush** [comment]
@ivarconr
Can you pls reopen the original [issue](https://github.com/Unleash/unleash/issues/8029)🙏
I guess it would be more comfortable:))

**Comment by FredrikOseberg** [comment]
Continued in #8029
