### ISSUE TITLE
Feature Request: Support NestJs

### ISSUE THREAD

**Issue by paulwer** [Unleash/unleash#8575]
### Describe the feature request

Hi everyone,
would it be possible to create a wrapper for nestjs for the unleash-client lib, like https://www.npmjs.com/package/nestjs-unleash, which seems like its been abandoned?

Thank you guys :)

**Comment by gastonfournier** [comment]
Hi @paulwer maybe a full SDK is not needed, perhaps you can just use the node SDK from nestjs. There's also the alternative of cloning that repository and keep it community maintained. 

There's a cost on maintaining multiple SDKs so that's why our recommendation would be to try to use the node SDK without a wrapper.

Let us know if that's an option for you. We'd be happy to support or provide some documentation but building and supporting another SDK is not in our priority list.

**Comment by paulwer** [comment]
Hi @gastonfournier,
thanks for your answer. I totaly understand this and if thats the final descision i would go with your recomendation.
But I would like to explain again, what I meant.

The solution I suggested would not be an additional sdk and more like a wrapper of the existing sdk. 
Most likly, "Only" dependencies has to be maintained in the future. 
The wrapper will enable nestjs users to setup the unleash client more quickly and efficient, leading to a better developer experience. Also good to put this on your own product website with a quick-start 😇👉

I would offer to do the first implementation as a PR.

**Comment by gastonfournier** [comment]
> The solution I suggested would not be an additional sdk and more like a wrapper of the existing sdk.
> Most likly, "Only" dependencies has to be maintained in the future.

Still it might imply other changes when new features are added, but if you'd like to open a PR with a suggestion we'd be happy to look into it. It's always great to have contributions from our users/customers :)

**Comment by paulwer** [comment]
I will likly not be able to maintain it somewhere in the future, but as mentioned, I can provide a starting point.
So if thats ok for you to maintain it in the future, i would love to do this :)

Can you guide me, where such code should be placed? Same Repo/Other Repo?

**Comment by gastonfournier** [comment]
That's the thing, it's not something we'd like to maintain at the moment. https://github.com/pmb0/nestjs-unleash was community maintained and we were not involved (at least not to my knowledge). My suggestion would be to either contribute there or open a new one. If simple enough we might consider "adopting it" later, but right now having more things to maintain becomes an expensive liability.

**Comment by paulwer** [comment]
ok, thanks :)
