### ISSUE TITLE
missing fonts when no internet access

### ISSUE THREAD

**Issue by nesvold** [Unleash/unleash#863]
Thanks guys for a most excellent service :)
When the unleash server is hosted somewhere without internet, the ui looks a bit funky because the material icon fonts cannot be loaded from https://fonts.googleapis.com. Is there a suggested fix for this - something you want to look into?
Thanks again
(ps, using the docker image)

**Comment by ivarconr** [comment]
I like the idea of Unleash not requiring internet. 

We already plan on moving icons from font to svgs. For the fonts themselves i think we might need to look into good fallback variants. 

Thoughts @FredrikOseberg ?

**Comment by FredrikOseberg** [comment]
Agreed. We've already started using material ui's SVG icons in new components so the transition should be quite painless. It will increase bundle size slightly, but as long as we are careful to import correctly we will only increase it by the size of the single icon and not the entire material-ui icon package which is quite large. Bundle size is something we'll need to revisit later, but the transition to SVG will allow us to save a network request and pave the way for code splitting in the future to offset the cost of the initial request. 

For fonts, it makes sense to set up common system font fallbacks.

**Comment by FredrikOseberg** [comment]
Adding good first issue label, as I'm not sure when I can get to this. The work would be to open up a PR in https://github.com/Unleash/unleash-frontend and do the following steps: 

- Swap out all `<Icon>icon</Icon>` icons with dedicated icons from material ui: https://material-ui.com/components/material-icons/ (make sure you only import selected icons and not the entire material-ui icon package)
- Download and include Roboto font as an otf font referencing it from the app.css file
- Verify that the UI works offline by turning off the internet connection and checking that the icons load

**Comment by aneeshrelan** [comment]
I was looking to give this a shot if that's okay?

Quick question:

I can't seem to find some good ways to replace the dynamic usage of icon, Such as the below:

```tsx
<Icon>{icon}</Icon>
```

The above mechanism needs the [Material Icon font](https://material-ui.com/components/icons/#icon-font-icons) linked, or do I embed the font as well, just like that for Roboto?

**Comment by FredrikOseberg** [comment]
Go for it. We added material ui as part of our v4 release so you can import
the corresponding icon directly from material ui. Here is the link to the
material ui icon list:
https://material-ui.com/components/material-icons/

lør. 19. jun. 2021 kl. 13:47 skrev Aneesh Relan ***@***.***>:

**Comment by aneeshrelan** [comment]
Thanks @FredrikOseberg 

I've completed most parts i.e. replaced all usage of `<Icon>icon</Icon` and included Roboto as well into app.css

In replacing all usage of `<Icon>icon</Icon>`, there are a few which use the icon name dynamically. Example: `src/component/application/application-edit-component.js`

```tsx
<Avatar style={{ marginRight: '8px' }}>
    <Icon>{icon || 'apps'}</Icon>
</Avatar>
```

I'm not really sure how this can be replaced with the Material UI component, since this is coming from the application data via the API. Any inputs

**Comment by aneeshrelan** [comment]
I could fix the other places as well, only the above is left out. @FredrikOseberg if you have any inputs on how the above can be taken up?

**Comment by FredrikOseberg** [comment]
> I could fix the other places as well, only the above is left out. @FredrikOseberg if you have any inputs on how the above can be taken up?

In applications you can set a custom icon for your connected applications, and it uses the entire list of available icons from material icons. The only way I can think of to handle this is to map all material ui icons from the npm package to these named and then resolve them with dynamic imports to avoid importing all icons, but it probably isn't worth the effort. 

We are most likely going to change how this works, so I think you can safely leave this part out.

**Comment by aneeshrelan** [comment]
@FredrikOseberg [#309](https://github.com/Unleash/unleash-frontend/pull/309) raised in unleash-frontend

Looking forward to your reviews. Thanks
