### ISSUE TITLE
feat: allow activation strategy properties to be arrays

### ISSUE THREAD

**Issue by mmiermans** [Unleash/unleash#867]
The Unleash Context [defines properties to be map with string values](https://docs.getunleash.io/unleash_context/). In our use-case, we require a custom activation strategy to receive an array of strings.

As a workaround, we're json-encoding our array. It would be nice to be able to pass in arrays and objects into `properties` directly.

**Comment by ivarconr** [comment]
Hi @mmiermans ,

I think allowing the Unleash Context in the SDK to also accept properties of other types, especially arrays, would be nice. 

I wonder though how we can make this addition in static types languages without resorting to `ts:any` or `java:object` types. It would also be nice to introduce this without breaking existing user implementation of custom strategies. Do you have any suggestion on the actual implementation, that would be useful? Which languages are you currently using?

**Comment by mmiermans** [comment]
We only using the Node client. If I understand your question correctly, you're asking how to specify a type that can be encoded in JSON:
- A Python type is proposed in https://github.com/python/typing/issues/182, but as of 2020 people claim it's not mypy compatible:
  ```python
  JSON = t.Union[str, int, float, bool, None, t.Mapping[str, 'JSON'], t.List['JSON']]```
- A Typescript > 3.7 solution is mentioned [here](https://www.npmjs.com/package/json-types#deprecation-notice): 
  ```typescript
  type Json = 
    | string
    | number
    | boolean
    | null
    | { [key: string]: Json }
    | Json[];
  ```

**Comment by ivarconr** [comment]
Yes I agree this could work for the Node.js SDK. Maybe we can start with that one? Would you be interested in opening an pull-request in [unleash-client-node](https://github.com/Unleash/unleash-client-node)?

**Comment by BMDan** [comment]
> * A Python type is proposed in [Define a JSON type python/typing#182](https://github.com/python/typing/issues/182), but as of 2020 people claim it's not mypy compatible:
>   ```python
>   JSON = t.Union[str, int, float, bool, None, t.Mapping[str, 'JSON'], t.List['JSON']]
>   ```

Yeah, it's not, and there doesn't seem to be a lot of impetus developing to support recursive types.  In the meantime, depending on what depth you need to support, either the safe or unsafe MyPy implementations in [this link](https://gist.github.com/BMDan/ede923f733dfdf5ed3f6c9634a3e281f) provide a pretty decent typing safeguard, IMHO.
