### ISSUE TITLE
feat: New Relic integration

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash#878]
Hi all :wave: 

We already released the addon-framework where we want to provide out-of the box integrations with third party tools. It would be super helpful if someone familiar with New Relic could assist on building the New Relic integration. The idea is to inform New Relic about changes via [New Relic Custom events](https://docs.newrelic.com/docs/telemetry-data-platform/ingest-apis/introduction-event-api/). This can be very helpful when analyzing issues in New Relic. 

We have already written the integration for Datadog, and relevant code for this is:
- [datadog.js](https://github.com/Unleash/unleash/blob/master/src/lib/addons/datadog.js)
- [datadog-definition.js](https://github.com/Unleash/unleash/blob/master/src/lib/addons/datadog-definition.js)

Documentation:
https://unleash.github.io/docs/addons/datadog

**Comment by aneeshrelan** [comment]
I've been working with New Relic lately on a few projects. Can I take a stab at it?

**Comment by ivarconr** [comment]
> I've been working with New Relic lately on a few projects. Can I take a stab at it?

That would be just wonderful. Let us know if you need any assistance!

**Comment by aneeshrelan** [comment]
This will take slightly more time than expected. I could get the custom events in using a simple `curl` as per New Relic docs, but not through unleash. One thing that I could get is some Event name validations happening. The current events (from Datadog integration) is `feature-updated` (hyphenated) which doesn't seem to be supported

**Comment by ivarconr** [comment]
Thanks for the update. It's perfectly fine to re-map the event names if needed.

**Comment by alexandrusavin** [comment]
Hi @ivarconr, there is [this](https://github.com/Unleash/unleash/pull/7492) PR that adds New Relic Event API integration to Unleash. I know this is an old feature request but we'd use it if it would be available.

**Comment by ivarconr** [comment]
this is cool @alexandrusavin. Thanks for doing this!
