### ISSUE TITLE
Playground context field with allowed values should be indicated clearly

### ISSUE THREAD

**Issue by Tymek** [Unleash/unleash#8836]
### Describe the feature request

The dropdown menu, when you have a context field with a list of allowed values, is not different from the textfield. This makes it hard to know it is a dropdown and you are supposed to select an item.

### Background

- Go to "context fields"
- Create new context field
- Specify legal values
- Go to playground
- Select that context field

### Solution suggestions

![image](https://github.com/user-attachments/assets/9f0d72df-e95b-4101-91b4-556ae1d7c3ef)

---
Internal ticket [issue/UNL-224](https://linear.app/unleash/issue/UNL-224/playground-v2-indicate-dropdown)

**Comment by Curis-lab** [comment]
@Tymek  Does this design align with what you had in mind?

![image](https://github.com/user-attachments/assets/38dd37b4-2d0c-4722-90e1-d94cb98d110b)

Please let me know if there’s anything you’d like me to adjust!

**Comment by Tymek** [comment]
Yes! 👏🏻  Please mention this issue in a PR
