### ISSUE TITLE
Pre-filled strategy name not working in UI

### ISSUE THREAD

**Issue by RikudouSage** [Unleash/unleash#886]
When I go to an application registered in Unleash and it has strategies that are not implemented in the Unleash instance, there's a link to `/strategies/create?name=strategyName`, when you go there the strategy name is not prefilled and the field is empty.

**Comment by shanestillwell** [comment]
I see this behavior on 4.0.10

<img width="799" alt="Screen Shot 2021-08-10 at 9 52 32 AM" src="https://user-images.githubusercontent.com/203271/128889453-1e0f9d7c-6267-4f43-ab89-e748c993e7be.png">
