### ISSUE TITLE
Webhooks configuration reset issue

### ISSUE THREAD

**Issue by BkSouX** [Unleash/unleash#891]
When I try to setup webhooks, body template keeps resetting when I update it.
Same issue for the webhooks url.

You have to be quick before it resets to saved value.

**Comment by ivarconr** [comment]
You are talking about the UI i assume? Which version of Unleash are you using?

**Comment by ivarconr** [comment]
I can confirm the error. It will reset every time you get new state from the server. `useEffect` is probably not configured correctly. Do you mind taking a look @FredrikOseberg ?

**Comment by ivarconr** [comment]
Should be solved in 4.08
