### ISSUE TITLE
Error in Migration

### ISSUE THREAD

**Issue by wodka** [Unleash/unleash#897]
When executing the migrations manually I just saw that in https://github.com/Unleash/unleash/blob/master/src/migrations/20210618100913-add-cascade-for-user-feedback.js#L4

the constraint is dropped before it was created.

**Comment by ivarconr** [comment]
I can't remember if there was a reason for this. Do you @chriswk ?

**Comment by chriswk** [comment]
You think it's because you can't add a cascade to a constraint without dropping it and reapplying it with the desired cascade

**Comment by wodka** [comment]
@chriswk at least I couldn't find the constraint in any migration before this one. Trying to delete it without it existing then failed. (but perhaps it id created by something else?)

**Comment by ivarconr** [comment]
Now i remember. We hade to change the constraint added in [20210602115555-create-feedback-table.js](https://github.com/Unleash/unleash/blob/master/src/migrations/20210602115555-create-feedback-table.js#L7). 

The reason to add the CASCADE was that experience a bug where it was not possible to remove users if there was a reference to the user id inside the user_feedback table.

**Comment by wodka** [comment]
ah - then it seems cockroach names them differently. It was created as `fk_user_id_ref_users`
