### ISSUE TITLE
Support CockroachDB

### ISSUE THREAD

**Issue by wodka** [Unleash/unleash#898]
So far it seems the only broken things are:

* Migrations (I needed to manually execute them and sometimes change the queries)
* Session handling is broken as knex-session misses the type on the first value (already created an issue there: https://github.com/gx0r/connect-session-knex/issues/84)

important is to pass the "version" do the db settings. 
```
unleash
  .start({
    db: {
      version: '9.6',
    },
  })
  ```
Ideally the type should be updated to allow this without warnings.
![image](https://user-images.githubusercontent.com/385731/126658503-b379f2b6-dcfb-4d0d-a4c9-df6d7ba7ca8b.png)

**Comment by ivarconr** [comment]
Thanks. We are considering forking knex-session because we have outstanding issues that has not been solved.

**Comment by sergeyshaykhullin** [comment]
Any updates?

**Comment by ivarconr** [comment]
Sorry. The biggest blocker is the knex-session library that does not seem to respond to issues anymore. Thus we need to in-house that library to make progress. 

We currently have two issues with that library that we would love to fix:

- https://github.com/gx0r/connect-session-knex/issues/84
- https://github.com/gx0r/connect-session-knex/issues/72

**Comment by wodka** [comment]
There is another problem: 

there won't be support for skip lock in cockroach: https://github.com/cockroachdb/cockroach/issues/40476


the FeatureToggleStore.setLastSeen used skipLocked: https://github.com/Unleash/unleash/blob/master/src/lib/db/feature-toggle-store.ts#L147

-> could we add an option to disable this?

for to possible pass this down to knex I added a ticket there as well: https://github.com/knex/knex/issues/4899
