### ISSUE TITLE
feat: improve usage metrics

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash#908]
Today _usage metrics_ only shows the evaluations last minute and last hour. Usage metrics is only addressing evaluation of feature toggles, mostly for debug purposes, and **not** (performance metrics) used to evaluate experiments or if a new new feature is performing better than the previous version. 

We should iterate on the usage metrics. Some ideas:

- Filter _usage metrics_ on static context fields such as `environment` and `appName`. 
- Store _usage metrics_ in a history table over a longer time period. E.g. last 14 days. 
  - Every 10 min last hour
  - Hourly last 24 hours
  - Daily last 14 days
- Filter _usage metrics_ on user defined context fields. We need to be careful here, aggregation is key to keep the data usage at acceptable levels. In does not make sense to store all impressions in a `usage metrics` scenario.

Any other use cases we should consider? Feedback welcomed!

**Comment by fjcero** [comment]
Integration with Segment, Mixpanel, Amplitude, etc will be really a great improvement. How this could be architecture to follow Unleash principles? Flagsmith is a good example on how they are handling 3rd party integrations

**Comment by ivarconr** [comment]
v4.3 uses the new service, and exposes raw data for the last 48 hours. We still need to add a way to visualize the data.

**Comment by ivarconr** [comment]
was solved in v4.8
