### ISSUE TITLE
Certificate expired 

### ISSUE THREAD

**Issue by smksnutmeg** [Unleash/unleash#915]
Need to fix certs on this domain :)

https://docs.getunleash.io/sdks/

<img width="1364" alt="Screenshot 2021-08-17 at 15 02 32" src="https://user-images.githubusercontent.com/34444996/129740206-717306e5-932f-4ee1-818e-8a6e64e7c4a8.png">

**Comment by ivarconr** [comment]
Hmz. Certificates should be handled automatically by GitHub pages. Which country are you in?

**Comment by smksnutmeg** [comment]
UK - a colleague of mine is in spain too and having the same issue.

**Comment by ivarconr** [comment]
Are you able to see what it complain about? Running a few ssl verifications. So far it says everything is ok.

**Comment by ivarconr** [comment]
![Screenshot_20210817-163429_Chrome](https://user-images.githubusercontent.com/158948/129745848-16098b84-2a0f-4f6a-becb-635582e9c7db.jpg)

https://www.ssllabs.com/ssltest/analyze.html?d=docs.getunleash.io&s=185.199.108.153&latest

**Comment by smksnutmeg** [comment]
That's odd! I get this in browser.
```
docs.getunleash.io normally uses encryption to protect your information. When Google Chrome tried to connect to docs.getunleash.io this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be docs.getunleash.io, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Google Chrome stopped the connection before any data was exchanged.

You cannot visit docs.getunleash.io at the moment because the website sent scrambled credentials that Google Chrome cannot process. Network errors and attacks are usually temporary, so this page will probably work later.
```

**Comment by ivarconr** [comment]
Can it be a temporary thing with GitHub pages? Do you get errors in other browsers or incognito?

**Comment by ivarconr** [comment]
Unable to reproduce.
