### ISSUE TITLE
UI configurationdoes not work

### ISSUE THREAD

**Issue by klauss42** [Unleash/unleash#925]
It seems that the UI configuration (headerBackground, environment, slogan) as documented in https://docs.getunleash.io/deploy/configuring_unleash does not work and  has no impact at all.
Is this UI configuration still supported? If yes, how to use it?

**Comment by ivarconr** [comment]
We have no immediate plans for this. 

We are working hard to build in environment support, and we plan to also include parts of that capability in the open-source as well. This would allow you to serve more than one environment from a single instance.
