### ISSUE TITLE
Should the default SMTP(S) port be 587 instead of 567?

### ISSUE THREAD

**Issue by theneva** [Unleash/unleash#937]
Hi! :wave:

The config currently defaults the SMTP(S) port to 567, which is (as far as I know) not in common use by SMTPS services:

https://github.com/Unleash/unleash/blob/6ae49c44d009eeb3bc6f5fe88b46430ed9a35e9b/src/lib/create-config.ts#L124-L127

Unless I got lost in the huge diff, the default value was changed from 465 to 567 in https://github.com/Unleash/unleash/pull/794. 465 is pretty standard, but not as common as 587. This leads me to think that the intention was to change it to 587.

Should it be changed to 587? (Perhaps it's a change for the next major release?)

Just stumbled across it and wanted to give you a heads-up :smile:

**Comment by ivarconr** [comment]
I think this has to be considered a bug. It should have been 587. For our own offering we have set all these 

WDYT @chriswk

**Comment by chriswk** [comment]
> I think this has to be considered a bug. It should have been 587. For our own offering we have set all these email settings.
> 
> WDYT @chriswk ?

Yes, I'd say that is a bug
