### ISSUE TITLE
Chore: replace coveralls with jest coverage

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash#940]
https://github.com/marketplace/actions/jest-coverage-report

**Comment by aneeshrelan** [comment]
Is this something you're looking for help? I can take a go at this as part of hacktoberfest?

**Comment by ivarconr** [comment]
Yes that would be nice 🙂. I think first step would be to establish the jest coverage as a report back on the PR.

**Comment by ivarconr** [comment]
Its working for PRs now: 🚀 
![image](https://user-images.githubusercontent.com/158948/136264268-c3fb8218-6210-4782-bc9f-49b3b8a212de.png)

It should also be possible to reuse report.json files (e.g. the master run) to avoid running the tests twice. The docs does not give much guidance on how and where to store the report file from master:
https://github.com/ArtiomTr/jest-coverage-report-action#use-existing-test-reports

**Comment by aneeshrelan** [comment]
We can save the json file from master as an artifact using something like [this](https://docs.github.com/en/enterprise-server@2.22/actions/advanced-guides/storing-workflow-data-as-artifacts) and then downloading the artifact in the PR builds.

Something similar is mentioned on their docs in the above link:
`For example, you can save every test run to an artifact and then download and reference them here.`

**Comment by ivarconr** [comment]
Interesting! Want to dig in to it?

**Comment by aneeshrelan** [comment]
I am not able to run `yarn test:coverage` locally. I was trying to run on an action as well on my fork, similar errors. Refer [this](https://github.com/aneeshrelan/unleash/runs/3846235724?check_suite_focus=true)

Any idea what I might be missing? @ivarconr

**Comment by ivarconr** [comment]
Hi there. You will need to have postgres running locally with a database called unleash_test. Please see https://github.com/Unleash/unleash/blob/master/websitev2/docs/contributing/developer-guide.md

I think we actually should have some initial verification of this.

**Comment by ivarconr** [comment]
It should work, i don't have time to look in to it today, but you can diff with the final version for the pr build (i know you had similar issues with the first version as well, can't exactly remember what I did to fix it):

https://github.com/Unleash/unleash/blob/master/.github/workflows/build_prs_jest_report.yaml
