### ISSUE TITLE
fix: replace connect-session-knex with something

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash#945]
connect-session-knex does not handle errors and their are not handled in an async context. We should consider forking or finding a better alternative for this library.

**Comment by ivarconr** [comment]
https://github.com/Unleash/unleash/pull/875

**Comment by tn819** [comment]
Just reading through issues and thinking of starting to contribute as I find this to be a cool project...

Went down the rabbit hole and looks like `connect-session-knex` has resolved the error handling on db connect with a PR, so this should be fine?
https://github.com/gx0r/connect-session-knex/commit/0b580674765a2de745200d84734c8695a888c984

**Comment by ivarconr** [comment]
Was fixed in v3.0.0 of connect-sesion-knex
