### ISSUE TITLE
Server Metrics

### ISSUE THREAD

**Issue by Andersos** [Unleash/unleash#98]
Been watching [this](https://www.youtube.com/watch?v=czes-oa0yik) and we should add some metrics to Unleash. This seems to be a good  tool to use https://github.com/felixge/node-measured

**Comment by SimenB** [comment]
We should do this.

Using `prom-client`, as it's the thing we use internally.

I can provide a PR later

**Comment by SimenB** [comment]
@ivarconr As we talked about on Friday, show we instead emit events? Then we can wrap it internally (which we already do for config) to create prometheus metrics?

/cc @sveisvei

**Comment by ivarconr** [comment]
It sounds like a great idea yes! Can probably add some prometheus-addon later.
