### ISSUE TITLE
Question: how to use a custom context userId (like schoolId, gradeId)

### ISSUE THREAD

**Issue by jeancatarina** [Unleash/unleash#996]
how to use a custom context userId?

i tried:

```
unleash.updateContext({
  schoolId: "2",
})
```

![image](https://user-images.githubusercontent.com/20483048/135656672-9bf7044d-e481-4764-b20c-a8a6275d241a.png)

but didnt work....
I also tried by properties:

```
const propertiesMap = new Map()

propertiesMap.set('schoolIds', '2')

unleash.updateContext({
  properties: propertiesMap,
})
```

but didnt worked too

**Comment by ivarconr** [comment]
Hi there. 

In your example you have defined a custom activation strategy. To make that work you must also implement the code in the SDK for it to know how to use that strategy. See our documentation for reference:

https://docs.getunleash.io/advanced/custom_activation_strategy
